import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

const contextual = {
    support: "native" as const,
    availability: "context" as const,
    note: "需要已持久化的真实 Teams ConversationReference",
};

/** Teams 能力以 Microsoft 365 Agents SDK 与 Connector API 的真实实现为准。 */
export const teamsCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { ...contextual, scenes: ["private", "direct", "group", "channel"] },
        update_message: contextual,
        delete_message: contextual,
        get_group_list: { support: "native" },
        get_group_info: contextual,
        get_group_member_list: contextual,
        get_group_member_info: contextual,
        get_login_info: { support: "native" },
        get_status: { support: "native" },
        get_version: { support: "native" },
        get_supported_actions: { support: "native" },
        get_conversation_reference: contextual,
        list_conversation_references: { support: "native" },
        register_conversation_reference: { support: "native" },
        create_personal_conversation: {
            support: "native",
            availability: "permission",
            permissions: ["Teams app installed for target user"],
        },
        send_adaptive_card: contextual,
        send_targeted_message: { ...contextual, scenes: ["group", "channel"] },
        send_typing: contextual,
        send_file_consent_card: contextual,
        send_file_info_card: contextual,
        get_team_details: contextual,
        list_team_channels: contextual,
        get_conversation_member: contextual,
        list_conversation_members: contextual,
        list_conversation_members_paged: contextual,
        add_message_reaction: contextual,
        remove_message_reaction: contextual,
        get_meeting_info: contextual,
        get_meeting_participant: contextual,
        send_meeting_notification: {
            support: "native",
            availability: "permission",
            permissions: ["OnlineMeetingNotification.Send.Chat"],
        },
        call_graph_api: {
            support: "native",
            availability: "permission",
            permissions: ["Microsoft Graph application permissions for the requested resource"],
        },
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "channel"] },
        message_updated: { support: "native" },
        message_deleted: { support: "native" },
        reaction_added: { support: "native" },
        reaction_removed: { support: "native" },
        member_joined: { support: "native" },
        member_left: { support: "native" },
        interaction: { support: "native", note: "invoke 与 Adaptive Card 提交" },
        custom: {
            support: "native",
            note: "typing、installationUpdate、会议和其他 Activity 无损投影",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: {
            support: "native",
            direction: "both",
            note: "生成/解析用户 mention entity；Teams Bot 不支持通用 @all entity",
        },
        reply: { support: "native", direction: "send" },
        image: { support: "native", direction: "both" },
        file: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        adaptive_card: { support: "native", direction: "both" },
        card: { support: "native", direction: "both" },
        teams_activity: { support: "native", direction: "send" },
        teams_value: { support: "native", direction: "receive" },
    },
    transports: {
        webhook: { support: "native", mode: "webhook" },
    },
});
