import {
    BaseApp,
    ConfigRestartRequiredError,
    yaml,
    ProtocolRegistry,
    configure,
    Protocol,
    readLine,
    initTokenManager,
    writeConfigFileAtomic,
    type Account,
} from "@onebots/core";
import { getAppConfigSchema } from "./config-schema.js";
import { registerAuthRoutes } from "./routes/auth.js";
import { registerConfigRoutes } from "./routes/config.js";
import { registerAdapterRoutes } from "./routes/adapter-api.js";
import { registerVerificationRoutes } from "./routes/verification.js";
import { registerTerminalRoutes } from "./routes/terminal.js";
import { registerPublicStaticRoutes } from "./routes/public-static.js";
import { registerMessageDebugRoutes } from "./routes/message-debug.js";
import { registerExtensionRoutes } from "./routes/extensions.js";
import { LogCacheManager } from "./log-cache.js";
import { VerificationManager } from "./verification-manager.js";
import { HfBackupService } from "./hf-backup.js";
import { MessageDebugManager } from "./message-debug.js";
import * as path from "path";
import * as fs from "fs";
import { createRequire } from "module";
import { pathToFileURL } from "url";
import koaStatic from "koa-static";
import { existsSync, writeFileSync, mkdirSync, readFileSync } from "fs";
import type { WsServer, Dict } from "@onebots/core";
import { getLoadedPlugins, loadPlugin, pluginCandidates } from "./plugin-loader.js";
import { writeCliError, writeCliOutput } from "./cli-output.js";
import {
    parseRuntimeConfig,
    validateAccountConfigCandidate,
    validateRuntimeConfig,
} from "./runtime-config-validator.js";
import { getAdapterInfos } from "./adapter-info.js";
import { handleManagementConfigSocketAction } from "./management-config-socket.js";
import {
    authorizeManagementUpgrade,
    extractManagementToken,
    managementCredentialsChanged,
    validateManagementToken,
} from "./management-auth.js";
import { startManagementAuthorizationMonitor } from "./management-authorization-monitor.js";
import type { WebSocket } from "ws";
import type { ServerResponse } from "node:http";
import { ensureManagementCredentials } from "./management-credentials.js";
import { RuntimeConfigStateTracker } from "./runtime-config-state.js";
import {
    getRuntimePluginSelection,
    type RuntimePluginSelection,
} from "./runtime-plugin-selection.js";
import { ExtensionManager } from "./extension-manager.js";
import { preflightServiceRuntimeIsolated } from "./service-preflight.js";
import packageMetadata from "../package.json" with { type: "json" };
import {
    applyManagementDocumentSecurityHeaders,
    isManagementSpaPath,
    renderManagementIndexHtml,
} from "./management-index.js";
import { isProcessRestartSupported } from "./process-restart.js";
import { ensureRuntimeDataDirectory } from "./runtime-data-directory.js";

const require = createRequire(pathToFileURL(path.join(process.cwd(), "node_modules")));

const client = (() => {
    const rel = ["..", "node_modules", "@onebots", "web", "dist"];
    const candidates = [
        path.join(import.meta.dirname, ...rel),
        path.join(process.cwd(), "node_modules", "@onebots", "web", "dist"),
        path.join(import.meta.dirname, "..", "..", "..", "packages", "web", "dist"),
    ].map(p => path.resolve(p));
    for (const dir of candidates) {
        if (existsSync(dir)) {
            return dir;
        }
    }
    return "";
})();

export class App extends BaseApp {
    public ws: WsServer;
    private _logCache: LogCacheManager;
    private _verification: VerificationManager;
    private _hfBackup: HfBackupService;
    private _messageDebug: MessageDebugManager;
    public ptyTerminal: ReturnType<typeof import("@karinjs/node-pty").spawn> | null = null;
    public terminalClients: Set<WebSocket> = new Set();
    private readonly runtimeConfigStateTracker: RuntimeConfigStateTracker;
    public readonly extensionManager: ExtensionManager;
    /** 退出码 75 后是否有守护器或编排器负责拉起新实例。 */
    public readonly restartSupported = isProcessRestartSupported();

    private static readonly DEFAULT_TOKEN_EXPIRATION_MS = 12 * 60 * 60 * 1000;
    private static readonly REFRESH_TOKEN_EXPIRATION_MS = 7 * 24 * 60 * 60 * 1000;
    public tokenManager = initTokenManager({
        defaultExpiration: App.DEFAULT_TOKEN_EXPIRATION_MS,
        refreshExpiration: App.REFRESH_TOKEN_EXPIRATION_MS,
    });
    public credentialsWereAutoGenerated = false;

    // 代理属性：路由文件通过这些属性访问管理器内部状态
    get logClients() {
        return this._logCache.clients;
    }
    get logCacheFile() {
        return this._logCache.cacheFile;
    }
    registerLogClient(client: ServerResponse, dispose: () => void): void {
        this._logCache.registerClient(client, dispose);
    }
    removeLogClient(client: ServerResponse): void {
        this._logCache.removeClient(client);
    }
    registerVerificationClient(client: ServerResponse, dispose: () => void): void {
        this._verification.registerClient(client, dispose);
    }
    removeVerificationClient(client: ServerResponse): void {
        this._verification.removeClient(client);
    }
    get pendingVerifications() {
        return this._verification.pending;
    }
    get messageDebug() {
        return this._messageDebug;
    }

    constructor(config: App.Config) {
        super(config, { name: packageMetadata.name, version: packageMetadata.version });
        this.runtimeConfigStateTracker = new RuntimeConfigStateTracker(BaseApp.configPath);
        this.extensionManager = new ExtensionManager({ configPath: BaseApp.configPath });

        if (client) this.logger.info(`使用 Web 前端目录: ${client}`);
        else this.logger.warn("未找到 @onebots/web/dist，管理端页面将不可用");

        this._logCache = new LogCacheManager(path.join(BaseApp.dataDir, "terminal-logs.txt"));
        this._logCache.interceptStdio();
        this._verification = new VerificationManager();
        this._hfBackup = new HfBackupService(this.logger);
        this._messageDebug = new MessageDebugManager();
        this.ws = this.router.ws("/", {
            authorize: request => authorizeManagementUpgrade(this, request),
        });

        const cleanupLogCacheOnExit = () => this._logCache.cleanupSync();
        process.once("exit", cleanupLogCacheOnExit);
        this.once("close", async () => {
            process.off("exit", cleanupLogCacheOnExit);
            const failures = this.disconnectManagementStreams();
            try {
                await this._logCache.cleanup();
            } catch (error) {
                failures.push(error);
            }
            if (failures.length === 1) throw failures[0];
            if (failures.length > 1) {
                throw new AggregateError(failures, "管理事件流清理未完整完成");
            }
        });
    }

    getPendingVerificationList(): Record<string, unknown>[] {
        return this._verification.getPendingList();
    }

    async backupDataToHf(configContent: string) {
        return this._hfBackup.backupData(configContent);
    }

    async backupDataDirToHfAfterStaticChange() {
        return this._hfBackup.backupAfterStaticChange();
    }

    protected onAdapterCreated(adapter: import("@onebots/core").Adapter): void {
        adapter.on("verification:request", (payload: Record<string, unknown>) => {
            this._verification.storeAndBroadcast(payload);
        });
        adapter.on("verification:clear", (payload: Record<string, unknown>) => {
            this._verification.clearAndBroadcast(payload);
        });
        adapter.on(
            "message:dispatch",
            (payload: { platform: string; account_id: string; event: unknown }) => {
                this._messageDebug.recordInbound(
                    payload.platform,
                    payload.account_id,
                    payload.event,
                );
            },
        );
        adapter.on(
            "message:protocol-dispatch",
            (payload: {
                platform: string;
                account_id: string;
                protocol: string;
                version: string;
                data: unknown;
            }) => {
                this._messageDebug.recordOutbound(
                    payload.platform,
                    payload.account_id,
                    payload.protocol,
                    payload.version,
                    payload.data,
                );
            },
        );
    }

    /** 为 REST 与 WebSocket 提供同一份带注册元数据的适配器摘要。 */
    get adapterInfos() {
        return getAdapterInfos(this.adapters.values(), this.pluginInfos);
    }

    /** 当前进程真正通过加载与注册契约校验的插件包清单。 */
    get pluginInfos() {
        return getLoadedPlugins();
    }

    /** 当前磁盘配置是否仍与最近一次成功应用的来源一致。 */
    get runtimeConfigState() {
        return this.runtimeConfigStateTracker.inspect();
    }

    markRuntimeConfigApplied(configPath: string, source: string): void {
        if (configPath === BaseApp.configPath) this.runtimeConfigStateTracker.markApplied(source);
    }

    /** 使用守护服务的真实解析目录验证磁盘配置和全部待启动插件。 */
    async preflightRestart(): Promise<void> {
        const config = parseRuntimeConfig(fs.readFileSync(BaseApp.configPath, "utf8"));
        const selection = getRuntimePluginSelection(config);
        const loadedPlugins = this.pluginInfos;
        await preflightServiceRuntimeIsolated({
            configPath: BaseApp.configPath,
            adapters:
                selection?.adapters ??
                loadedPlugins
                    .filter(plugin => plugin.type === "adapter")
                    .map(plugin => plugin.name),
            protocols:
                selection?.protocols ??
                loadedPlugins
                    .filter(plugin => plugin.type === "protocol")
                    .map(plugin => plugin.name),
            workingDirectory: process.cwd(),
        });
    }

    protected override onConfigPersisted(configPath: string, content: string): void {
        this.markRuntimeConfigApplied(configPath, content);
    }

    protected override validateAccountConfigCandidate(
        configKey: string,
        config: Account.Config,
    ): void {
        validateAccountConfigCandidate(
            this.config as unknown as Record<string, unknown>,
            configKey,
            config as unknown as Record<string, unknown>,
        );
    }

    async start() {
        this.assertCanStart();
        if (this.isStarted) return;

        try {
            await this.startRuntime();
        } catch (error) {
            // BaseApp.start 已完成回滚时，直接保留其聚合错误。
            if (this.isDisposed) throw error;
            await this.rollbackFailedStart(error);
        }
    }

    private async startRuntime() {
        validateRuntimeConfig(this.config as Record<string, unknown>);
        registerAuthRoutes(this, this.router);
        registerConfigRoutes(this, this.router);
        registerAdapterRoutes(this, this.router);
        registerVerificationRoutes(this, this.router);
        registerTerminalRoutes(this, this.router);
        registerPublicStaticRoutes(this, this.router);
        registerMessageDebugRoutes(this, this.router);
        registerExtensionRoutes(this, this.router);

        if (!existsSync(BaseApp.logFile)) {
            const dir = path.dirname(BaseApp.logFile);
            if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
            writeFileSync(BaseApp.logFile, "", "utf8");
        }
        const fileListener = (eventType: string) => {
            if (eventType === "change")
                this.ws.clients.forEach(async client => {
                    client.send(
                        JSON.stringify({
                            event: "system.log",
                            data: await readLine(1, BaseApp.logFile),
                        }),
                    );
                });
        };
        const logWatcher = fs.watch(BaseApp.logFile, fileListener);
        let logWatcherClosed = false;
        const closeLogWatcher = () => {
            if (logWatcherClosed) return;
            logWatcherClosed = true;
            process.off("disconnect", closeLogWatcher);
            logWatcher.close();
        };
        this.once("close", closeLogWatcher);
        process.once("disconnect", closeLogWatcher);

        this.ws.on("connection", async (client, request) => {
            const managementToken = extractManagementToken(request);
            const stopAuthorizationMonitor = startManagementAuthorizationMonitor(
                this,
                managementToken,
                {
                    onUnauthorized: () => client.close(1008, "Unauthorized"),
                },
            );
            client.once("close", stopAuthorizationMonitor);
            client.send(
                JSON.stringify({
                    event: "system.sync",
                    data: {
                        config: fs.readFileSync(BaseApp.configPath, "utf8"),
                        adapters: this.adapterInfos,
                        protocol: ProtocolRegistry.getAllMetadata(),
                        plugins: this.pluginInfos,
                        configState: this.runtimeConfigState,
                        app: this.info,
                        schema: getAppConfigSchema(),
                        logs: fs.existsSync(BaseApp.logFile)
                            ? await readLine(100, BaseApp.logFile)
                            : "",
                    },
                }),
            );
            client.on("message", async raw => {
                if (!validateManagementToken(this, managementToken).valid) {
                    client.close(1008, "Unauthorized");
                    return;
                }
                let payload: Dict = {};
                try {
                    payload = JSON.parse(raw.toString());
                } catch {
                    return;
                }
                const configResponse = await handleManagementConfigSocketAction(this, payload);
                if (configResponse) {
                    try {
                        return client.send(JSON.stringify(configResponse));
                    } catch (error) {
                        this.logger.error("发送管理端配置回执失败", { error });
                        return;
                    }
                }
                switch (payload.action) {
                    case "system.input":
                        process.stdin.resume();
                        process.nextTick(() =>
                            process.stdin.emit("data", Buffer.from(payload.data + "\n", "utf8")),
                        );
                        process.nextTick(() => process.stdin.emit("end"));
                        return true;
                    case "bot.start": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOnline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                    case "bot.stop": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOffline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                }
            });
        });

        for (const [, adapter] of this.adapters) {
            if (!adapter.listenerCount("verification:request")) {
                adapter.on("verification:request", (payload: Record<string, unknown>) => {
                    this._verification.storeAndBroadcast(payload);
                });
            }
            if (!adapter.listenerCount("verification:clear")) {
                adapter.on("verification:clear", (payload: Record<string, unknown>) => {
                    this._verification.clearAndBroadcast(payload);
                });
            }
        }

        if (fs.existsSync(client)) {
            const managementIndex = renderManagementIndexHtml(
                fs.readFileSync(path.join(client, "index.html"), "utf8"),
                this.config.path,
            );
            this.use(async (ctx, next) => {
                if (ctx.method !== "HEAD" && ctx.method !== "GET") return next();
                if (!isManagementSpaPath(ctx.path)) return next();
                ctx.type = "html";
                applyManagementDocumentSecurityHeaders(ctx);
                ctx.set("Cache-Control", "no-store");
                ctx.body = managementIndex;
            });
            this.use(koaStatic(client, { index: false }));
        }

        await super.start();
    }

    async reload(config: BaseApp.Config) {
        validateRuntimeConfig(config as Record<string, unknown>);
        const currentPlugins = getRuntimePluginSelection(
            this.config as unknown as Record<string, unknown>,
        );
        const nextPlugins = getRuntimePluginSelection(config as Record<string, unknown>);
        if (JSON.stringify(currentPlugins) !== JSON.stringify(nextPlugins)) {
            throw new ConfigRestartRequiredError(["plugins"]);
        }
        const previous = this.config;
        await super.reload(config);
        if (managementCredentialsChanged(previous, this.config)) {
            this.tokenManager.revokeAll();
            setImmediate(() => {
                for (const client of this.ws.clients) client.close(1008, "Credentials changed");
                for (const client of this.terminalClients) {
                    client.close(1008, "Credentials changed");
                }
                const streamFailures = this.disconnectManagementStreams();
                if (streamFailures.length) {
                    this.logger.error("管理凭据轮换后关闭 SSE 连接失败", {
                        failures: streamFailures.map(error =>
                            error instanceof Error ? error.message : String(error),
                        ),
                    });
                }
            });
        }
    }

    private disconnectManagementStreams(): unknown[] {
        return [
            ...this._logCache.disconnectClients(),
            ...this._verification.disconnectClients(),
            ...this._messageDebug.disconnectClients(),
        ];
    }
}

export namespace App {
    export interface Config extends BaseApp.Config {
        plugins?: RuntimePluginSelection;
    }
    export const defaultConfig: Config = {
        ...BaseApp.defaultConfig,
    };
    export function registerGeneral<K extends keyof Protocol.Configs>(
        key: K,
        config: Protocol.Config<Protocol.Configs[K]>,
    ) {
        defaultConfig.general = {
            ...defaultConfig.general,
            [key]: config,
        };
    }
    export async function loadAdapterFactory(
        platform: string,
        maybeNames = pluginCandidates("adapter", platform),
    ): Promise<boolean> {
        return loadPlugin("adapter", platform, maybeNames, require);
    }
    export async function loadProtocolFactory(
        name: string,
        maybeNames = pluginCandidates("protocol", name),
    ): Promise<boolean> {
        return loadPlugin("protocol", name, maybeNames, require);
    }
}

export function createOnebots(config: BaseApp.Config | string = "config.yaml") {
    const isStartWithConfigFile = typeof config === "string";
    if (isStartWithConfigFile) {
        config = path.resolve(process.cwd(), config as string);
        BaseApp.configDir = path.dirname(config);
        BaseApp.configFileName = path.basename(config);
    }
    if (!existsSync(BaseApp.configDir)) mkdirSync(BaseApp.configDir);
    const dataDirectory = ensureRuntimeDataDirectory(BaseApp.dataDir);
    if (dataDirectory.created) {
        writeCliOutput(`[onebots] 已创建并验证数据存储目录: ${BaseApp.dataDir}`);
    }
    if (!existsSync(BaseApp.configPath) && isStartWithConfigFile) {
        writeConfigFileAtomic(
            BaseApp.configPath,
            readFileSync(path.resolve(import.meta.dirname, "./config.sample.yaml"), "utf8"),
        );
        writeCliOutput(`[onebots] 已创建默认配置文件: ${BaseApp.configPath}`);
    }
    if (!isStartWithConfigFile) {
        writeConfigFileAtomic(BaseApp.configPath, yaml.dump(config));
        writeCliOutput(`[onebots] 已自动保存配置到: ${BaseApp.configPath}`);
    }
    config = parseRuntimeConfig(readFileSync(BaseApp.configPath, "utf8")) as BaseApp.Config;
    const managementCredentials = ensureManagementCredentials(config as Record<string, unknown>);
    config = managementCredentials.config as BaseApp.Config;
    if (managementCredentials.generated) {
        writeConfigFileAtomic(BaseApp.configPath, yaml.dump(config), {
            backup: true,
            mode: 0o600,
        });
        writeCliError("[onebots] 已生成管理端鉴权码并写入配置文件的 access_token 字段。");
        writeCliError("[onebots] 鉴权码不会写入日志；首次登录时请从以下文件读取：");
        writeCliError(`  配置文件: ${BaseApp.configPath}`);
    } else if (managementCredentials.source === "environment") {
        writeCliOutput("[onebots] 管理端使用 ONEBOTS_ACCESS_TOKEN 环境变量鉴权。");
    }
    configure({
        appenders: {
            out: {
                type: "stdout",
                layout: { type: "colored" },
            },
            files: {
                type: "file",
                maxLogSize: 1024 * 1024 * 50,
                filename: BaseApp.logFile,
            },
        },
        categories: {
            default: {
                appenders: ["out", "files"],
                level: (config as BaseApp.Config).log_level || "info",
            },
        },
        disableClustering: true,
    });
    return new App(config as BaseApp.Config);
}

export function defineConfig(config: BaseApp.Config) {
    return config;
}
