import {
    BaseApp,
    yaml,
    ProtocolRegistry,
    configure,
    Protocol,
    readLine,
    initTokenManager,
} from "@onebots/core";
import { getAppConfigSchema } from "./config-schema.js";
import { registerAuthRoutes } from "./routes/auth.js";
import { registerConfigRoutes } from "./routes/config.js";
import { registerAdapterRoutes } from "./routes/adapter-api.js";
import { registerVerificationRoutes } from "./routes/verification.js";
import { registerTerminalRoutes } from "./routes/terminal.js";
import { registerPublicStaticRoutes } from "./routes/public-static.js";
import * as path from "path";
import * as fs from "fs";
import { createRequire } from "module";
import { pathToFileURL } from "url";
import koaStatic from "koa-static";
import { copyFileSync, existsSync, writeFileSync, mkdirSync, readFileSync } from "fs";
import type { WsServer, Dict } from "@onebots/core";
import { randomBytes } from "node:crypto";
import { execFileSync } from "node:child_process";

const require = createRequire(pathToFileURL(path.join(process.cwd(), 'node_modules')));

// 多目录依次查找 @onebots/web/dist，找到即用（Docker/HF 从 development 启动时 cwd 下无 @onebots/web）
const client = (() => {
    const rel = ['..', 'node_modules', '@onebots', 'web', 'dist'];
    const candidates = [
        path.join(import.meta.dirname, ...rel),
        path.join(process.cwd(), 'node_modules', '@onebots', 'web', 'dist'),
        path.join(import.meta.dirname, '..', '..', '..', 'packages', 'web', 'dist'),
    ].map(p => path.resolve(p));
    for (const dir of candidates) {
        console.log('[onebots] 查找 Web 前端目录:', dir);
        if (existsSync(dir)) {
            console.log('[onebots] 使用 Web 前端目录:', dir);
            return dir;
        }
    }
    console.log('[onebots] 未找到 @onebots/web/dist，管理端页面将不可用');
    return '';
})();

/**
 * 当前实例是否使用了自动生成的管理端账号（用于登录成功后提示用户修改密码）。
 * 由 createOnebots 设置，然后复制到 App 实例的 credentialsWereAutoGenerated 属性中。
 * 此模块级变量保持仅供 createOnebots 使用；路由模块访问 app.credentialsWereAutoGenerated。
 */
let _credentialsWereAutoGenerated = false;

export class App extends BaseApp {
    public ws: WsServer;
    public logCacheFile: string;
    private logWriteStream: fs.WriteStream;
    public logClients: Set<any> = new Set();
    public verificationClients: Set<any> = new Set();
    /** 待处理验证请求（Web 离线时也可稍后拉取完成），key: platform:account_id */
    public pendingVerifications: Map<string, { payload: Record<string, unknown>; createdAt: number }> = new Map();
    private static readonly VERIFICATION_TTL_MS = 30 * 60 * 1000; // 30 分钟过期
    private static readonly MAX_PENDING_VERIFICATIONS = 20; // 最多保留条数，避免堆积过多
    public ptyTerminal: any = null;
    public terminalClients: Set<any> = new Set();
    public tokenManager = initTokenManager({
        defaultExpiration: 12 * 60 * 60 * 1000,
        refreshExpiration: 7 * 24 * 60 * 60 * 1000,
    });
    /** 当前实例是否使用了自动生成的管理端账号 */
    public credentialsWereAutoGenerated: boolean;

    constructor(config: App.Config) {
        super(config);

        // 1. 初始化日志缓存文件
        this.logCacheFile = path.join(process.cwd(), 'data', 'terminal-logs.txt');
        this.initLogCache();

        // 2. 从模块级变量复制自动生成凭据状态
        this.credentialsWereAutoGenerated = _credentialsWereAutoGenerated;

        // 3. 初始化 WebSocket
        this.ws = this.router.ws("/");

        // 3. 监听进程退出，清空缓存
        process.on('exit', () => {
            this.cleanupLogCache();
        });
        process.on('SIGINT', () => {
            this.cleanupLogCache();
            process.exit();
        });
        process.on('SIGTERM', () => {
            this.cleanupLogCache();
            process.exit();
        });
    }

    private initLogCache() {
        // 确保 data 目录存在
        const dataDir = path.dirname(this.logCacheFile);
        if (!existsSync(dataDir)) {
            mkdirSync(dataDir, { recursive: true });
        }

        // 清空旧的日志缓存文件（重启时清空）
        writeFileSync(this.logCacheFile, '', 'utf-8');

        // 创建写入流
        this.logWriteStream = fs.createWriteStream(this.logCacheFile, { flags: 'a', encoding: 'utf-8' });

        // 拦截 stdout 和 stderr 的 write 方法
        const originalStdoutWrite = process.stdout.write.bind(process.stdout);
        const originalStderrWrite = process.stderr.write.bind(process.stderr);

        process.stdout.write = ((chunk: any, encoding?: any, callback?: any) => {
            const message = chunk.toString();
            try {
                // 缓存到文件
                this.cacheLog(message);
                // 广播到所有 SSE 客户端
                this.broadcastLog(message);
            } catch (e) {
                // Use the original write to avoid re-entering the interceptor
                originalStderrWrite(`[onebots] Log interceptor error: ${e}\n`);
            }
            // 继续正常输出
            return originalStdoutWrite(chunk, encoding, callback);
        }) as any;

        process.stderr.write = ((chunk: any, encoding?: any, callback?: any) => {
            const message = chunk.toString();
            try {
                // 缓存到文件
                this.cacheLog(message);
                // 广播到所有 SSE 客户端
                this.broadcastLog(message);
            } catch (e) {
                // Use the original write to avoid re-entering the interceptor
                originalStderrWrite(`[onebots] Log interceptor error: ${e}\n`);
            }
            // 继续正常输出
            return originalStderrWrite(chunk, encoding, callback);
        }) as any;
    }

    private broadcastLog(message: string) {
        if (this.logClients.size > 0 && message) {
            // 将 \n 替换为 \r\n 以适配 xterm.js
            const terminalMessage = message.replace(/\n/g, '\r\n');
            const data = `data: ${JSON.stringify({ message: terminalMessage })}\n\n`;

            this.logClients.forEach(client => {
                try {
                    client.write(data);
                } catch (e) {
                    this.logClients.delete(client);
                }
            });
        }
    }

    /** 将验证请求推送给所有已连接的 verification SSE 客户端 */
    private broadcastVerification(payload: Record<string, unknown>) {
        const data = `data: ${JSON.stringify(payload)}\n\n`;
        this.verificationClients.forEach(client => {
            try {
                client.write(data);
            } catch (e) {
                this.verificationClients.delete(client);
            }
        });
    }

    /** 存储待处理验证并广播（Web 离线时也会持久化，用户稍后打开页面可拉取完成）；超出上限时剔除最旧的；key 含 type 以便同一账号同时存在 device 与 sms */
    private storeAndBroadcastVerification(payload: Record<string, unknown>) {
        const platform = String(payload.platform ?? '');
        const account_id = String(payload.account_id ?? '');
        const type = String(payload.type ?? '');
        if (!platform || !account_id) return;
        const key = `${platform}:${account_id}:${type}`;
        const createdAt = Date.now();
        if (this.pendingVerifications.size >= App.MAX_PENDING_VERIFICATIONS && !this.pendingVerifications.has(key)) {
            let oldestKey: string | null = null;
            let oldestTime = Infinity;
            for (const [k, { createdAt: t }] of this.pendingVerifications) {
                if (t < oldestTime) {
                    oldestTime = t;
                    oldestKey = k;
                }
            }
            if (oldestKey != null) this.pendingVerifications.delete(oldestKey);
        }
        this.pendingVerifications.set(key, { payload, createdAt });
        this.broadcastVerification(payload);
    }

    /** 返回未过期的待处理验证列表（用于 GET /api/verification/pending） */
    public getPendingVerificationList(): Record<string, unknown>[] {
        const now = Date.now();
        const list: Record<string, unknown>[] = [];
        for (const [key, { payload, createdAt }] of this.pendingVerifications) {
            if (now - createdAt <= App.VERIFICATION_TTL_MS) {
                list.push(payload);
            } else {
                this.pendingVerifications.delete(key);
            }
        }
        return list;
    }

    /** 订阅适配器的 verification:request，用于推送到 Web 并持久化待处理列表 */
    protected onAdapterCreated(adapter: import("@onebots/core").Adapter): void {
        adapter.on('verification:request', (payload: Record<string, unknown>) => {
            this.storeAndBroadcastVerification(payload);
        });
    }

    private cleanupLogCache() {
        // 关闭写入流
        if (this.logWriteStream) {
            this.logWriteStream.end();
        }
        // 清空缓存文件
        try {
            if (existsSync(this.logCacheFile)) {
                writeFileSync(this.logCacheFile, '', 'utf-8');
            }
        } catch (e) {
            this.logger.error('清空日志缓存失败:', e);
        }
    }


    private cacheLog(message: string) {
        if (this.logWriteStream && message) {
            this.logWriteStream.write(message);
        }
    }

    /** 将当前配置与整个 data 目录备份到 HF Space 仓库（需 HF_TOKEN、HF_REPO_ID） */
    public async backupDataToHf(configContent: string): Promise<{ success: boolean; message?: string }> {
        const hfToken = process.env.HF_TOKEN;
        const hfRepoId = process.env.HF_REPO_ID;
        if (!hfToken || !hfRepoId || !/^[a-zA-Z0-9_-]+\/[a-zA-Z0-9_.-]+$/.test(hfRepoId)) {
            return { success: false, message: "未配置 HF_TOKEN 或 HF_REPO_ID" };
        }
        const [namespace, repo] = hfRepoId.split("/");
        const files: { path: string; content: string; encoding?: "utf-8" | "base64" }[] = [
            { path: "config_backup.yaml", content: configContent },
        ];
        try {
            const dataDir = BaseApp.configDir;
            if (existsSync(dataDir)) {
                const tarBuf = execFileSync("tar", ["-czf", "-", "-C", dataDir, "."], {
                    encoding: "buffer",
                    maxBuffer: 15 * 1024 * 1024,
                }) as Buffer;
                if (tarBuf.length > 0) {
                    files.push({ path: "data_backup.tar.gz", content: tarBuf.toString("base64"), encoding: "base64" });
                }
            }
            const res = await fetch(`https://huggingface.co/api/spaces/${namespace}/${repo}/commit/main`, {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "Authorization": `Bearer ${hfToken}`,
                },
                body: JSON.stringify({
                    summary: "onebots data backup",
                    files,
                }),
            });
            if (!res.ok) {
                const text = await res.text();
                this.logger?.warn?.("备份到 HF 仓库失败:", res.status, text);
                return { success: false, message: `备份失败: ${res.status} ${text}` };
            }
            return { success: true };
        } catch (e) {
            this.logger?.warn?.("备份到 HF 仓库异常:", e);
            return { success: false, message: (e as Error).message };
        }
    }

    /**
     * 站点静态文件变更后：若配置了 HF_TOKEN + HF_REPO_ID（如 Hugging Face Space），则再次打包整个配置目录并提交到仓库，持久化 static 等文件
     */
    public async backupDataDirToHfAfterStaticChange(): Promise<
        { attempted: false } | { attempted: true; success: boolean; message?: string }
    > {
        const hfToken = process.env.HF_TOKEN;
        const hfRepoId = process.env.HF_REPO_ID;
        if (!hfToken || !hfRepoId || !/^[a-zA-Z0-9_-]+\/[a-zA-Z0-9_.-]+$/.test(hfRepoId)) {
            return { attempted: false };
        }
        try {
            const configContent = readFileSync(BaseApp.configPath, 'utf8');
            const r = await this.backupDataToHf(configContent);
            if (!r.success && r.message) {
                this.logger?.warn?.(`Hugging Face 备份（站点静态变更后）: ${r.message}`);
            }
            return { attempted: true, success: r.success, message: r.message };
        } catch (e) {
            const msg = (e as Error).message;
            this.logger?.warn?.('Hugging Face 备份（站点静态变更后）异常:', e);
            return { attempted: true, success: false, message: msg };
        }
    }

    async start() {
        // Route module registrations — each registers a group of routes on the router
        registerAuthRoutes(this, this.router);
        registerConfigRoutes(this, this.router);
        registerAdapterRoutes(this, this.router);
        registerVerificationRoutes(this, this.router);
        registerTerminalRoutes(this, this.router);
        registerPublicStaticRoutes(this, this.router);

        // WebSocket 日志监听（确保日志文件存在再 watch，避免 ENOENT）
        if (!existsSync(BaseApp.logFile)) {
            const dir = path.dirname(BaseApp.logFile);
            if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
            writeFileSync(BaseApp.logFile, "", "utf8");
        }
        const fileListener = (eventType: string) => {
            if (eventType === "change")
                this.ws.clients.forEach(async client => {
                    client.send(
                        JSON.stringify({
                            event: "system.log",
                            data: await readLine(1, BaseApp.logFile),
                        }),
                    );
                });
        };
        const logWatcher = fs.watch(BaseApp.logFile, fileListener);
        this.once("close", () => {
            logWatcher.close();
        });
        process.once("disconnect", () => {
            logWatcher.close();
        });

        // WebSocket 连接处理
        this.ws.on("connection", async client => {
            client.send(
                JSON.stringify({
                    event: "system.sync",
                        data: {
                        config: fs.readFileSync(BaseApp.configPath, "utf8"),
                        adapters: [...this.adapters.values()].map(adapter => {
                            return adapter.info;
                        }),
                        protocol: ProtocolRegistry.getAllMetadata(),
                        app: this.info,
                            schema: getAppConfigSchema(),
                        logs: fs.existsSync(BaseApp.logFile) ? await readLine(100, BaseApp.logFile) : "",
                    },
                }),
            );
            client.on("message", async raw => {
                let payload: Dict = {};
                try {
                    payload = JSON.parse(raw.toString());
                } catch {
                    // 无效的消息数据，忽略该条消息
                    return;
                }
                switch (payload.action) {
                    case "system.input":
                        // 将流的模式切换到"流动模式"
                        process.stdin.resume();

                        // 使用以下函数来模拟输入数据
                        function simulateInput(data: Buffer) {
                            process.nextTick(() => {
                                process.stdin.emit("data", data);
                            });
                        }

                        simulateInput(Buffer.from(payload.data + "\n", "utf8"));
                        // 模拟结束
                        process.nextTick(() => {
                            process.stdin.emit("end");
                        });
                        return true;
                    case "system.saveConfig":
                        fs.writeFileSync(BaseApp.configPath, payload.data, "utf8");
                        this.credentialsWereAutoGenerated = false;
                        return;
                    case "system.reload":
                        const config = yaml.load(fs.readFileSync(BaseApp.configPath, "utf8"));
                        return this.reload(config as App.Config);
                    case "bot.start": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOnline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                    case "bot.stop": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOffline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                }
            });
        });

        // 订阅已有适配器的验证事件（init 时创建的适配器已通过 onAdapterCreated 订阅，此处为兜底）
        for (const [, adapter] of this.adapters) {
            if (!adapter.listenerCount('verification:request')) {
                adapter.on('verification:request', (payload: Record<string, unknown>) => {
                    this.storeAndBroadcastVerification(payload);
                });
            }
        }

        // 静态文件服务
        if (fs.existsSync(client)) {
            this.use(koaStatic(client));
            // SPA fallback：仅对已知前端路由返回 index.html；协议与 adapter 提供的路径（如 /platform/accountId/...、.../webhook）一律 next，由 router 处理
            const spaPathRegex = /^\/(login|bots|config|system|terminal|logs)(\/.*)?$/;
            this.use(async (ctx, next) => {
                if (ctx.method !== 'HEAD' && ctx.method !== 'GET') return next();
                const p = ctx.path;
                const isSpaRoute = p === '/' || spaPathRegex.test(p);
                if (!isSpaRoute) return next();
                ctx.type = 'html';
                ctx.body = fs.readFileSync(path.join(client, 'index.html'));
            });
        }

        // 调用父类的 start
        await super.start();
    }
}
export namespace App {
    export interface Config extends BaseApp.Config { }
    export const defaultConfig: Config = {
        ...BaseApp.defaultConfig,
    }
    export function registerGeneral<K extends keyof Protocol.Configs>(
        key: K,
        config: Protocol.Config<Protocol.Configs[K]>,
    ) {
        defaultConfig.general = {
            ...defaultConfig.general,
            [key]: config
        }
    }
    async function safeImport(name: string) {
        try {
            return await import(name);
        } catch {
            // 模块不存在，返回 undefined 表示加载失败
        }
    }
    export async function loadAdapterFactory(platform: string,maybeNames=[
        `@onebots/adapter-${platform}`,
        `onebots-adapter-${platform}`,
        platform
    ]):Promise<boolean>{
        if(!maybeNames.length) return false;
        const modName=maybeNames.shift()!;
        try{
            require(modName);
            return true;
        }catch (e) {
            console.warn(`[onebots] 加载适配器 ${modName} 失败: ${e}`);
            return loadAdapterFactory(platform,maybeNames);
        }
    }
    export async function loadProtocolFactory(name: string, maybeNames=[
        `@onebots/protocol-${name}`,
        `onebots-protocol-${name}`,
        `${name}`
        ]):Promise<boolean>{
        if(!maybeNames.length) return false;
        const modName=maybeNames.shift()!;
        try{
            require(modName);
            return true;
        }catch (e) {
            console.warn(`[onebots] 加载协议 ${modName} 失败: ${e}`);
            return loadProtocolFactory(name,maybeNames);
        }
    }
}
export function createOnebots(
    config: BaseApp.Config | string = "config.yaml",
    // cp: ChildProcess | null = null,
) {
    const isStartWithConfigFile = typeof config === "string";
    if (isStartWithConfigFile) {
        config = path.resolve(process.cwd(), config as string);
        BaseApp.configDir = path.dirname(config);
    }
    if (!existsSync(BaseApp.configDir)) mkdirSync(BaseApp.configDir);
    if (!existsSync(BaseApp.configPath) && isStartWithConfigFile) {
        copyFileSync(path.resolve(import.meta.dirname, "./config.sample.yaml"), BaseApp.configPath);
        console.log("[onebots] 已创建默认配置文件:", BaseApp.configPath);
    }
    if (!isStartWithConfigFile) {
        writeFileSync(BaseApp.configPath, yaml.dump(config));
        console.log("[onebots] 已自动保存配置到:", BaseApp.configPath);
    }
    if (!existsSync(BaseApp.dataDir)) {
        mkdirSync(BaseApp.dataDir);
        console.log("[onebots] 已创建数据存储目录:", BaseApp.dataDir);
    }
    config = yaml.load(readFileSync(BaseApp.configPath, "utf8")) as BaseApp.Config;
    const hasAccessToken = !!(config as { access_token?: string }).access_token?.trim();
    if ((!config.username || !config.password) && !hasAccessToken) {
        const generatedUser = "onebots_" + randomBytes(4).toString("hex");
        const generatedPass = randomBytes(16).toString("hex");
        (config as Record<string, unknown>).username = generatedUser;
        (config as Record<string, unknown>).password = generatedPass;
        writeFileSync(BaseApp.configPath, yaml.dump(config));
        _credentialsWereAutoGenerated = true;
        console.log("[onebots] 已自动生成管理端账号并写入配置文件，请尽快在 Web 端修改密码：");
        console.log("  用户名:", generatedUser);
        console.log("  密码:", generatedPass);
        console.log("  配置文件:", BaseApp.configPath);
    }
    configure({
        appenders: {
            out: {
                type: "stdout",
                layout: { type: "colored" },
            },
            files: {
                type: "file",
                maxLogSize: 1024 * 1024 * 50,
                filename: BaseApp.logFile,
            },
        },
        categories: {
            default: {
                appenders: ["out", "files"],
                level: (config as BaseApp.Config).log_level || "info",
            },
        },
        disableClustering: true,
    });
    // if (cp) process.on("disconnect", () => cp.kill());
    return new App(config as BaseApp.Config);
}

export function defineConfig(config: BaseApp.Config) {
    return config;
}