import {
    BaseApp,
    yaml,
    ProtocolRegistry,
    configure,
    Protocol,
    readLine,
    initTokenManager,
    writeConfigFileAtomic,
} from "@onebots/core";
import { getAppConfigSchema } from "./config-schema.js";
import { registerAuthRoutes } from "./routes/auth.js";
import { registerConfigRoutes } from "./routes/config.js";
import { registerAdapterRoutes } from "./routes/adapter-api.js";
import { registerVerificationRoutes } from "./routes/verification.js";
import { registerTerminalRoutes } from "./routes/terminal.js";
import { registerPublicStaticRoutes } from "./routes/public-static.js";
import { registerMessageDebugRoutes } from "./routes/message-debug.js";
import { LogCacheManager } from "./log-cache.js";
import { VerificationManager } from "./verification-manager.js";
import { HfBackupService } from "./hf-backup.js";
import { MessageDebugManager } from "./message-debug.js";
import * as path from "path";
import * as fs from "fs";
import { createRequire } from "module";
import { pathToFileURL } from "url";
import koaStatic from "koa-static";
import { existsSync, writeFileSync, mkdirSync, readFileSync } from "fs";
import type { WsServer, Dict } from "@onebots/core";
import { loadPlugin, pluginCandidates } from "./plugin-loader.js";
import { writeCliError, writeCliOutput } from "./cli-output.js";
import { validateRuntimeConfig } from "./runtime-config-validator.js";
import { getAdapterInfo } from "./adapter-info.js";
import { handleManagementConfigSocketAction } from "./management-config-socket.js";
import {
    authorizeManagementUpgrade,
    extractManagementToken,
    managementCredentialsChanged,
    validateManagementToken,
} from "./management-auth.js";
import type { WebSocket } from "ws";
import { ensureManagementCredentials } from "./management-credentials.js";

const require = createRequire(pathToFileURL(path.join(process.cwd(), "node_modules")));

const client = (() => {
    const rel = ["..", "node_modules", "@onebots", "web", "dist"];
    const candidates = [
        path.join(import.meta.dirname, ...rel),
        path.join(process.cwd(), "node_modules", "@onebots", "web", "dist"),
        path.join(import.meta.dirname, "..", "..", "..", "packages", "web", "dist"),
    ].map(p => path.resolve(p));
    for (const dir of candidates) {
        if (existsSync(dir)) {
            return dir;
        }
    }
    return "";
})();

export class App extends BaseApp {
    public ws: WsServer;
    private _logCache: LogCacheManager;
    private _verification: VerificationManager;
    private _hfBackup: HfBackupService;
    private _messageDebug: MessageDebugManager;
    public ptyTerminal: ReturnType<typeof import("@karinjs/node-pty").spawn> | null = null;
    public terminalClients: Set<WebSocket> = new Set();

    private static readonly DEFAULT_TOKEN_EXPIRATION_MS = 12 * 60 * 60 * 1000;
    private static readonly REFRESH_TOKEN_EXPIRATION_MS = 7 * 24 * 60 * 60 * 1000;
    public tokenManager = initTokenManager({
        defaultExpiration: App.DEFAULT_TOKEN_EXPIRATION_MS,
        refreshExpiration: App.REFRESH_TOKEN_EXPIRATION_MS,
    });
    public credentialsWereAutoGenerated = false;

    // 代理属性：路由文件通过这些属性访问管理器内部状态
    get logClients() {
        return this._logCache.clients;
    }
    get logCacheFile() {
        return this._logCache.cacheFile;
    }
    get verificationClients() {
        return this._verification.clients;
    }
    get pendingVerifications() {
        return this._verification.pending;
    }
    get messageDebug() {
        return this._messageDebug;
    }

    constructor(config: App.Config) {
        super(config);

        if (client) this.logger.info(`使用 Web 前端目录: ${client}`);
        else this.logger.warn("未找到 @onebots/web/dist，管理端页面将不可用");

        this._logCache = new LogCacheManager(path.join(process.cwd(), "data", "terminal-logs.txt"));
        this._logCache.interceptStdio();
        this._verification = new VerificationManager();
        this._hfBackup = new HfBackupService(this.logger);
        this._messageDebug = new MessageDebugManager();
        this.ws = this.router.ws("/", {
            authorize: request => authorizeManagementUpgrade(this, request),
        });

        process.on("exit", () => this._logCache.cleanup());
        this.once("close", () => this._logCache.cleanup());
    }

    getPendingVerificationList(): Record<string, unknown>[] {
        return this._verification.getPendingList();
    }

    async backupDataToHf(configContent: string) {
        return this._hfBackup.backupData(configContent);
    }

    async backupDataDirToHfAfterStaticChange() {
        return this._hfBackup.backupAfterStaticChange();
    }

    protected onAdapterCreated(adapter: import("@onebots/core").Adapter): void {
        adapter.on("verification:request", (payload: Record<string, unknown>) => {
            this._verification.storeAndBroadcast(payload);
        });
        adapter.on("verification:clear", (payload: Record<string, unknown>) => {
            this._verification.clearAndBroadcast(payload);
        });
        adapter.on(
            "message:dispatch",
            (payload: { platform: string; account_id: string; event: unknown }) => {
                this._messageDebug.recordInbound(
                    payload.platform,
                    payload.account_id,
                    payload.event,
                );
            },
        );
        adapter.on(
            "message:protocol-dispatch",
            (payload: {
                platform: string;
                account_id: string;
                protocol: string;
                version: string;
                data: unknown;
            }) => {
                this._messageDebug.recordOutbound(
                    payload.platform,
                    payload.account_id,
                    payload.protocol,
                    payload.version,
                    payload.data,
                );
            },
        );
    }

    /** 为 REST 与 WebSocket 提供同一份带注册元数据的适配器摘要。 */
    get adapterInfos() {
        return [...this.adapters.values()].map(getAdapterInfo);
    }

    async start() {
        this.assertCanStart();
        if (this.isStarted) return;
        validateRuntimeConfig(this.config as Record<string, unknown>);
        registerAuthRoutes(this, this.router);
        registerConfigRoutes(this, this.router);
        registerAdapterRoutes(this, this.router);
        registerVerificationRoutes(this, this.router);
        registerTerminalRoutes(this, this.router);
        registerPublicStaticRoutes(this, this.router);
        registerMessageDebugRoutes(this, this.router);

        if (!existsSync(BaseApp.logFile)) {
            const dir = path.dirname(BaseApp.logFile);
            if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
            writeFileSync(BaseApp.logFile, "", "utf8");
        }
        const fileListener = (eventType: string) => {
            if (eventType === "change")
                this.ws.clients.forEach(async client => {
                    client.send(
                        JSON.stringify({
                            event: "system.log",
                            data: await readLine(1, BaseApp.logFile),
                        }),
                    );
                });
        };
        const logWatcher = fs.watch(BaseApp.logFile, fileListener);
        this.once("close", () => logWatcher.close());
        process.once("disconnect", () => logWatcher.close());

        this.ws.on("connection", async (client, request) => {
            const managementToken = extractManagementToken(request);
            client.send(
                JSON.stringify({
                    event: "system.sync",
                    data: {
                        config: fs.readFileSync(BaseApp.configPath, "utf8"),
                        adapters: this.adapterInfos,
                        protocol: ProtocolRegistry.getAllMetadata(),
                        app: this.info,
                        schema: getAppConfigSchema(),
                        logs: fs.existsSync(BaseApp.logFile)
                            ? await readLine(100, BaseApp.logFile)
                            : "",
                    },
                }),
            );
            client.on("message", async raw => {
                if (!validateManagementToken(this, managementToken).valid) {
                    client.close(1008, "Unauthorized");
                    return;
                }
                let payload: Dict = {};
                try {
                    payload = JSON.parse(raw.toString());
                } catch {
                    return;
                }
                const configResponse = await handleManagementConfigSocketAction(this, payload);
                if (configResponse) {
                    try {
                        return client.send(JSON.stringify(configResponse));
                    } catch (error) {
                        this.logger.error("发送管理端配置回执失败", { error });
                        return;
                    }
                }
                switch (payload.action) {
                    case "system.input":
                        process.stdin.resume();
                        process.nextTick(() =>
                            process.stdin.emit("data", Buffer.from(payload.data + "\n", "utf8")),
                        );
                        process.nextTick(() => process.stdin.emit("end"));
                        return true;
                    case "bot.start": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOnline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                    case "bot.stop": {
                        const { platform, uin } = JSON.parse(payload.data);
                        await this.adapters.get(platform)?.setOffline(uin);
                        return client.send(
                            JSON.stringify({
                                event: "bot.change",
                                data: this.adapters.get(platform).getAccount(uin).info,
                            }),
                        );
                    }
                }
            });
        });

        for (const [, adapter] of this.adapters) {
            if (!adapter.listenerCount("verification:request")) {
                adapter.on("verification:request", (payload: Record<string, unknown>) => {
                    this._verification.storeAndBroadcast(payload);
                });
            }
            if (!adapter.listenerCount("verification:clear")) {
                adapter.on("verification:clear", (payload: Record<string, unknown>) => {
                    this._verification.clearAndBroadcast(payload);
                });
            }
        }

        if (fs.existsSync(client)) {
            this.use(koaStatic(client));
            const spaPathRegex = /^\/(login|bots|config|system|terminal|logs)(\/.*)?$/;
            this.use(async (ctx, next) => {
                if (ctx.method !== "HEAD" && ctx.method !== "GET") return next();
                const p = ctx.path;
                if (p !== "/" && !spaPathRegex.test(p)) return next();
                ctx.type = "html";
                ctx.body = fs.readFileSync(path.join(client, "index.html"));
            });
        }

        await super.start();
    }

    async reload(config: BaseApp.Config) {
        validateRuntimeConfig(config as Record<string, unknown>);
        const previous = this.config;
        await super.reload(config);
        if (managementCredentialsChanged(previous, this.config)) {
            this.tokenManager.revokeAll();
            setImmediate(() => {
                for (const client of this.ws.clients) client.close(1008, "Credentials changed");
                for (const client of this.terminalClients) {
                    client.close(1008, "Credentials changed");
                }
            });
        }
    }
}

export namespace App {
    export interface Config extends BaseApp.Config {}
    export const defaultConfig: Config = {
        ...BaseApp.defaultConfig,
    };
    export function registerGeneral<K extends keyof Protocol.Configs>(
        key: K,
        config: Protocol.Config<Protocol.Configs[K]>,
    ) {
        defaultConfig.general = {
            ...defaultConfig.general,
            [key]: config,
        };
    }
    export async function loadAdapterFactory(
        platform: string,
        maybeNames = pluginCandidates("adapter", platform),
    ): Promise<boolean> {
        return loadPlugin("adapter", platform, maybeNames, require);
    }
    export async function loadProtocolFactory(
        name: string,
        maybeNames = pluginCandidates("protocol", name),
    ): Promise<boolean> {
        return loadPlugin("protocol", name, maybeNames, require);
    }
}

export function createOnebots(config: BaseApp.Config | string = "config.yaml") {
    const isStartWithConfigFile = typeof config === "string";
    if (isStartWithConfigFile) {
        config = path.resolve(process.cwd(), config as string);
        BaseApp.configDir = path.dirname(config);
    }
    if (!existsSync(BaseApp.configDir)) mkdirSync(BaseApp.configDir);
    if (!existsSync(BaseApp.configPath) && isStartWithConfigFile) {
        writeConfigFileAtomic(
            BaseApp.configPath,
            readFileSync(path.resolve(import.meta.dirname, "./config.sample.yaml"), "utf8"),
        );
        writeCliOutput(`[onebots] 已创建默认配置文件: ${BaseApp.configPath}`);
    }
    if (!isStartWithConfigFile) {
        writeConfigFileAtomic(BaseApp.configPath, yaml.dump(config));
        writeCliOutput(`[onebots] 已自动保存配置到: ${BaseApp.configPath}`);
    }
    if (!existsSync(BaseApp.dataDir)) {
        mkdirSync(BaseApp.dataDir);
        writeCliOutput(`[onebots] 已创建数据存储目录: ${BaseApp.dataDir}`);
    }
    config = yaml.load(readFileSync(BaseApp.configPath, "utf8")) as BaseApp.Config;
    const managementCredentials = ensureManagementCredentials(config as Record<string, unknown>);
    config = managementCredentials.config as BaseApp.Config;
    if (managementCredentials.generated) {
        writeConfigFileAtomic(BaseApp.configPath, yaml.dump(config), { backup: true });
        writeCliError("[onebots] 已生成管理端鉴权码并写入配置文件的 access_token 字段。");
        writeCliError("[onebots] 鉴权码不会写入日志；首次登录时请从以下文件读取：");
        writeCliError(`  配置文件: ${BaseApp.configPath}`);
    } else if (managementCredentials.source === "environment") {
        writeCliOutput("[onebots] 管理端使用 ONEBOTS_ACCESS_TOKEN 环境变量鉴权。");
    }
    configure({
        appenders: {
            out: {
                type: "stdout",
                layout: { type: "colored" },
            },
            files: {
                type: "file",
                maxLogSize: 1024 * 1024 * 50,
                filename: BaseApp.logFile,
            },
        },
        categories: {
            default: {
                appenders: ["out", "files"],
                level: (config as BaseApp.Config).log_level || "info",
            },
        },
        disableClustering: true,
    });
    return new App(config as BaseApp.Config);
}

export function defineConfig(config: BaseApp.Config) {
    return config;
}
