import type { FrameworkProfile } from "./framework-integration-types.js";
import { deepFreeze } from "./framework-integration-utils.js";

export const DISTRIBUTION_FRAMEWORK_PROFILES: Readonly<Record<string, FrameworkProfile>> =
    deepFreeze({
        yunzai: {
            id: "yunzai",
            displayName: "云崽 / TRSS-Yunzai",
            kind: "distribution",
            packageName: null,
            protocol: "onebot.v11",
            transport: "reverse-websocket",
            verification: "documented",
            distributionAudit: {
                sourceRevision: "2d1652ac899e8f4338b5310171319e6894b2499c",
                auditedAt: "2026-09-02",
                requiredActions: [
                    "_get_group_notice",
                    "_send_group_notice",
                    "_set_model_show",
                    "create_group_file_folder",
                    "delete_essence_msg",
                    "delete_friend",
                    "delete_group_file",
                    "delete_msg",
                    "download_file",
                    "get_cookies",
                    "get_csrf_token",
                    "get_essence_msg_list",
                    "get_forward_msg",
                    "get_friend_list",
                    "get_friend_msg_history",
                    "get_group_file_system_info",
                    "get_group_file_url",
                    "get_group_files_by_folder",
                    "get_group_honor_info",
                    "get_group_info",
                    "get_group_list",
                    "get_group_member_info",
                    "get_group_member_list",
                    "get_group_msg_history",
                    "get_group_root_files",
                    "get_guild_channel_list",
                    "get_guild_list",
                    "get_guild_member_list",
                    "get_guild_member_profile",
                    "get_guild_meta_by_guest",
                    "get_guild_service_profile",
                    "get_login_info",
                    "get_msg",
                    "get_online_clients",
                    "get_private_file_url",
                    "get_stranger_info",
                    "get_version_info",
                    "send_group_forward_msg",
                    "send_group_sign",
                    "send_guild_channel_msg",
                    "send_like",
                    "send_msg",
                    "send_private_forward_msg",
                    "set_essence_msg",
                    "set_friend_add_request",
                    "set_group_add_request",
                    "set_group_admin",
                    "set_group_ban",
                    "set_group_card",
                    "set_group_kick",
                    "set_group_leave",
                    "set_group_name",
                    "set_group_portrait",
                    "set_group_special_title",
                    "set_group_whole_ban",
                    "set_qq_avatar",
                    "set_qq_profile",
                    "upload_group_file",
                    "upload_private_file",
                ],
                supportedActions: [
                    "delete_friend",
                    "delete_msg",
                    "get_cookies",
                    "get_csrf_token",
                    "get_forward_msg",
                    "get_friend_list",
                    "get_friend_msg_history",
                    "get_group_honor_info",
                    "get_group_info",
                    "get_group_list",
                    "get_group_member_info",
                    "get_group_member_list",
                    "get_group_msg_history",
                    "get_login_info",
                    "get_msg",
                    "get_stranger_info",
                    "get_version_info",
                    "send_group_forward_msg",
                    "send_like",
                    "send_msg",
                    "send_private_forward_msg",
                    "set_friend_add_request",
                    "set_group_add_request",
                    "set_group_admin",
                    "set_group_ban",
                    "set_group_card",
                    "set_group_kick",
                    "set_group_leave",
                    "set_group_name",
                    "set_group_special_title",
                    "set_group_whole_ban",
                ],
                unsupportedActions: [
                    "_get_group_notice",
                    "_send_group_notice",
                    "_set_model_show",
                    "create_group_file_folder",
                    "delete_essence_msg",
                    "delete_group_file",
                    "download_file",
                    "get_essence_msg_list",
                    "get_group_file_system_info",
                    "get_group_file_url",
                    "get_group_files_by_folder",
                    "get_group_root_files",
                    "get_guild_channel_list",
                    "get_guild_list",
                    "get_guild_member_list",
                    "get_guild_member_profile",
                    "get_guild_meta_by_guest",
                    "get_guild_service_profile",
                    "get_online_clients",
                    "get_private_file_url",
                    "send_group_sign",
                    "send_guild_channel_msg",
                    "set_essence_msg",
                    "set_group_portrait",
                    "set_qq_avatar",
                    "set_qq_profile",
                    "upload_group_file",
                    "upload_private_file",
                ],
                note: "静态审计 TRSS-Yunzai 官方 OneBotv11 适配器的直接 sendApi 调用；不代表完整进程互操作已验证。",
            },
            upstream: "https://yunzai-bot.com/get-started/platform.html",
            defaultFrameworkOrigin: "http://127.0.0.1:2536",
            limitations: [
                "审计版本的 59 个直接动作中支持 31 个，剩余 28 个集中在文件、群公告、频道与 QQ 资料私有动作。",
                "不同云崽分支的 OneBot 入口与扩展动作并不完全一致；尚未完成固定版本完整进程互操作。",
            ],
        },
        zhenxun: {
            id: "zhenxun",
            displayName: "真寻",
            kind: "distribution",
            packageName: "nonebot-adapter-onebot",
            protocol: "onebot.v11",
            transport: "reverse-websocket",
            verification: "documented",
            distributionAudit: {
                sourceRevision: "39ed1ade1469318d53b5beb943f05b89664d294e",
                auditedAt: "2026-09-02",
                requiredActions: [
                    "delete_friend",
                    "delete_msg",
                    "get_forward_msg",
                    "get_friend_list",
                    "get_group_info",
                    "get_group_list",
                    "get_group_member_info",
                    "get_group_member_list",
                    "get_login_info",
                    "get_stranger_info",
                    "send_group_forward_msg",
                    "send_group_msg",
                    "send_private_msg",
                    "set_friend_add_request",
                    "set_group_add_request",
                    "set_group_ban",
                    "set_group_leave",
                ],
                supportedActions: [
                    "delete_friend",
                    "delete_msg",
                    "get_forward_msg",
                    "get_friend_list",
                    "get_group_info",
                    "get_group_list",
                    "get_group_member_info",
                    "get_group_member_list",
                    "get_login_info",
                    "get_stranger_info",
                    "send_group_forward_msg",
                    "send_group_msg",
                    "send_private_msg",
                    "set_friend_add_request",
                    "set_group_add_request",
                    "set_group_ban",
                    "set_group_leave",
                ],
                unsupportedActions: [],
                note: "静态审计真寻核心源码中的明确 OneBot API 调用；第三方插件、动态 call_api 与完整进程仍未验证。",
            },
            upstream: "https://github.com/zhenxun-org/zhenxun_bot",
            defaultFrameworkOrigin: "http://127.0.0.1:8080",
            limitations: [
                "审计版本核心源码中的 17 个明确 OneBot 动作均有协议入口，但完整真寻进程与第三方插件仍待验证。",
                "模板不承诺动态 call_api、第三方插件或 QQ 协议端私有字段。",
            ],
        },
    });
