import type { FrameworkProfile } from "./framework-integration-types.js";
import { deepFreeze } from "./framework-integration-utils.js";

export const FRAMEWORK_PROFILES: Readonly<Record<string, FrameworkProfile>> = deepFreeze({
    koishi: {
        id: "koishi",
        displayName: "Koishi",
        kind: "framework",
        packageName: "@koishijs/plugin-adapter-satori",
        protocol: "satori.v1",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "4.18.6",
            adapterVersion: "1.5.1",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:koishi",
            checks: ["auth-rejection", "handshake", "private-message", "message.create"],
        },
        upstream: "https://koishi.chat/en-US/plugins/adapter/satori",
        defaultFrameworkOrigin: null,
        limitations: [
            "群消息、富媒体、重连与完整 Satori 资源动作矩阵仍待固定版本验证。",
            "Koishi 4.18.6 的固定依赖审计包含由 file-type GHSA-5v7r-6r5c-r473 传播的 12 个中等级条目。",
        ],
    },
    nonebot: {
        id: "nonebot",
        displayName: "NoneBot2",
        kind: "framework",
        packageName: "nonebot-adapter-onebot",
        protocol: "onebot.v11",
        transport: "reverse-websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "2.5.0",
            adapterVersion: "2.4.6",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:nonebot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://onebot.adapters.nonebot.dev/docs/guide/setup/",
        defaultFrameworkOrigin: "http://127.0.0.1:8080",
        limitations: ["群消息、富媒体、重连与完整动作矩阵仍待固定版本验证。"],
    },
    karin: {
        id: "karin",
        displayName: "Karin",
        kind: "framework",
        packageName: "@karinjs/plugin-adapter-milky",
        protocol: "milky.v1",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "1.15.3",
            adapterVersion: "1.3.3",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:karin",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "get_impl_info",
                "send_private_message",
            ],
        },
        upstream: "https://github.com/KarinJS/karin-plugin-adapter-milky",
        defaultFrameworkOrigin: null,
        limitations: [
            "群消息、富媒体、重连、SSE、Webhook 与完整动作矩阵仍待固定版本验证。",
            "插件 1.3.3 未在发布包依赖中声明 node-karin，独立安装时必须显式安装 1.15.3。",
            "node-karin 1.15.3 固定 yaml 2.7.0，受 GHSA-48c2-rrv3-qjmp 影响且当前无可用自动修复。",
        ],
    },
    zhin: {
        id: "zhin",
        displayName: "Zhin",
        kind: "framework",
        packageName: "@zhin.js/adapter-onebot11",
        protocol: "onebot.v11",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "6.0.15",
            adapterVersion: "7.0.8",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:zhin",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://www.npmjs.com/package/@zhin.js/adapter-onebot11",
        defaultFrameworkOrigin: null,
        limitations: ["群消息、富媒体、重连、侧事件与完整动作矩阵仍待固定版本验证。"],
    },
    alemonjs: {
        id: "alemonjs",
        displayName: "AlemonJS",
        kind: "framework",
        packageName: "@alemonjs/onebot",
        protocol: "onebot.v11",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "2.1.103",
            adapterVersion: "2.1.21",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:alemonjs",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://www.npmjs.com/package/@alemonjs/onebot",
        defaultFrameworkOrigin: null,
        limitations: [
            "OneBot 12 仍是上游实验路径；默认模板固定使用 OneBot 11。",
            "固定版本依赖的 npm audit 报告 file-type 中等级拒绝服务风险；上游修复前不提升为 verified。",
            "群消息、富媒体、重连、侧事件与完整动作矩阵仍待固定版本验证。",
        ],
    },
    melobot: {
        id: "melobot",
        displayName: "melobot",
        kind: "framework",
        packageName: "melobot[onebot]",
        protocol: "onebot.v11",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "3.4.0",
            adapterVersion: "built-in",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:melobot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://docs.melobot.org/ob_refer/impl.html",
        defaultFrameworkOrigin: null,
        limitations: ["群消息、富媒体、重连、反向 WebSocket 与完整动作矩阵仍待验证。"],
    },
    zerobot: {
        id: "zerobot",
        displayName: "ZeroBot",
        kind: "framework",
        packageName: "github.com/wdvxdr1123/ZeroBot",
        protocol: "onebot.v11",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "1.8.2",
            adapterVersion: "built-in",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:zerobot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://github.com/wdvxdr1123/ZeroBot",
        defaultFrameworkOrigin: null,
        limitations: ["群消息、富媒体、重连、反向 WebSocket 与完整动作矩阵仍待验证。"],
    },
    kovi: {
        id: "kovi",
        displayName: "Kovi",
        kind: "framework",
        packageName: "kovi-onebot",
        protocol: "onebot.v11",
        transport: "websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "0.13.0",
            adapterVersion: "0.13.2",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:kovi",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://github.com/ThriceCola/Kovi",
        defaultFrameworkOrigin: null,
        limitations: [
            "Kovi 0.13.2 会生成带双斜杠的 /api 与 /event 地址，OneBots 已提供精确兼容路径。",
            "Milky driver、群消息、富媒体、断线重连与完整动作矩阵仍待验证。",
        ],
    },
    astrbot: {
        id: "astrbot",
        displayName: "AstrBot",
        kind: "framework",
        packageName: "AstrBot",
        protocol: "onebot.v11",
        transport: "reverse-websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "4.28.0b1",
            adapterVersion: "1.4.4",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:astrbot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream:
            "https://github.com/AstrBotDevs/AstrBot/blob/master/docs/zh/platform/aiocqhttp.md",
        defaultFrameworkOrigin: "http://127.0.0.1:6199",
        limitations: [
            "证据覆盖官方 AiocqhttpAdapter 边界，不代表 AstrBot 模型、插件与 WebUI 全栈已经验证。",
            "群消息、富媒体、重连与完整动作矩阵仍待验证。",
        ],
    },
    langbot: {
        id: "langbot",
        displayName: "LangBot",
        kind: "framework",
        packageName: "langbot",
        protocol: "onebot.v11",
        transport: "reverse-websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "4.10.9",
            adapterVersion: "built-in",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:langbot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://github.com/langbot-app/LangBot",
        defaultFrameworkOrigin: "http://127.0.0.1:2280",
        limitations: [
            "证据覆盖官方 AiocqhttpAdapter 边界，不代表模型、流水线、插件与 WebUI 全栈已经验证。",
            "群消息、富媒体、重连与完整动作矩阵仍待验证。",
        ],
    },
    alicebot: {
        id: "alicebot",
        displayName: "AliceBot",
        kind: "framework",
        packageName: "alicebot-adapter-cqhttp",
        protocol: "onebot.v11",
        transport: "reverse-websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "0.11.0",
            adapterVersion: "0.11.0",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:alicebot",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://github.com/AliceBotProject/alicebot",
        defaultFrameworkOrigin: "http://127.0.0.1:8080",
        limitations: [
            "AliceBot 0.11.0 的反向 WebSocket 鉴权误读响应头，生成方案使用握手前鉴权子类修复该边界。",
            "证据覆盖 CQHTTP adapter 的事件与动作边界；插件调度、群消息、富媒体和重连仍待验证。",
        ],
    },
    kotori: {
        id: "kotori",
        displayName: "Kotori",
        kind: "framework",
        packageName: "@kotori-bot/kotori-plugin-adapter-onebot",
        protocol: "onebot.v11",
        transport: "reverse-websocket",
        verification: "handshake",
        evidence: {
            frameworkVersion: "1.7.5",
            adapterVersion: "2.1.2",
            lastVerifiedAt: "2026-09-02",
            command: "pnpm interop:kotori",
            checks: [
                "auth-rejection",
                "handshake",
                "private-message",
                "get_login_info",
                "send_private_msg",
            ],
        },
        upstream: "https://github.com/kotorijs/kotori",
        defaultFrameworkOrigin: "http://127.0.0.1:7200",
        limitations: [
            "官方 adapter 2.1.2 不提供 token 配置，生成方案通过 connection 扩展点在事件进入 adapter 前校验握手。",
            "证据覆盖官方 OneBot adapter 的会话、身份动作与私聊发送；完整 Loader、群消息和重连仍待验证。",
        ],
    },
});
