// App exports
export { App, createOnebots, defineConfig } from "./app.js";
export { getAppConfigSchema } from "./config-schema.js";

// Re-export core symbols that adapters and protocols depend on
// (avoids requiring consumers to add @onebots/core as a direct dependency)
export {
    // Registry
    AdapterRegistry,
    ProtocolRegistry,
    // Base classes
    Adapter,
    Account,
    Protocol,
    BaseApp,
    SqliteDB,
    Router,
    // Types
    CommonEvent,
    CommonTypes,
    AccountStatus,
    AdapterError,
    ErrorCategory,
    ErrorSeverity,
    NetworkError,
    OneBotsError,
    ResourceError,
    RuntimeError,
    UnsupportedCapabilityError,
    ValidationError,
    type Schema,
    type RouterContext,
    type Next,
    type Dict,
    type WsServer,
    type AdapterCapabilityManifest,
    type CapabilityDescriptor,
    type ReverseWebSocketOptions,
    type MediaSourceInput,
    type MaterializedMedia,
    type PlatformActionHandler,
    type PlatformActionParams,
    type PlatformActionRegistry,
    type RefreshableValueResult,
    // Infrastructure
    ConnectionManager,
    ReverseWebSocketSession,
    RetryPresets,
    // Utilities
    yaml,
    configure,
    readLine,
    dateLikeToEventMs,
    toUnixSeconds,
    unixSecondsToEventMs,
    unixMillisToEventMs,
    coerceUnixToEventMs,
    requirePositiveIntegerParam,
    requireNonEmptyStringParam,
    requireBooleanParam,
    readPackageVersion,
    readPackageVersionFile,
    materializeMediaSource,
    definePlatformActions,
    isSafeAbsoluteApiPath,
    emitAwaited,
    KeyedSingleFlight,
    mapConcurrent,
    RefreshableValue,
    RecentEventDeduplicator,
    sha256Json,
    sha256Text,
    stableJsonStringify,
    defineAdapterCapabilities,
    assertAdapterCapabilities,
    assertAdapterCapabilityContract,
    assertSupportedActionsImplemented,
    adapterActionMethodName,
    listSupportedActions,
    decryptWechatCallback,
    decryptWechatCallbackFor,
    extractWechatEncryptedPayload,
    parseWechatXml,
    verifyWechatCallbackSignature,
    // Proxy
    buildProxyUrl,
    maskProxyUrl,
    createProxyAgent,
    createHttpsProxyAgent,
    createSocksProxyAgent,
    // Auth
    createManagedTokenValidator,
    initTokenManager,
    // Config
    ConfigValidator,
} from "@onebots/core";
