// App exports
export { App, createOnebots, defineConfig } from "./app.js";
export { getAppConfigSchema } from "./config-schema.js";

// Re-export core symbols that adapters and protocols depend on
// (avoids requiring consumers to add @onebots/core as a direct dependency)
export {
    // Registry
    AdapterRegistry,
    ProtocolRegistry,
    // Base classes
    Adapter,
    Account,
    Protocol,
    BaseApp,
    SqliteDB,
    Router,
    // Types
    CommonEvent,
    CommonTypes,
    AccountStatus,
    AdapterError,
    ErrorCategory,
    ErrorSeverity,
    NetworkError,
    OneBotsError,
    ResourceError,
    RuntimeError,
    UnsupportedCapabilityError,
    ValidationError,
    type Schema,
    type RouterContext,
    type Next,
    type Dict,
    type WsServer,
    type AdapterCapabilityManifest,
    type CapabilityDescriptor,
    type ReverseWebSocketOptions,
    type MediaSourceInput,
    type MaterializedMedia,
    type PlatformActionHandler,
    type PlatformActionContractErrors,
    type PlatformActionParameterMap,
    type UnexpectedPlatformActionParameter,
    type PlatformActionParams,
    type PlatformActionRegistry,
    type PlatformHttpActionParamRule,
    type PlatformHttpActionRoute,
    type PlatformHttpActionRequest,
    type PlatformHttpActionValidationIssue,
    type PlatformHttpStringParamRule,
    type PlatformHttpIntegerParamRule,
    type PlatformHttpBooleanParamRule,
    type PlatformHttpArrayParamRule,
    type PlatformHttpObjectArrayParamRule,
    type PlatformHttpConditionalRequirement,
    type PlatformHttpGetActionRoute,
    type PlatformHttpPostActionRoute,
    type RefreshableValueResult,
    type EventDeliveryStore,
    type EventDeliveryRetry,
    type OrderedEventDeliveryQueueOptions,
    // Infrastructure
    ConnectionManager,
    ReverseWebSocketSession,
    RetryPresets,
    // Utilities
    yaml,
    configure,
    readLine,
    dateLikeToEventMs,
    toUnixSeconds,
    unixSecondsToEventMs,
    unixMillisToEventMs,
    coerceUnixToEventMs,
    requirePositiveIntegerParam,
    requireNonEmptyStringParam,
    requireBooleanParam,
    readPackageVersion,
    readPackageVersionFile,
    materializeMediaSource,
    definePlatformActions,
    definePlatformActionContract,
    definePlatformActionHandlers,
    definePlatformHttpActionRoutes,
    isCanonicalAdapterAction,
    isSafeAbsoluteApiPath,
    emitAllAwaited,
    emitAwaited,
    KeyedSingleFlight,
    FailureCollector,
    mapConcurrent,
    RefreshableValue,
    RecentEventDeduplicator,
    ReliableEventIngress,
    OrderedEventDeliveryQueue,
    sha256Json,
    sha256Text,
    stableJsonStringify,
    defineAdapterCapabilities,
    definePlatformActionCapabilities,
    assertAdapterCapabilities,
    assertAdapterCapabilityContract,
    assertSupportedActionsImplemented,
    adapterActionMethodName,
    listSupportedActions,
    decryptWechatCallback,
    decryptWechatCallbackFor,
    extractWechatEncryptedPayload,
    parseWechatXml,
    verifyWechatCallbackSignature,
    createWechatJsApiSignature,
    type WechatJsApiSignature,
    type WechatJsApiSignatureOptions,
    // Proxy
    buildProxyUrl,
    maskProxyUrl,
    createProxyAgent,
    createHttpsProxyAgent,
    createSocksProxyAgent,
    // Auth
    createManagedTokenValidator,
    initTokenManager,
    // Config
    ConfigValidator,
} from "@onebots/core";
