import { BaseApp } from "@onebots/core";
import {
    applyRuntimeConfigFile,
    saveAndApplyRuntimeConfig,
    type RuntimeConfigApplicationHost,
    type RuntimeConfigApplicationResult,
} from "./runtime-config-application.js";

interface BackupResult {
    success: boolean;
    message?: string;
}

interface ManagementLogger {
    warn(message: string, context?: unknown): void;
}

export interface ManagedRuntimeConfigHost extends RuntimeConfigApplicationHost {
    credentialsWereAutoGenerated: boolean;
    backupDataToHf(content: string): Promise<BackupResult>;
    logger?: ManagementLogger;
}

export interface ManagedRuntimeConfigResult extends RuntimeConfigApplicationResult {
    success: true;
    message: string;
}

/** HTTP 与管理 WebSocket 共用的保存入口，确保运行态与副作用语义一致。 */
export async function saveManagedRuntimeConfig(
    host: ManagedRuntimeConfigHost,
    content: string,
    configPath = BaseApp.configPath,
): Promise<ManagedRuntimeConfigResult> {
    const result = await saveAndApplyRuntimeConfig(host, content, configPath);
    host.credentialsWereAutoGenerated = false;
    await backupConfigBestEffort(host, content, result.applied);
    return describeManagedRuntimeConfigResult(result, "配置已保存并生效", "配置已保存");
}

/** 重新应用磁盘配置，不重写文件或生成新备份。 */
export async function reloadManagedRuntimeConfig(
    host: ManagedRuntimeConfigHost,
    configPath = BaseApp.configPath,
): Promise<ManagedRuntimeConfigResult> {
    const result = await applyRuntimeConfigFile(host, configPath);
    return describeManagedRuntimeConfigResult(result, "配置已重新加载", "配置已读取");
}

function describeManagedRuntimeConfigResult(
    result: RuntimeConfigApplicationResult,
    appliedMessage: string,
    savedMessage: string,
): ManagedRuntimeConfigResult {
    return result.restartRequired
        ? {
              success: true,
              ...result,
              message: `${savedMessage}；${result.changedHostFields.join(", ")} 需要重启后生效`,
          }
        : { success: true, ...result, message: appliedMessage };
}

async function backupConfigBestEffort(
    host: ManagedRuntimeConfigHost,
    content: string,
    applied: boolean,
): Promise<void> {
    try {
        const result = await host.backupDataToHf(content);
        if (!result.success && result.message) host.logger?.warn(result.message);
    } catch (error) {
        host.logger?.warn(`配置已保存${applied ? "并生效" : ""}，但自动备份失败`, { error });
    }
}
