import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { writeConfigFileAtomic } from "@onebots/core";
import { handleManagementConfigSocketAction } from "./management-config-socket.js";
import type { ManagedRuntimeConfigHost } from "./managed-runtime-config.js";

const directories: string[] = [];

function configFile(content = "access_token: old-token\n"): string {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), "onebots-config-socket-"));
    directories.push(directory);
    const file = path.join(directory, "config.yaml");
    fs.writeFileSync(file, content, { mode: 0o600 });
    return file;
}

function host(isReloading = false): ManagedRuntimeConfigHost & {
    reload: ReturnType<typeof vi.fn>;
    backupDataToHf: ReturnType<typeof vi.fn>;
} {
    return {
        isReloading,
        reload: vi.fn(async () => undefined),
        credentialsWereAutoGenerated: true,
        backupDataToHf: vi.fn(async () => ({ success: true })),
        logger: { warn: vi.fn() },
    };
}

afterEach(() => {
    for (const directory of directories.splice(0)) {
        fs.rmSync(directory, { recursive: true, force: true });
    }
});

describe("management config WebSocket actions", () => {
    it("保存后应用配置并返回带 echo 的机器回执", async () => {
        const file = configFile();
        const app = host();

        await expect(
            handleManagementConfigSocketAction(
                app,
                {
                    action: "system.saveConfig",
                    data: "access_token: next-token\n",
                    echo: "request-1",
                },
                file,
            ),
        ).resolves.toEqual({
            event: "system.config.result",
            echo: "request-1",
            data: {
                success: true,
                applied: true,
                restartRequired: false,
                changedHostFields: [],
                message: "配置已保存并生效",
            },
        });
        expect(app.reload).toHaveBeenCalledWith({ access_token: "next-token" });
        expect(app.backupDataToHf).toHaveBeenCalledWith("access_token: next-token\n");
        expect(app.credentialsWereAutoGenerated).toBe(false);
    });

    it("无效配置返回 CONFIG_INVALID 且不覆盖磁盘", async () => {
        const file = configFile();
        const app = host();

        const response = await handleManagementConfigSocketAction(
            app,
            { action: "system.saveConfig", data: "accounts: [\n" },
            file,
        );

        expect(response).toMatchObject({
            event: "system.config.result",
            data: { success: false, code: "CONFIG_INVALID" },
        });
        expect(fs.readFileSync(file, "utf8")).toBe("access_token: old-token\n");
        expect(app.reload).not.toHaveBeenCalled();
    });

    it("重载磁盘配置返回回执且不执行远端备份", async () => {
        const file = configFile("access_token: disk-token\n");
        const app = host();

        const response = await handleManagementConfigSocketAction(
            app,
            { action: "system.reload" },
            file,
        );

        expect(response).toMatchObject({
            event: "system.config.result",
            data: { success: true, applied: true, message: "配置已重新加载" },
        });
        expect(app.reload).toHaveBeenCalledWith({ access_token: "disk-token" });
        expect(app.backupDataToHf).not.toHaveBeenCalled();
    });

    it("配置事务冲突返回 CONFIG_CONFLICT 而不是拒绝消息监听器", async () => {
        const file = configFile();
        const app = host(true);

        await expect(
            handleManagementConfigSocketAction(app, { action: "system.reload", echo: 7 }, file),
        ).resolves.toMatchObject({
            echo: 7,
            data: { success: false, code: "CONFIG_CONFLICT" },
        });
    });

    it("运行态失败返回 CONFIG_APPLY_FAILED 并恢复磁盘配置", async () => {
        const file = configFile();
        const app = host();
        app.reload.mockRejectedValue(new Error("adapter failed"));

        const response = await handleManagementConfigSocketAction(
            app,
            { action: "system.saveConfig", data: "access_token: next-token\n" },
            file,
        );

        expect(response).toMatchObject({
            data: {
                success: false,
                code: "CONFIG_APPLY_FAILED",
                message: "adapter failed",
            },
        });
        expect(fs.readFileSync(file, "utf8")).toBe("access_token: old-token\n");
        expect(app.backupDataToHf).not.toHaveBeenCalled();
    });

    it("外部配置写入导致回滚冲突时返回 CONFIG_CONFLICT", async () => {
        const file = configFile();
        const concurrent = "access_token: external-token\nlog_level: debug\n";
        const app = host();
        app.reload.mockImplementation(async () => {
            writeConfigFileAtomic(file, concurrent);
            throw new Error("adapter failed");
        });

        const response = await handleManagementConfigSocketAction(
            app,
            { action: "system.saveConfig", data: "access_token: next-token\n" },
            file,
        );

        expect(response).toMatchObject({
            data: {
                success: false,
                code: "CONFIG_CONFLICT",
                message: "配置应用失败，且磁盘配置已被另一操作更新；已保留最新文件",
            },
        });
        expect(fs.readFileSync(file, "utf8")).toBe(concurrent);
        expect(app.backupDataToHf).not.toHaveBeenCalled();
    });

    it("忽略不属于配置管理的消息", async () => {
        await expect(
            handleManagementConfigSocketAction(host(), { action: "bot.start" }),
        ).resolves.toBeUndefined();
    });
});
