import path from "node:path";
import { pathToFileURL } from "node:url";
import { buildServiceArgs, type ServiceSpec } from "./service-definition.js";

/** 来自历史 node-windows 实现（425515a5 的父提交），不是新 manager SCM 名称。 */
export const LEGACY_WINDOWS_SYSTEM_SERVICE_ID = "onebotsgateway.exe";
const invalid = () => new Error("旧 Windows 系统服务契约无效，禁止迁移");

export interface LegacyWindowsSystemFiles {
    definition: string;
    executable: string;
    runner: string;
}

/** 仅历史证据路径，不创建 runner、安装 node-windows 或注册旧服务。 */
export function legacyWindowsSystemFiles(spec: ServiceSpec, stateDirectory: string): LegacyWindowsSystemFiles {
    validate(spec, stateDirectory);
    const directory = path.win32.join(path.win32.dirname(spec.binPath), "daemon");
    return {
        definition: path.win32.join(directory, "onebotsgateway.xml"),
        executable: path.win32.join(directory, LEGACY_WINDOWS_SYSTEM_SERVICE_ID),
        runner: path.win32.join(stateDirectory, "onebots-system-runner.mjs"),
    };
}

/** 原历史生成器的精确字节；只能用于识别/备份，不能作为当前包的执行入口。 */
export function historicalWindowsSystemRunner(spec: ServiceSpec): string {
    validate(spec, path.win32.dirname(spec.configPath));
    const entry = spec.binPath;
    return `// Generated by OneBots. Reinstall the service instead of editing this file.
const entry = ${JSON.stringify(entry)};
process.argv = [process.execPath, entry, ...${JSON.stringify(buildServiceArgs(spec).slice(1))}];
process.chdir(${JSON.stringify(spec.workingDirectory)});
await import(${JSON.stringify(pathToFileURL(entry, { windows: true }).href)});
`;
}

/** 校验旧 WinSW 扁平 XML 全契约，含 node-windows wrapper 路径和重启参数。 */
export function validateLegacyWindowsSystemXml(
    xml: string,
    spec: ServiceSpec,
    stateDirectory: string,
    wrapperPath: string,
): boolean {
    try {
        validate(spec, stateDirectory);
        absolute(wrapperPath);
        if (typeof xml !== "string" || Buffer.byteLength(xml) > 64 * 1024) return false;
        const body = /^\s*<service>\s*([\s\S]*?)\s*<\/service>\s*$/u.exec(xml)?.[1];
        if (body === undefined) return false;
        const elements: Array<[string, string]> = [];
        const pattern = /<([a-z]+)>([^<]*)<\/\1>/gu;
        let cursor = 0;
        for (const match of body.matchAll(pattern)) {
            if (body.slice(cursor, match.index).trim()) return false;
            const decoded = decodeXml(match[2]);
            if (decoded === null) return false;
            elements.push([match[1], decoded]);
            cursor = match.index + match[0].length;
        }
        if (body.slice(cursor).trim()) return false;
        const files = legacyWindowsSystemFiles(spec, stateDirectory);
        const expected: Array<[string, string]> = [
            ["id", LEGACY_WINDOWS_SYSTEM_SERVICE_ID],
            ["name", "onebots-gateway"],
            ["description", "OneBots Bridge Service"],
            ["executable", spec.nodePath],
            ...["--harmony", wrapperPath, "--file", files.runner, "--scriptoptions=", "--log",
                "onebots-gateway wrapper", "--grow", "0", "--wait", "5", "--maxrestarts", "-1",
                "--abortonerror", "n", "--stopparentfirst", "undefined"].map(value =>
                ["argument", value] as [string, string]),
            ["logmode", "rotate"], ["logpath", stateDirectory], ["stoptimeout", "30sec"],
            ["workingdirectory", spec.workingDirectory],
        ];
        return JSON.stringify(elements) === JSON.stringify(expected);
    } catch {
        return false;
    }
}

function absolute(value: string): void {
    // 禁止 drive-relative、UNC/设备命名空间、ADS 与含隐含归一化的路径。
    if (typeof value !== "string" || !/^[A-Za-z]:\\/.test(value) ||
        /[\u0000-\u001f\u007f]/.test(value) || value.slice(2).includes(":") ||
        path.win32.normalize(value) !== value || value.split("\\").some(part => /[. ]$/.test(part)))
        throw invalid();
}
function validate(spec: ServiceSpec, stateDirectory: string): void {
    if (spec.scope !== "system") throw invalid();
    for (const value of [spec.binPath, spec.nodePath, spec.configPath, spec.workingDirectory, stateDirectory])
        absolute(value);
    for (const list of [spec.adapters, spec.protocols, spec.applications ?? []]) {
        if (!Array.isArray(list) || list.some(value => typeof value !== "string" ||
            /[\u0000-\u001f\u007f]/.test(value))) throw invalid();
    }
}
function decodeXml(value: string): string | null {
    if (/&(?!(?:amp|lt|gt|quot|apos);)/u.test(value)) return null;
    const entities: Record<string, string> = { amp: "&", lt: "<", gt: ">", quot: '"', apos: "'" };
    return value.replace(/&(amp|lt|gt|quot|apos);/gu, (_, key: string) => entities[key]);
}
