import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { SERVICE_NAME, buildServiceArgs, type ServiceSpec } from "./service-definition.js";

export const WINDOWS_SYSTEM_SERVICE_ID = `${SERVICE_NAME.replace(/[^\w]/gi, "").toLowerCase()}.exe`;

export interface WindowsSystemServiceFiles {
    definition: string;
    executable: string;
    runner: string;
}

export interface WindowsSystemServiceOptions {
    name: string;
    description: string;
    script: string;
    execPath: string;
    workingDirectory: string;
    logpath: string;
    wait: number;
    grow: number;
    maxRestarts: number;
}

interface XmlElement {
    name: string;
    value: string;
}

/** node-windows 将 WinSW 文件固定写入入口脚本旁的 daemon 目录。 */
export function getWindowsSystemServiceFiles(
    spec: ServiceSpec,
    stateDirectory: string,
): WindowsSystemServiceFiles {
    const directory = path.join(path.dirname(path.resolve(spec.binPath)), "daemon");
    return {
        definition: path.join(directory, `${path.parse(WINDOWS_SYSTEM_SERVICE_ID).name}.xml`),
        executable: path.join(directory, WINDOWS_SYSTEM_SERVICE_ID),
        runner: path.join(stateDirectory, "onebots-system-runner.mjs"),
    };
}

/** 通过 JS 数组传递参数，绕开 node-windows wrapper 对 scriptOptions 的空格拆分。 */
export function renderWindowsSystemRunner(spec: ServiceSpec): string {
    const entry = path.resolve(spec.binPath);
    const args = buildServiceArgs(spec).slice(1);
    return `// Generated by OneBots. Reinstall the service instead of editing this file.
const entry = ${JSON.stringify(entry)};
process.argv = [process.execPath, entry, ...${JSON.stringify(args)}];
process.chdir(${JSON.stringify(spec.workingDirectory)});
await import(${JSON.stringify(pathToFileURL(entry).href)});
`;
}

/** node-windows 只启动无额外参数的 runner；完整 CLI 参数由 runner 数组承载。 */
export function buildWindowsSystemServiceOptions(
    spec: ServiceSpec,
    stateDirectory: string,
): WindowsSystemServiceOptions {
    return {
        name: SERVICE_NAME,
        description: "OneBots Bridge Service",
        script: getWindowsSystemServiceFiles(spec, stateDirectory).runner,
        execPath: spec.nodePath,
        workingDirectory: spec.workingDirectory,
        logpath: stateDirectory,
        wait: 5,
        grow: 0,
        maxRestarts: -1,
    };
}

/** 验证 WinSW 的完整扁平配置，拒绝启动参数、路径或策略中的任何漂移。 */
export function validateWindowsSystemServiceDefinition(
    xml: string,
    spec: ServiceSpec,
    stateDirectory: string,
    wrapperPath: string,
): boolean {
    const actual = parseFlatServiceXml(xml);
    if (!actual) return false;

    const files = getWindowsSystemServiceFiles(spec, stateDirectory);
    const expected: XmlElement[] = [
        { name: "id", value: WINDOWS_SYSTEM_SERVICE_ID },
        { name: "name", value: SERVICE_NAME },
        { name: "description", value: "OneBots Bridge Service" },
        { name: "executable", value: path.resolve(spec.nodePath) },
        { name: "argument", value: "--harmony" },
        { name: "argument", value: path.resolve(wrapperPath) },
        { name: "argument", value: "--file" },
        { name: "argument", value: files.runner },
        { name: "argument", value: "--scriptoptions=" },
        { name: "argument", value: "--log" },
        { name: "argument", value: `${SERVICE_NAME} wrapper` },
        { name: "argument", value: "--grow" },
        { name: "argument", value: "0" },
        { name: "argument", value: "--wait" },
        { name: "argument", value: "5" },
        { name: "argument", value: "--maxrestarts" },
        { name: "argument", value: "-1" },
        { name: "argument", value: "--abortonerror" },
        { name: "argument", value: "n" },
        { name: "argument", value: "--stopparentfirst" },
        { name: "argument", value: "undefined" },
        { name: "logmode", value: "rotate" },
        { name: "logpath", value: stateDirectory },
        { name: "stoptimeout", value: "30sec" },
        { name: "workingdirectory", value: spec.workingDirectory },
    ];

    return (
        actual.length === expected.length &&
        actual.every(
            (element, index) =>
                element.name === expected[index]?.name && element.value === expected[index]?.value,
        )
    );
}

function parseFlatServiceXml(xml: string): XmlElement[] | null {
    const service = xml.match(/^\s*<service>\s*([\s\S]*?)\s*<\/service>\s*$/u);
    if (!service) return null;

    const body = service[1] ?? "";
    const elements: XmlElement[] = [];
    const pattern = /<([a-z]+)>([^<]*)<\/\1>/gu;
    let cursor = 0;
    for (const match of body.matchAll(pattern)) {
        if (body.slice(cursor, match.index).trim()) return null;
        const value = decodeXmlText(match[2] ?? "");
        if (value === null) return null;
        elements.push({ name: match[1] ?? "", value });
        cursor = (match.index ?? 0) + match[0].length;
    }
    if (body.slice(cursor).trim()) return null;
    return elements;
}

function decodeXmlText(value: string): string | null {
    if (/&(?!(?:amp|lt|gt|quot|apos);)/u.test(value)) return null;
    const entities: Record<string, string> = {
        amp: "&",
        lt: "<",
        gt: ">",
        quot: '"',
        apos: "'",
    };
    return value.replace(/&(amp|lt|gt|quot|apos);/gu, (_, name: string) => entities[name] ?? "");
}
