import * as path from "node:path";
import { pathToFileURL } from "node:url";
import { buildServiceArgs, type ServiceSpec } from "./service-definition.js";

export interface WindowsUserServiceFiles {
    definition: string;
    legacyRunner: string;
    log: string;
    runner: string;
}

/** 用户级计划任务的全部持久化文件都位于用户状态目录。 */
export function getWindowsUserServiceFiles(stateDirectory: string): WindowsUserServiceFiles {
    return {
        definition: path.join(stateDirectory, "onebots-service.xml"),
        legacyRunner: path.join(stateDirectory, "onebots-runner.cmd"),
        log: path.join(stateDirectory, "onebots.log"),
        runner: path.join(stateDirectory, "onebots-user-runner.mjs"),
    };
}

/**
 * 在同一 Node 进程中恢复 CLI 参数并加载入口，避免 cmd.exe 展开路径和配置中的元字符。
 * stdout/stderr 使用同步追加，确保任务计划没有控制台时仍可通过 `onebots logs` 读取。
 */
export function renderWindowsUserRunner(spec: ServiceSpec, logPath: string): string {
    const entry = path.resolve(spec.binPath);
    const args = buildServiceArgs(spec).slice(1);
    return `// Generated by OneBots. Reinstall the service instead of editing this file.
import { closeSync, openSync, writeSync } from "node:fs";

const logDescriptor = openSync(${JSON.stringify(logPath)}, "a");
const writeLog = (chunk, encoding, callback) => {
    const done = typeof encoding === "function" ? encoding : callback;
    try {
        const data =
            typeof chunk === "string"
                ? Buffer.from(chunk, typeof encoding === "string" ? encoding : "utf8")
                : chunk;
        writeSync(logDescriptor, data);
        if (typeof done === "function") done();
        return true;
    } catch (error) {
        if (typeof done === "function") {
            done(error);
            return false;
        }
        throw error;
    }
};
process.stdout.write = writeLog;
process.stderr.write = writeLog;
process.once("exit", () => closeSync(logDescriptor));

const entry = ${JSON.stringify(entry)};
process.argv = [process.execPath, entry, ...${JSON.stringify(args)}];
process.chdir(${JSON.stringify(spec.workingDirectory)});
await import(${JSON.stringify(pathToFileURL(entry).href)});
`;
}

/** 任务计划直接执行 Node runner，不经过 cmd.exe 或 PowerShell。 */
export function renderWindowsUserTaskXml(nodePath: string, runnerPath: string): string {
    const argumentsValue = windowsQuote(runnerPath);
    return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <Triggers><LogonTrigger><Enabled>true</Enabled></LogonTrigger></Triggers>
  <Principals><Principal id="Author"><LogonType>InteractiveToken</LogonType><RunLevel>LeastPrivilege</RunLevel></Principal></Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <RestartOnFailure><Interval>PT5S</Interval><Count>999</Count></RestartOnFailure>
    <StartWhenAvailable>true</StartWhenAvailable>
  </Settings>
  <Actions Context="Author"><Exec><Command>${xmlEscape(nodePath)}</Command><Arguments>${xmlEscape(argumentsValue)}</Arguments></Exec></Actions>
</Task>
`;
}

function windowsQuote(value: string): string {
    return `"${value.replace(/(\\*)"/g, '$1$1\\"').replace(/(\\+)$/g, "$1$1")}"`;
}

function xmlEscape(value: string): string {
    return value
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&apos;");
}
