import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

/** Slack Web API/Events API 当前可用的能力。 */
export const slackCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "channel"] },
        delete_message: { support: "native" },
        update_message: { support: "native" },
        get_message: { support: "native", availability: "context" },
        get_login_info: { support: "native" },
        get_user_info: { support: "native" },
        get_friend_list: { support: "native", note: "按工作区用户目录投影" },
        get_friend_info: { support: "emulated", note: "按工作区用户投影" },
        get_group_list: { support: "emulated", note: "按频道投影群组" },
        get_group_info: { support: "emulated", note: "按频道投影群组" },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native" },
        get_group_member_info: { support: "native" },
        kick_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["channels:manage"],
        },
        call_slack_api: {
            support: "native",
            availability: "context",
            note: "受当前 token scopes 约束的原生 Slack Web API 入口",
        },
        add_reaction: { support: "native", permissions: ["reactions:write"] },
        remove_reaction: { support: "native", permissions: ["reactions:write"] },
        add_pin: { support: "native", permissions: ["pins:write"] },
        remove_pin: { support: "native", permissions: ["pins:write"] },
        get_thread_replies: { support: "native", availability: "permission" },
        open_conversation: { support: "native", availability: "permission" },
        create_channel: { support: "native", availability: "permission" },
        archive_channel: { support: "native", availability: "permission" },
        unarchive_channel: { support: "native", availability: "permission" },
        rename_channel: { support: "native", availability: "permission" },
        set_channel_topic: { support: "native", availability: "permission" },
        set_channel_purpose: { support: "native", availability: "permission" },
        join_channel: { support: "native", availability: "permission" },
        invite_channel_members: { support: "native", availability: "permission" },
        kick_channel_member: { support: "native", availability: "permission" },
        schedule_message: { support: "native", permissions: ["chat:write"] },
        delete_scheduled_message: { support: "native", permissions: ["chat:write"] },
        list_scheduled_messages: { support: "native", permissions: ["chat:write"] },
        add_bookmark: { support: "native", availability: "permission" },
        edit_bookmark: { support: "native", availability: "permission" },
        remove_bookmark: { support: "native", availability: "permission" },
        list_bookmarks: { support: "native", availability: "permission" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "channel"] },
        message_updated: { support: "native" },
        message_deleted: { support: "native" },
        reaction_added: { support: "native" },
        reaction_removed: { support: "native" },
        member_joined: { support: "native" },
        member_left: { support: "native" },
        native_event: {
            support: "native",
            note: "所有未标准化 Events API 事件以 custom notice 和 raw_event 无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "send" },
        image: { support: "native", direction: "send" },
        file: {
            support: "emulated",
            direction: "send",
            note: "当前将文件 URL 投影为消息文本；原生上传可通过 call_slack_api 扩展",
        },
        audio: { support: "native", direction: "receive" },
        video: { support: "native", direction: "receive" },
        reply: { support: "native", direction: "both" },
    },
    transports: {
        socket_mode: { support: "native", mode: "websocket" },
        webhook: { support: "native", mode: "webhook" },
    },
});
