import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";
import { SLACK_PLATFORM_ACTIONS } from "./platform-actions.js";

const platformActions = Object.fromEntries(
    [...SLACK_PLATFORM_ACTIONS].map(action => [
        action,
        { support: "native" as const, availability: "context" as const },
    ]),
);

/** Slack Web API/Events API 当前可用的能力。 */
export const slackCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        ...platformActions,
        send_message: { support: "native", scenes: ["private", "channel"] },
        delete_message: {
            support: "native",
            availability: "context",
            note: "需提供 scene_id，或消息已由当前进程收发",
        },
        update_message: {
            support: "native",
            availability: "context",
            note: "需提供 scene_id，或消息已由当前进程收发",
        },
        get_message: { support: "native", availability: "context" },
        get_login_info: { support: "native" },
        get_user_info: { support: "native" },
        get_friend_list: { support: "native", note: "按工作区用户目录投影" },
        get_friend_info: { support: "emulated", note: "按工作区用户投影" },
        get_channel_list: { support: "native" },
        get_channel_info: { support: "native" },
        get_channel_member_list: { support: "native" },
        get_channel_member_info: { support: "native" },
        get_file: { support: "native", availability: "permission" },
        delete_file: { support: "native", availability: "permission" },
        create_channel: { support: "native", availability: "permission" },
        update_channel: { support: "native", availability: "permission" },
        delete_channel: { support: "native", availability: "permission" },
        invite_channel_member: { support: "native", availability: "permission" },
        kick_channel_member: {
            support: "native",
            availability: "permission",
            permissions: ["channels:manage"],
        },
        call_slack_api: {
            support: "native",
            availability: "context",
            note: "受当前 token scopes 约束的原生 Slack Web API 入口",
        },
        add_reaction: { support: "native", permissions: ["reactions:write"] },
        remove_reaction: { support: "native", permissions: ["reactions:write"] },
        add_pin: { support: "native", permissions: ["pins:write"] },
        remove_pin: { support: "native", permissions: ["pins:write"] },
        get_thread_replies: { support: "native", availability: "permission" },
        open_conversation: { support: "native", availability: "permission" },
        archive_channel: { support: "native", availability: "permission" },
        unarchive_channel: { support: "native", availability: "permission" },
        rename_channel: { support: "native", availability: "permission" },
        set_channel_topic: { support: "native", availability: "permission" },
        set_channel_purpose: { support: "native", availability: "permission" },
        join_channel: { support: "native", availability: "permission" },
        invite_channel_members: { support: "native", availability: "permission" },
        leave_channel: { support: "native", availability: "permission" },
        schedule_message: { support: "native", permissions: ["chat:write"] },
        delete_scheduled_message: { support: "native", permissions: ["chat:write"] },
        list_scheduled_messages: { support: "native", permissions: ["chat:write"] },
        add_bookmark: { support: "native", availability: "permission" },
        edit_bookmark: { support: "native", availability: "permission" },
        remove_bookmark: { support: "native", availability: "permission" },
        list_bookmarks: { support: "native", availability: "permission" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "channel"] },
        message_updated: { support: "native" },
        message_deleted: { support: "native" },
        reaction_added: { support: "native" },
        reaction_removed: { support: "native" },
        member_joined: { support: "native" },
        member_left: { support: "native" },
        user_added: { support: "native" },
        user_updated: { support: "native" },
        interaction: { support: "native" },
        native_event: {
            support: "native",
            note: "所有未标准化 Events API 事件以 custom notice 和 raw_event 无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "send" },
        image: { support: "native", direction: "both" },
        file: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        reply: { support: "native", direction: "both" },
        slack_message: {
            support: "native",
            direction: "send",
            note: "承载 Block Kit、attachments 与 chat.postMessage 原生选项",
        },
    },
    transports: {
        socket_mode: { support: "native", mode: "websocket" },
        webhook: { support: "native", mode: "webhook" },
        manual: {
            support: "native",
            mode: "native",
            note: "通过 ingest()、ingestHttp() 或 acceptHttp(Request) 接入既有 Host",
        },
    },
});
