import type { ZulipEventType } from "./types.js";

/** 内置 Event Queue 默认订阅；配置显式选择时不参与合并。 */
export const ZULIP_DEFAULT_EVENT_TYPES = [
    "attachment",
    "heartbeat",
    "channel_folder",
    "drafts",
    "message",
    "navigation_view",
    "update_message",
    "update_message_flags",
    "delete_message",
    "reaction",
    "reminders",
    "saved_snippets",
    "scheduled_messages",
    "subscription",
    "stream",
    "realm_user",
    "user_group",
    "invites_changed",
    "alert_words",
    "muted_users",
    "custom_profile_fields",
    "realm_domains",
    "realm_emoji",
    "realm_linkifiers",
    "realm_playgrounds",
    "realm_export",
    "realm_export_consent",
    "presence",
    "user_status",
    "typing",
    "user_topic",
    "restart",
] as const satisfies readonly ZulipEventType[];

/** Web 配置界面与文档共用的事件名称。 */
export const ZULIP_EVENT_TYPE_LABELS: Readonly<Partial<Record<ZulipEventType, string>>> = {
    alert_words: "提醒词",
    attachment: "附件",
    channel_folder: "频道文件夹",
    drafts: "草稿",
    message: "消息",
    navigation_view: "导航视图",
    update_message: "消息更新",
    update_message_flags: "消息标记变化",
    delete_message: "消息删除",
    reaction: "表情回应",
    reminders: "提醒",
    saved_snippets: "保存片段",
    scheduled_messages: "定时消息",
    subscription: "频道订阅",
    stream: "频道",
    realm_user: "组织成员",
    user_group: "用户组",
    presence: "在线状态",
    user_status: "用户状态",
    typing: "输入状态",
    user_topic: "个人话题偏好",
    heartbeat: "心跳",
    invites_changed: "邀请变化",
    muted_users: "静音用户",
    custom_profile_fields: "自定义资料字段",
    realm_domains: "允许注册的邮箱域名",
    realm_emoji: "组织自定义表情",
    realm_linkifiers: "组织链接规则",
    realm_playgrounds: "代码运行环境",
    realm_export: "数据导出",
    realm_export_consent: "数据导出授权",
    restart: "服务器重启",
};
