import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

/** LINE Messaging API 与官方 SDK 11.x 的真实能力边界。 */
export const lineCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group"] },
        delete_message: { support: "unsupported" },
        get_message: { support: "unsupported", note: "仅支持按 ID 下载媒体内容" },
        get_login_info: { support: "native" },
        get_user_info: { support: "native", availability: "context" },
        get_friend_list: {
            support: "native",
            note: "Get followers 受 LINE 账号类型与审核状态限制",
        },
        get_friend_info: { support: "native", availability: "context" },
        get_group_list: { support: "emulated", note: "持久化 Webhook 中已知的 group/room" },
        get_group_info: { support: "native", availability: "context" },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native", availability: "permission" },
        get_group_member_info: { support: "native", availability: "context" },
        push_message: { support: "native" },
        reply_message: { support: "native" },
        multicast: { support: "native" },
        broadcast: { support: "native" },
        narrowcast: { support: "native" },
        get_narrowcast_progress: { support: "native" },
        validate_push: { support: "native" },
        validate_reply: { support: "native" },
        validate_multicast: { support: "native" },
        validate_broadcast: { support: "native" },
        validate_narrowcast: { support: "native" },
        push_messages_by_phone: { support: "native" },
        show_loading_animation: { support: "native", scenes: ["private"] },
        mark_messages_as_read: { support: "native" },
        mark_messages_as_read_by_token: { support: "native" },
        get_message_content: { support: "native" },
        get_message_content_preview: { support: "native" },
        get_message_content_transcoding: { support: "native" },
        issue_link_token: { support: "native" },
        get_followers: { support: "native" },
        get_room_member_count: { support: "native" },
        get_room_member_profile: { support: "native" },
        get_room_member_list: { support: "native" },
        get_message_quota: { support: "native" },
        get_message_quota_consumption: { support: "native" },
        get_number_of_sent_reply_messages: { support: "native" },
        get_number_of_sent_push_messages: { support: "native" },
        get_number_of_sent_multicast_messages: { support: "native" },
        get_number_of_sent_broadcast_messages: { support: "native" },
        get_phone_message_statistics: { support: "native" },
        get_aggregation_unit_name_list: { support: "native" },
        get_aggregation_unit_usage: { support: "native" },
        get_webhook_endpoint: { support: "native" },
        set_webhook_endpoint: { support: "native" },
        test_webhook_endpoint: { support: "native" },
        create_rich_menu: { support: "native" },
        get_rich_menu: { support: "native" },
        list_rich_menus: { support: "native" },
        delete_rich_menu: { support: "native" },
        set_rich_menu_image: { support: "native" },
        get_rich_menu_image: { support: "native" },
        validate_rich_menu: { support: "native" },
        get_default_rich_menu: { support: "native" },
        set_default_rich_menu: { support: "native" },
        cancel_default_rich_menu: { support: "native" },
        link_rich_menu_to_user: { support: "native" },
        unlink_rich_menu_from_user: { support: "native" },
        get_user_rich_menu: { support: "native" },
        link_rich_menu_to_users: { support: "native" },
        unlink_rich_menu_from_users: { support: "native" },
        create_rich_menu_alias: { support: "native" },
        get_rich_menu_alias: { support: "native" },
        list_rich_menu_aliases: { support: "native" },
        update_rich_menu_alias: { support: "native" },
        delete_rich_menu_alias: { support: "native" },
        rich_menu_batch: { support: "native" },
        validate_rich_menu_batch: { support: "native" },
        get_rich_menu_batch_progress: { support: "native" },
        create_coupon: { support: "native" },
        get_coupon: { support: "native" },
        list_coupons: { support: "native" },
        close_coupon: { support: "native" },
        get_membership_list: { support: "native" },
        get_membership_subscription: { support: "native" },
        get_joined_membership_users: { support: "native" },
        get_number_of_followers: { support: "native" },
        get_friends_demographics: { support: "native" },
        get_number_of_message_deliveries: { support: "native" },
        get_message_event: { support: "native" },
        get_statistics_per_unit: { support: "native" },
        get_rich_menu_insight_summary: { support: "native" },
        get_rich_menu_insight_daily: { support: "native" },
        can_send_image: { support: "native" },
        can_send_record: { support: "native" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group"] },
        message_updated: { support: "native", scenes: ["group"] },
        message_deleted: { support: "native", scenes: ["private", "group"] },
        friend_add: { support: "native", scenes: ["private"] },
        user_removed: { support: "native", scenes: ["private"] },
        member_joined: { support: "native", scenes: ["group"] },
        member_left: { support: "native", scenes: ["group"] },
        interaction: { support: "native" },
        custom: {
            support: "native",
            note: "join/leave、会员、Beacon、账号绑定、视频播放完成及模块事件无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "send" },
        reply: { support: "native", direction: "both", note: "发送需 quote_token" },
        image: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        file: { support: "native", direction: "receive" },
        location: { support: "native", direction: "both" },
        sticker: { support: "native", direction: "both" },
        line_message: {
            support: "native",
            direction: "send",
            note: "承载 Flex、Template、Imagemap、Coupon、Quick Reply 等完整官方 Message",
        },
    },
    transports: {
        webhook: { support: "native", mode: "webhook" },
    },
});
