import {
    defineAdapterCapabilities,
    definePlatformActionCapabilities,
    type AdapterCapabilityManifest,
} from "onebots";
import { LINE_PLATFORM_ACTIONS } from "./platform-actions.js";

const platformActions = definePlatformActionCapabilities(LINE_PLATFORM_ACTIONS, {
    support: "native",
    availability: "context",
});

/** LINE Messaging API 与官方 SDK 11.x 的真实能力边界。 */
export const lineCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        ...platformActions,
        send_message: { support: "native", scenes: ["private", "group"] },
        delete_message: { support: "unsupported" },
        get_message: { support: "unsupported", note: "仅支持按 ID 下载媒体内容" },
        mark_message_as_read: {
            support: "native",
            scenes: ["private", "group"],
            availability: "context",
            note: "message_id 必须来自当前账号接收且包含 markAsReadToken 的事件",
        },
        get_login_info: { support: "native" },
        get_user_info: { support: "native", availability: "context" },
        get_friend_list: {
            support: "native",
            note: "Get followers 受 LINE 账号类型与审核状态限制",
        },
        get_friend_info: { support: "native", availability: "context" },
        get_group_list: { support: "emulated", note: "持久化 Webhook 中已知的 group/room" },
        get_group_info: { support: "native", availability: "context" },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native", availability: "permission" },
        get_group_member_info: { support: "native", availability: "context" },
        show_loading_animation: { support: "native", scenes: ["private"] },
        get_group_member_ids: { support: "native", availability: "permission" },
        add_audience: { support: "native", availability: "permission" },
        create_audience: { support: "native", availability: "permission" },
        create_click_audience: { support: "native", availability: "permission" },
        create_impression_audience: { support: "native", availability: "permission" },
        create_upload_audience: { support: "native", availability: "permission" },
        add_user_ids_to_audience: { support: "native", availability: "permission" },
        get_audience: { support: "native", availability: "permission" },
        list_audiences: { support: "native", availability: "permission" },
        get_shared_audience: { support: "native", availability: "permission" },
        list_shared_audiences: { support: "native", availability: "permission" },
        update_audience_description: { support: "native", availability: "permission" },
        delete_audience: { support: "native", availability: "permission" },
        create_liff_app: { support: "native", availability: "permission" },
        list_liff_apps: { support: "native", availability: "permission" },
        update_liff_app: { support: "native", availability: "permission" },
        delete_liff_app: { support: "native", availability: "permission" },
        acquire_chat_control: { support: "native", availability: "permission" },
        release_chat_control: { support: "native", availability: "permission" },
        list_modules: { support: "native", availability: "permission" },
        attach_module: { support: "native", availability: "permission" },
        detach_module: { support: "native", availability: "permission" },
        mission_sticker: { support: "native", availability: "permission" },
        get_membership_list: { support: "native" },
        get_membership_subscription: { support: "native" },
        get_joined_membership_users: { support: "native" },
        get_number_of_followers: { support: "native" },
        get_friends_demographics: { support: "native" },
        get_number_of_message_deliveries: { support: "native" },
        get_message_event: { support: "native" },
        get_statistics_per_unit: { support: "native" },
        get_rich_menu_insight_summary: { support: "native" },
        get_rich_menu_insight_daily: { support: "native" },
        can_send_image: { support: "native" },
        can_send_record: { support: "native" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group"] },
        message_updated: { support: "native", scenes: ["group"] },
        message_deleted: { support: "native", scenes: ["private", "group"] },
        friend_add: { support: "native", scenes: ["private"] },
        user_removed: { support: "native", scenes: ["private"] },
        group_increase: { support: "native", scenes: ["group"] },
        group_decrease: { support: "native", scenes: ["group"] },
        member_joined: { support: "native", scenes: ["group"] },
        member_left: { support: "native", scenes: ["group"] },
        user_updated: {
            support: "native",
            scenes: ["private"],
            note: "会员加入/续订/退出与账号绑定结果使用稳定 sub_type 投影",
        },
        message_status: {
            support: "native",
            note: "LINE notification messages 送达完成事件",
        },
        interaction: {
            support: "native",
            note: "Postback、Beacon 与视频播放完成事件使用稳定 sub_type 投影",
        },
        custom: {
            support: "native",
            note: "Module 控制、Bot suspend/resume 等无对应通用语义的生命周期事件无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "send" },
        reply: {
            support: "native",
            direction: "both",
            note: "可使用已接收消息的 message_id 自动解析 quoteToken",
        },
        image: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        file: { support: "native", direction: "receive" },
        location: { support: "native", direction: "both" },
        sticker: { support: "native", direction: "both" },
        line_message: {
            support: "native",
            direction: "send",
            note: "承载 Flex、Template、Imagemap、Coupon、Quick Reply 等完整官方 Message",
        },
    },
    transports: {
        webhook: { support: "native", mode: "webhook" },
        manual: {
            support: "native",
            mode: "native",
            note: "通过 await ingest() 接入既有 Host 并等待协议投递",
        },
    },
});
