import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

const manageMessages = {
    support: "native" as const,
    availability: "permission" as const,
    permissions: ["MANAGE_MESSAGES"],
};
const manageRoles = {
    support: "native" as const,
    availability: "permission" as const,
    permissions: ["MANAGE_ROLES"],
};
const manageThreads = {
    support: "native" as const,
    availability: "permission" as const,
    permissions: ["MANAGE_THREADS"],
};

/** Discord REST/Gateway 实现当前可用的能力。 */
export const discordCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "channel"] },
        delete_message: { support: "native", scenes: ["private", "group", "channel"] },
        get_message: { support: "native", scenes: ["private", "group", "channel"] },
        get_message_history: { support: "native", scenes: ["private", "group", "channel"] },
        get_login_info: { support: "native" },
        get_user_info: { support: "native" },
        get_friend_list: { support: "emulated", note: "返回机器人可见用户" },
        get_friend_info: { support: "emulated", note: "按 Discord 用户投影" },
        get_group_list: { support: "emulated", note: "按 Guild 投影群组" },
        get_group_info: { support: "emulated", note: "按 Guild 投影群组" },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native" },
        get_group_member_info: { support: "native" },
        kick_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["KICK_MEMBERS"],
        },
        mute_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["MODERATE_MEMBERS"],
        },
        set_group_card: { support: "native", availability: "context" },
        send_group_message_reaction: { support: "native" },
        call_discord_api: {
            support: "native",
            availability: "context",
            note: "受当前 Bot token 权限约束的完整 Discord v10 REST API 入口",
        },
        ban_member: {
            support: "native",
            availability: "permission",
            permissions: ["BAN_MEMBERS"],
        },
        unban_member: {
            support: "native",
            availability: "permission",
            permissions: ["BAN_MEMBERS"],
        },
        get_guild_bans: {
            support: "native",
            availability: "permission",
            permissions: ["BAN_MEMBERS"],
        },
        get_guild_roles: { support: "native" },
        create_guild_role: manageRoles,
        update_guild_role: manageRoles,
        delete_guild_role: manageRoles,
        add_guild_member_role: manageRoles,
        remove_guild_member_role: manageRoles,
        bulk_delete_messages: manageMessages,
        crosspost_message: {
            support: "native",
            availability: "permission",
            permissions: ["SEND_MESSAGES"],
        },
        get_channel_pins: { support: "native" },
        pin_message: {
            support: "native",
            availability: "permission",
            permissions: ["PIN_MESSAGES"],
        },
        unpin_message: {
            support: "native",
            availability: "permission",
            permissions: ["PIN_MESSAGES"],
        },
        trigger_typing: { support: "native" },
        create_thread: manageThreads,
        join_thread: { support: "native" },
        leave_thread: { support: "native" },
        add_thread_member: { support: "native" },
        remove_thread_member: manageThreads,
        list_thread_members: { support: "native" },
        get_active_threads: { support: "native" },
        get_channel_invites: {
            support: "native",
            availability: "permission",
            permissions: ["MANAGE_CHANNELS"],
        },
        create_channel_invite: {
            support: "native",
            availability: "permission",
            permissions: ["CREATE_INSTANT_INVITE"],
        },
        delete_invite: {
            support: "native",
            availability: "permission",
            permissions: ["MANAGE_CHANNELS"],
        },
        get_reaction_users: { support: "native" },
        get_guild_info: { support: "native" },
        get_guild_list: { support: "native" },
        get_guild_member_info: { support: "native" },
        get_channel_info: { support: "native" },
        get_channel_list: { support: "native" },
        create_channel: {
            support: "native",
            availability: "permission",
            permissions: ["MANAGE_CHANNELS"],
        },
        update_channel: {
            support: "native",
            availability: "permission",
            permissions: ["MANAGE_CHANNELS"],
        },
        delete_channel: {
            support: "native",
            availability: "permission",
            permissions: ["MANAGE_CHANNELS"],
        },
        get_channel_member_info: { support: "native" },
        get_channel_member_list: { support: "native" },
        kick_channel_member: {
            support: "native",
            availability: "permission",
            permissions: ["KICK_MEMBERS"],
        },
        set_channel_member_mute: {
            support: "native",
            availability: "permission",
            permissions: ["MODERATE_MEMBERS"],
        },
        can_send_image: { support: "native" },
        can_send_record: { support: "native" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "channel"] },
        group_member_increase: { support: "native", scenes: ["group"] },
        group_member_decrease: { support: "native", scenes: ["group"] },
        message_updated: { support: "native" },
        message_deleted: { support: "native" },
        reaction_added: { support: "native" },
        reaction_removed: { support: "native" },
        interaction: { support: "native" },
        native_dispatch: {
            support: "native",
            note: "所有未标准化 Gateway Dispatch 以 custom notice 和 raw_event 无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "both" },
        image: { support: "native", direction: "both" },
        file: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        embed: { support: "native", direction: "send" },
        reply: { support: "native", direction: "receive" },
        sticker: { support: "native", direction: "receive" },
    },
    transports: {
        gateway: { support: "native", mode: "websocket" },
    },
});
