import { AdapterRegistry, type Schema } from "onebots";

export { WhatsAppAdapter } from "./adapter.js";
export {
    isWhatsAppBusinessComplianceAction,
    WhatsAppBusinessCompliance,
    WHATSAPP_BUSINESS_COMPLIANCE_ACTIONS,
    WHATSAPP_BUSINESS_COMPLIANCE_FIELDS,
    WHATSAPP_BUSINESS_ENTITY_TYPES,
    type WhatsAppBusinessComplianceAction,
    type WhatsAppBusinessComplianceField,
    type WhatsAppBusinessComplianceInfo,
    type WhatsAppBusinessComplianceResponse,
    type WhatsAppBusinessComplianceUpdate,
    type WhatsAppBusinessComplianceUpdateResponse,
    type WhatsAppBusinessEntityType,
    type WhatsAppComplianceContactDetails,
    type WhatsAppComplianceContactInfo,
    type WhatsAppGrievanceOfficerDetails,
    type WhatsAppGrievanceOfficerInfo,
} from "./business-compliance.js";
export {
    isWhatsAppBusinessEncryptionAction,
    WhatsAppBusinessEncryption,
    WHATSAPP_BUSINESS_ENCRYPTION_ACTIONS,
    type WhatsAppBusinessEncryptionAction,
    type WhatsAppBusinessEncryptionInfo,
    type WhatsAppBusinessEncryptionResponse,
    type WhatsAppBusinessEncryptionUpdateResponse,
    type WhatsAppBusinessPublicKeySignatureStatus,
} from "./business-encryption.js";
export {
    isWhatsAppBusinessProfileAction,
    WhatsAppBusinessProfiles,
    WHATSAPP_BUSINESS_PROFILE_ACTIONS,
    WHATSAPP_BUSINESS_PROFILE_FIELDS,
    WHATSAPP_BUSINESS_VERTICALS,
    type WhatsAppBusinessProfile,
    type WhatsAppBusinessProfileAction,
    type WhatsAppBusinessProfileField,
    type WhatsAppBusinessProfileResponse,
    type WhatsAppBusinessProfileUpdate,
    type WhatsAppBusinessProfileUpdateResponse,
    type WhatsAppBusinessVertical,
} from "./business-profile.js";
export { whatsAppCapabilities } from "./capabilities.js";
export { WhatsAppClient } from "./client.js";
export {
    isWhatsAppCommerceAction,
    WhatsAppCommerce,
    WHATSAPP_COMMERCE_ACTIONS,
    type WhatsAppCommerceAction,
    type WhatsAppCommerceSettingsEntry,
    type WhatsAppCommerceSettingsResponse,
    type WhatsAppCommerceSettingsUpdate,
    type WhatsAppCommerceSettingsUpdateResponse,
} from "./commerce.js";
export {
    isWhatsAppQrCodeAction,
    WhatsAppQrCodes,
    WHATSAPP_QR_CODE_ACTIONS,
    WHATSAPP_QR_CODE_FIELDS,
    WHATSAPP_QR_IMAGE_FORMATS,
    type WhatsAppQrCode,
    type WhatsAppQrCodeAction,
    type WhatsAppQrCodeCreate,
    type WhatsAppQrCodeDeleteResponse,
    type WhatsAppQrCodeDetails,
    type WhatsAppQrCodeField,
    type WhatsAppQrCodeFieldSelection,
    type WhatsAppQrCodeGetResponse,
    type WhatsAppQrCodeListQuery,
    type WhatsAppQrCodeListResponse,
    type WhatsAppQrCodeMutationResponse,
    type WhatsAppQrCodePaging,
    type WhatsAppQrCodeUpdate,
    type WhatsAppQrImageFormat,
} from "./qr-codes.js";
export {
    isWhatsAppMessageTemplateAction,
    WhatsAppMessageTemplates,
    WHATSAPP_MESSAGE_TEMPLATE_ACTIONS,
    type WhatsAppMessageTemplateAction,
} from "./message-templates.js";
export {
    isWhatsAppMessageTemplateCategory,
    isWhatsAppMessageTemplateField,
    isWhatsAppMessageTemplateParameterFormat,
    isWhatsAppMessageTemplateStatus,
    WHATSAPP_MESSAGE_TEMPLATE_CATEGORIES,
    WHATSAPP_MESSAGE_TEMPLATE_FIELDS,
    WHATSAPP_MESSAGE_TEMPLATE_PARAMETER_FORMATS,
    WHATSAPP_MESSAGE_TEMPLATE_STATUSES,
    type WhatsAppMessageTemplate,
    type WhatsAppMessageTemplateCategory,
    type WhatsAppMessageTemplateComponent,
    type WhatsAppMessageTemplateCreate,
    type WhatsAppMessageTemplateCreateResponse,
    type WhatsAppMessageTemplateDetails,
    type WhatsAppMessageTemplateField,
    type WhatsAppMessageTemplateFieldSelection,
    type WhatsAppMessageTemplateListQuery,
    type WhatsAppMessageTemplateListFullResponse,
    type WhatsAppMessageTemplateListResponse,
    type WhatsAppMessageTemplateNamespaceResponse,
    type WhatsAppMessageTemplatePaging,
    type WhatsAppMessageTemplateParameterFormat,
    type WhatsAppMessageTemplateStatus,
    type WhatsAppMessageTemplateSuccessResponse,
    type WhatsAppMessageTemplateUpdate,
    type WhatsAppTemplateJson,
} from "./message-template-types.js";
export {
    isWhatsAppFlowAction,
    WhatsAppFlows,
    WHATSAPP_FLOW_ACTIONS,
    type WhatsAppFlowAction,
} from "./flows.js";
export {
    isWhatsAppFlowCategory,
    isWhatsAppFlowField,
    isWhatsAppFlowMetricGranularity,
    isWhatsAppFlowMetricName,
    isWhatsAppFlowStatus,
    WHATSAPP_FLOW_CATEGORIES,
    WHATSAPP_FLOW_FIELDS,
    WHATSAPP_FLOW_METRICS,
    WHATSAPP_FLOW_METRIC_GRANULARITIES,
    WHATSAPP_FLOW_STATUSES,
    type WhatsAppFlowAsset,
    type WhatsAppFlowAssetListResponse,
    type WhatsAppFlowCategory,
    type WhatsAppFlowCreate,
    type WhatsAppFlowCreateResponse,
    type WhatsAppFlowDetails,
    type WhatsAppFlowField,
    type WhatsAppFlowGraphNode,
    type WhatsAppFlowHealthEntity,
    type WhatsAppFlowHealthError,
    type WhatsAppFlowHealthStatus,
    type WhatsAppFlowJson,
    type WhatsAppFlowJsonUploadResponse,
    type WhatsAppFlowListResponse,
    type WhatsAppFlowMetricGranularity,
    type WhatsAppFlowMetricName,
    type WhatsAppFlowMetricQuery,
    type WhatsAppFlowMetricResponse,
    type WhatsAppFlowMigrationRequest,
    type WhatsAppFlowMigrationResponse,
    type WhatsAppFlowPaging,
    type WhatsAppFlowPreview,
    type WhatsAppFlowStatus,
    type WhatsAppFlowSuccessResponse,
    type WhatsAppFlowSummary,
    type WhatsAppFlowUpdate,
    type WhatsAppFlowValidationError,
} from "./flow-types.js";
export {
    isWhatsAppBlockedUserAction,
    WhatsAppBlockedUsers,
    WHATSAPP_BLOCKED_USER_ACTIONS,
    type WhatsAppBlockedUser,
    type WhatsAppBlockedUserAction,
    type WhatsAppBlockedUserListQuery,
    type WhatsAppBlockedUserListResponse,
    type WhatsAppBlockedUserOperation,
    type WhatsAppBlockedUserPaging,
    type WhatsAppBlockUsersResponse,
    type WhatsAppUnblockUsersResponse,
} from "./blocked-users.js";
export {
    isWhatsAppMediaAction,
    isWhatsAppMediaMimeType,
    WhatsAppMedia,
    WHATSAPP_MEDIA_ACTIONS,
    WHATSAPP_MEDIA_LIMITS,
    type WhatsAppMediaAction,
    type WhatsAppMediaDeleteResponse,
    type WhatsAppMediaDownload,
    type WhatsAppMediaInfo,
    type WhatsAppMediaMimeType,
    type WhatsAppMediaUploadResponse,
} from "./media.js";
export {
    isWhatsAppConversationalAutomationAction,
    WhatsAppConversationalAutomation,
    WHATSAPP_BUSINESS_BOT_FIELDS,
    WHATSAPP_CONVERSATIONAL_AUTOMATION_ACTIONS,
    type WhatsAppBusinessBot,
    type WhatsAppBusinessBotCommand,
    type WhatsAppBusinessBotField,
    type WhatsAppConversationalAutomationAction,
    type WhatsAppConversationalAutomationResponse,
    type WhatsAppConversationalAutomationSettings,
} from "./conversational-automation.js";
export {
    isWhatsAppWebhookSubscriptionAction,
    WhatsAppWebhookSubscriptions,
    WHATSAPP_SUBSCRIBED_APP_FIELDS,
    WHATSAPP_WEBHOOK_SUBSCRIPTION_ACTIONS,
    type WhatsAppSubscribedAppData,
    type WhatsAppSubscribedAppField,
    type WhatsAppWebhookSubscription,
    type WhatsAppWebhookSubscriptionAction,
    type WhatsAppWebhookSubscriptionMutationResponse,
    type WhatsAppWebhookSubscriptionRequest,
    type WhatsAppWebhookSubscriptionsResponse,
} from "./webhook-subscriptions.js";
export {
    isWhatsAppSolutionMigrationAction,
    WhatsAppSolutionMigration,
    WHATSAPP_MIGRATION_INTENT_FIELDS,
    WHATSAPP_MIGRATION_STATUSES,
    WHATSAPP_SOLUTION_MIGRATION_ACTIONS,
    WHATSAPP_SOLUTION_MIGRATION_INTENTS,
    WHATSAPP_SOLUTION_MIGRATION_REQUEST_STATUSES,
    type WhatsAppMigrationIntent,
    type WhatsAppMigrationIntentField,
    type WhatsAppMigrationStatus,
    type WhatsAppSolutionMigrationAction,
    type WhatsAppSolutionMigrationIntent,
    type WhatsAppSolutionMigrationRequest,
    type WhatsAppSolutionMigrationRequestStatus,
    type WhatsAppSolutionMigrationResponse,
} from "./solution-migration.js";
export {
    isWhatsAppCallingAction,
    WhatsAppCalling,
    WHATSAPP_CALLING_ACTIONS,
    type WhatsAppCallingAction,
} from "./calling.js";
export { WhatsAppApiError, type WhatsAppApiErrorOptions } from "./errors.js";
export {
    isWhatsAppEncryptedMessageAction,
    WhatsAppEncryptedMessages,
    WHATSAPP_ENCRYPTED_MESSAGE_ACTIONS,
    type WhatsAppEncryptedMessageAction,
    type WhatsAppEncryptedMessageResponse,
} from "./encrypted-messages.js";
export {
    isWhatsAppPhoneNumberAction,
    WhatsAppPhoneNumbers,
    WHATSAPP_PHONE_NUMBER_ACTIONS,
    type WhatsAppPhoneNumberAction,
    type WhatsAppPhoneNumberRegistration,
    type WhatsAppSuccessResponse,
    type WhatsAppVerificationCodeMethod,
    type WhatsAppVerificationCodeRequest,
    type WhatsAppVerificationCodeResponse,
} from "./phone-numbers.js";
export {
    isWhatsAppHistoryAction,
    WhatsAppHistory,
    WHATSAPP_HISTORY_ACTIONS,
    type WhatsAppHistoryAction,
} from "./history.js";
export { projectMessageContent, projectWhatsAppWebhook } from "./events.js";
export {
    isWhatsAppSettingsAction,
    WhatsAppSettings,
    WHATSAPP_SETTINGS_ACTIONS,
    type WhatsAppSettingsAction,
} from "./settings.js";
export { isWhatsAppGroupWebhookEntry } from "./group-webhook.js";
export { compileWhatsAppMessages } from "./messages.js";
export {
    isWhatsAppGroupAction,
    WhatsAppGroups,
    WHATSAPP_GROUP_ACTIONS,
    type WhatsAppGroupAction,
} from "./groups.js";
export {
    executeWhatsAppPlatformAction,
    WHATSAPP_PLATFORM_ACTIONS,
    type WhatsAppPlatformAction,
} from "./platform-actions.js";
export { WhatsAppWebhookHost } from "./webhook-host.js";
export {
    routeWhatsAppWebhook,
    WhatsAppWebhookRouter,
    type WhatsAppWebhookDelivery,
} from "./webhook-routing.js";
export type { WhatsAppHttpContext } from "./webhook-host.js";
export type {
    WhatsAppCallIconVisibility,
    WhatsAppCallingSettings,
    WhatsAppCallingSettingsUpdate,
    WhatsAppFeatureStatus,
    WhatsAppPayloadEncryptionSettings,
    WhatsAppPayloadEncryptionUpdate,
    WhatsAppPhoneNumberSettings,
    WhatsAppSettingsUpdateResponse,
    WhatsAppSipServer,
    WhatsAppSrtpProtocol,
    WhatsAppStorageConfigurationSettings,
    WhatsAppStorageConfigurationUpdate,
} from "./settings-types.js";
export type {
    WhatsAppHistoryDeliveryStatus,
    WhatsAppHistoryEvent,
    WhatsAppHistoryEventEdge,
    WhatsAppHistoryEventOccurrence,
    WhatsAppHistoryEventsQuery,
    WhatsAppHistoryEventsResponse,
    WhatsAppHistoryPaging,
    WhatsAppMessageHistoryEntry,
    WhatsAppMessageHistoryQuery,
    WhatsAppMessageHistoryResponse,
    WhatsAppWebhookUpdateState,
} from "./history-types.js";
export type {
    WhatsAppCallConnectParams,
    WhatsAppCallManageParams,
    WhatsAppCallPermissionAction,
    WhatsAppCallPermissionActionName,
    WhatsAppCallPermissionLimit,
    WhatsAppCallPermissionResponse,
    WhatsAppCallPermissionStatus,
    WhatsAppCallResponse,
    WhatsAppCallSession,
    WhatsAppCallTerminateResponse,
} from "./calling-types.js";
export type {
    WhatsAppAPIResponse,
    WhatsAppCallOptions,
    WhatsAppClientEvents,
    WhatsAppConfig,
    WhatsAppContact,
    WhatsAppErrorData,
    WhatsAppGroupCreateParams,
    WhatsAppGroupDetails,
    WhatsAppGroupIdentityFields,
    WhatsAppGroupInviteLinkDeletedResponse,
    WhatsAppGroupInviteLinkResponse,
    WhatsAppGroupJoinRequest,
    WhatsAppGroupJoinRequestActionResponse,
    WhatsAppGroupJoinRequestCreatedEntry,
    WhatsAppGroupJoinRequestRevokedEntry,
    WhatsAppGroupJoinRequestsResponse,
    WhatsAppGroupLifecycleEntry,
    WhatsAppGroupListResponse,
    WhatsAppGroupOperationResponse,
    WhatsAppGroupPagination,
    WhatsAppGroupParticipant,
    WhatsAppGroupParticipantsAddedEntry,
    WhatsAppGroupParticipantsEntry,
    WhatsAppGroupParticipantsRemovedEntry,
    WhatsAppGroupSettingResult,
    WhatsAppGroupSettingsEntry,
    WhatsAppGroupStatusEntry,
    WhatsAppGroupSuccessResponse,
    WhatsAppGroupSummary,
    WhatsAppGroupUpdateParams,
    WhatsAppGroupWebhookEntry,
    WhatsAppGroupWebhookError,
    WhatsAppMediaObject,
    WhatsAppIngestResult,
    WhatsAppMessageEvent,
    WhatsAppMessageStatus,
    WhatsAppMessageStatusEvent,
    WhatsAppMessageType,
    WhatsAppObservedContact,
    WhatsAppPaging,
    WhatsAppPhoneNumberInfo,
    WhatsAppSendMessageParams,
    WhatsAppWebhookChange,
    WhatsAppWebhookContact,
    WhatsAppWebhookEvent,
    WhatsAppWebhookMetadata,
    WhatsAppWebhookRequest,
    WhatsAppWebhookResponse,
    WhatsAppWebhookValue,
    WhatsAppVerifiedWebhook,
} from "./types.js";

export const whatsappSchema: Schema = {
    account_id: {
        type: "string",
        required: true,
        label: "账号标识",
        description: "OneBots 内部区分 WhatsApp 号码的稳定标识",
        ui: { section: "credentials" },
    },
    phone_number_id: {
        type: "string",
        required: true,
        label: "Phone Number ID",
        description: "WhatsApp > API Setup 中的 Phone Number ID",
        ui: { section: "credentials" },
    },
    business_account_id: {
        type: "string",
        required: true,
        label: "Business Account ID",
        description: "WhatsApp Business Account ID，用于模板等管理 API",
        ui: { section: "credentials" },
    },
    access_token: {
        type: "string",
        required: true,
        label: "Access Token",
        sensitive: true,
        description: "建议使用系统用户生成的长期访问令牌",
        ui: { section: "credentials" },
    },
    app_secret: {
        type: "string",
        label: "App Secret",
        sensitive: true,
        description: "使用 ingestHttp()/acceptHttp() 时用于校验 X-Hub-Signature-256",
        ui: {
            section: "credentials",
            visibleWhen: { path: "receive_mode", oneOf: ["webhook", "manual"] },
        },
    },
    receive_mode: {
        type: "string",
        default: "webhook",
        label: "事件接收方式",
        choices: [
            { value: "webhook", label: "Webhook" },
            { value: "manual", label: "手动接入既有 Host/队列" },
        ],
        description: "manual 不注册路由，由现有 Host 调用 ingest()/ingestHttp()/acceptHttp()",
        ui: { section: "transport" },
    },
    webhook_verify_token: {
        type: "string",
        label: "Webhook Verify Token",
        sensitive: true,
        description: "acceptHttp() 处理 Meta GET 验证时使用，须与控制台配置一致",
        ui: {
            section: "transport",
            visibleWhen: { path: "receive_mode", oneOf: ["webhook", "manual"] },
        },
    },
    webhook_path: {
        type: "string",
        label: "Webhook 路径",
        placeholder: "/whatsapp/{account_id}/webhook",
        description: "复用 OneBots 主 HTTP 服务；留空自动生成账号隔离路径",
        pattern: /^\/(?!\/)[^?#\u0000-\u001f\u007f]*$/,
        ui: {
            section: "transport",
            visibleWhen: { path: "receive_mode", oneOf: ["webhook"] },
        },
    },
    api_version: {
        type: "string",
        required: true,
        label: "Graph API 版本",
        description: "按 Meta 应用当前已启用的版本填写，例如 v23.0，避免隐式版本漂移",
        ui: { section: "advanced" },
    },
    api_base_url: {
        type: "string",
        default: "https://graph.facebook.com",
        label: "Graph API Base URL",
        description: "仅官方兼容代理或测试环境需要覆盖，必须使用 HTTPS",
        pattern: /^https:\/\/[^\s/?#]+(?::\d+)?\/?$/,
        ui: { section: "advanced" },
    },
    deduplicate_webhooks: {
        type: "boolean",
        default: true,
        label: "过滤重复 Webhook",
        description: "按原始负载哈希过滤 Meta 重投递",
        ui: { section: "delivery" },
    },
    webhook_deduplication_limit: {
        type: "number",
        default: 10000,
        label: "去重缓存上限",
        description: "进程内保留的最近 Webhook 哈希数量，最低 100",
        ui: { section: "advanced" },
    },
};

AdapterRegistry.registerSchema("whatsapp", whatsappSchema);
