import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

/** ICQQ 已通过通用 Adapter seam 暴露的原生能力。 */
export const icqqCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "channel"] },
        delete_message: { support: "native", scenes: ["private", "group"] },
        get_message: { support: "native", scenes: ["private", "group"] },
        get_message_history: { support: "native", scenes: ["private", "group"] },
        get_forward_message: { support: "native" },
        mark_message_as_read: { support: "native", scenes: ["private", "group"] },
        get_login_info: { support: "native" },
        get_user_info: { support: "native" },
        get_friend_list: { support: "native" },
        get_friend_info: { support: "native" },
        delete_friend: { support: "native" },
        send_friend_nudge: { support: "native" },
        send_like: { support: "native" },
        get_friend_requests: { support: "native" },
        handle_friend_request: { support: "native" },
        get_group_list: { support: "native" },
        get_group_info: { support: "native" },
        set_group_name: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native" },
        get_group_member_info: { support: "native" },
        kick_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        invite_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["group.invite"],
        },
        mute_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        mute_group_all: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        mute_group_anonymous: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        set_group_anonymous: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        set_group_admin: {
            support: "native",
            availability: "permission",
            permissions: ["group.owner"],
        },
        set_group_card: {
            support: "native",
            availability: "permission",
            permissions: ["group.member"],
        },
        set_group_special_title: {
            support: "native",
            availability: "permission",
            permissions: ["group.owner"],
        },
        send_group_nudge: { support: "native", scenes: ["group"] },
        handle_group_request: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        get_group_notifications: { support: "native" },
        set_group_avatar: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        send_group_message_reaction: { support: "native", scenes: ["group"] },
        send_group_announcement: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        set_group_essence_message: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        delete_group_essence_message: {
            support: "native",
            availability: "permission",
            permissions: ["group.admin"],
        },
        get_guild_info: { support: "native" },
        get_guild_list: { support: "native" },
        get_guild_member_info: { support: "native" },
        get_guild_member_list: { support: "native" },
        get_channel_info: { support: "native" },
        get_channel_list: { support: "native" },
        upload_file: { support: "native", scenes: ["private", "group"] },
        delete_file: { support: "native", scenes: ["private", "group"] },
        get_group_files: { support: "native", scenes: ["group"] },
        create_group_folder: {
            support: "native",
            availability: "permission",
            permissions: ["group.file"],
        },
        get_file_download_url: { support: "native", scenes: ["private", "group"] },
        move_group_file: {
            support: "native",
            availability: "permission",
            permissions: ["group.file"],
        },
        rename_group_file: {
            support: "native",
            availability: "permission",
            permissions: ["group.file"],
        },
        rename_group_folder: {
            support: "native",
            availability: "permission",
            permissions: ["group.file"],
        },
        delete_group_folder: {
            support: "native",
            availability: "permission",
            permissions: ["group.file"],
        },
        can_send_image: { support: "native" },
        can_send_record: { support: "native" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
        get_cookies: { support: "native" },
        get_csrf_token: { support: "native" },
        get_credentials: { support: "native" },
        clean_cache: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group"] },
        friend_request: { support: "native" },
        group_request: { support: "native", scenes: ["group"] },
        group_member_increase: { support: "native", scenes: ["group"] },
        group_member_decrease: { support: "native", scenes: ["group"] },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "both" },
        face: { support: "native", direction: "both" },
        image: { support: "native", direction: "both" },
        record: { support: "native", direction: "both" },
        audio: { support: "native", direction: "send" },
        video: { support: "native", direction: "both" },
        reply: { support: "native", direction: "both" },
        share: { support: "native", direction: "both" },
        json: { support: "native", direction: "both" },
        xml: { support: "native", direction: "both" },
    },
    transports: {
        native: { support: "native", mode: "native" },
    },
});
