import { defineAdapterCapabilities, type AdapterCapabilityManifest } from "onebots";

/** 飞书开放平台实现当前可用的能力。 */
export const feishuCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "channel"] },
        delete_message: { support: "native" },
        get_message: { support: "native" },
        update_message: { support: "native" },
        get_login_info: { support: "native" },
        get_user_info: { support: "native" },
        get_friend_list: {
            support: "native",
            availability: "permission",
            permissions: ["contact:user.base:readonly"],
            note: "按应用可见的通讯录用户投影",
        },
        get_friend_info: { support: "emulated", note: "按通讯录用户投影" },
        get_group_list: { support: "native" },
        get_group_info: { support: "native" },
        set_group_name: { support: "native", availability: "permission" },
        leave_group: { support: "native" },
        get_group_member_list: { support: "native" },
        get_group_member_info: { support: "native" },
        kick_group_member: {
            support: "native",
            availability: "permission",
            permissions: ["im:chat.members:write_only"],
        },
        call_feishu_api: {
            support: "native",
            availability: "context",
            note: "受 tenant token 权限约束的飞书/Lark 开放平台原生入口",
        },
        reply_message: { support: "native", permissions: ["im:message"] },
        forward_message: { support: "native", permissions: ["im:message"] },
        add_reaction: { support: "native", availability: "permission" },
        delete_reaction: { support: "native", availability: "permission" },
        get_reactions: { support: "native", availability: "permission" },
        create_chat: { support: "native", availability: "permission" },
        update_chat: { support: "native", availability: "permission" },
        delete_chat: { support: "native", availability: "permission" },
        add_chat_members: { support: "native", availability: "permission" },
        remove_chat_members: { support: "native", availability: "permission" },
        send_app_urgent: { support: "native", availability: "permission" },
        send_sms_urgent: { support: "native", availability: "permission" },
        send_phone_urgent: { support: "native", availability: "permission" },
        create_pin: { support: "native", availability: "permission" },
        delete_pin: { support: "native", availability: "permission" },
        get_pin_list: { support: "native", availability: "permission" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "channel"] },
        message_deleted: { support: "native" },
        member_joined: { support: "native" },
        member_left: { support: "native" },
        native_event: {
            support: "native",
            note: "未标准化事件以 custom notice 和 raw_event 无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "both" },
        image: { support: "native", direction: "both" },
        file: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        post: { support: "native", direction: "both" },
        interactive: { support: "native", direction: "both" },
        reply: { support: "native", direction: "both" },
        sticker: { support: "native", direction: "both" },
    },
    transports: {
        webhook: { support: "native", mode: "webhook" },
        long_connection: { support: "native", mode: "websocket" },
    },
});
