import type { IncomingMessage } from "node:http";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { TokenManager, type RouterContext } from "@onebots/core";
import type { App } from "../app.js";
import { registerAuthRoutes } from "./auth.js";

type Handler = (ctx: RouterContext, next: () => Promise<void>) => void | Promise<void>;

function setup() {
    const posts = new Map<string, Handler>();
    const uses: Handler[] = [];
    const router = {
        post: vi.fn((path: string, handler: Handler) => posts.set(path, handler)),
        get: vi.fn(),
        use: vi.fn((_path: string, handler: Handler) => uses.push(handler)),
    };
    const app = {
        config: {
            username: "old-user",
            password: "old-password",
            access_token: "old-token",
        },
        tokenManager: new TokenManager(),
        credentialsWereAutoGenerated: false,
    } as unknown as App;
    registerAuthRoutes(app, router as never);
    return {
        app,
        login: posts.get("/api/auth/login")!,
        refresh: posts.get("/api/auth/refresh")!,
        middleware: uses[0],
    };
}

function loginContext(body: Record<string, unknown>): RouterContext {
    return { request: { body }, set: vi.fn() } as unknown as RouterContext;
}

function apiContext(token?: string): RouterContext {
    const req = {
        url: "/api/config",
        headers: token ? { authorization: `Bearer ${token}` } : {},
    } as IncomingMessage;
    return {
        path: "/api/config",
        method: "GET",
        ip: "127.0.0.1",
        req,
        request: { body: {}, ip: "127.0.0.1" },
        state: {},
        get: () => "",
        set: vi.fn(),
    } as unknown as RouterContext;
}

describe("management HTTP authentication", () => {
    beforeEach(() => vi.stubEnv("ONEBOTS_ACCESS_TOKEN", ""));
    afterEach(() => vi.unstubAllEnvs());

    it("登录处理器在配置热重载后立即使用新凭据", async () => {
        const { app, login } = setup();
        const oldLogin = loginContext({ username: "old-user", password: "old-password" });
        await login(oldLogin, async () => undefined);
        expect(oldLogin.body).toMatchObject({ success: true });

        app.config.username = "new-user";
        app.config.password = "new-password";
        app.config.access_token = "new-token";

        const rejected = loginContext({ username: "old-user", password: "old-password" });
        await login(rejected, async () => undefined);
        expect(rejected.status).toBe(401);

        const passwordLogin = loginContext({
            username: "new-user",
            password: "new-password",
        });
        await login(passwordLogin, async () => undefined);
        expect(passwordLogin.body).toMatchObject({ success: true });

        const tokenLogin = loginContext({ access_token: "new-token" });
        await login(tokenLogin, async () => undefined);
        expect(tokenLogin.body).toMatchObject({ success: true, token: "new-token" });
    });

    it("API 中间件同时接受当前配置 token 与有效会话 token", async () => {
        const { app, middleware } = setup();
        const session = app.tokenManager.generateToken({ username: "old-user" });
        const next = vi.fn(async () => undefined);

        await middleware(apiContext("old-token"), next);
        await middleware(apiContext(session.token), next);
        expect(next).toHaveBeenCalledTimes(2);

        const rejected = apiContext("wrong-token");
        await middleware(rejected, next);
        expect(rejected.status).toBe(401);
        expect(rejected.body).toEqual({ error: "Unauthorized", message: "Unauthorized" });
        expect(next).toHaveBeenCalledTimes(2);
    });

    it("为凭据签发、鉴权失败和受保护 API 统一禁止缓存", async () => {
        const { login, refresh, middleware } = setup();
        const loginCtx = loginContext({ username: "old-user", password: "old-password" });
        const refreshCtx = loginContext({ refreshToken: "invalid" });
        const protectedCtx = apiContext("old-token");
        const rejectedCtx = apiContext("wrong-token");

        await login(loginCtx, async () => undefined);
        await refresh(refreshCtx, async () => undefined);
        await middleware(protectedCtx, async () => undefined);
        await middleware(rejectedCtx, async () => undefined);

        for (const ctx of [loginCtx, refreshCtx, protectedCtx, rejectedCtx]) {
            expect(ctx.set).toHaveBeenCalledWith("Cache-Control", "no-store");
        }
        expect(refreshCtx.status).toBe(401);
        expect(rejectedCtx.status).toBe(401);
    });
});
