import type { IncomingMessage } from "node:http";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { TokenManager, type RouterContext } from "@onebots/core";
import type { App } from "../app.js";
import { MANAGEMENT_LOGIN_FAILURE_LIMIT, registerAuthRoutes } from "./auth.js";

type Handler = (ctx: RouterContext, next: () => Promise<void>) => void | Promise<void>;

function setup() {
    const posts = new Map<string, Handler>();
    const uses: Handler[] = [];
    const router = {
        post: vi.fn((path: string, handler: Handler) => posts.set(path, handler)),
        get: vi.fn(),
        use: vi.fn((_path: string, handler: Handler) => uses.push(handler)),
    };
    const app = {
        config: {
            username: "old-user",
            password: "old-password",
            access_token: "old-token",
        },
        tokenManager: new TokenManager(),
        credentialsWereAutoGenerated: false,
        runtimeContractId: "sha256:contract-current",
        info: {
            application_name: "onebots",
            application_version: "1.2.8",
            instance_id: "instance-current",
        },
        logger: { error: vi.fn() },
        lifecycle: { register: vi.fn() },
    } as unknown as App;
    registerAuthRoutes(app, router as never);
    return {
        app,
        login: posts.get("/api/auth/login")!,
        refresh: posts.get("/api/auth/refresh")!,
        middleware: uses[0],
    };
}

function loginContext(body: Record<string, unknown>): RouterContext {
    return {
        ip: "127.0.0.1",
        method: "POST",
        path: "/api/auth/login",
        request: { body, ip: "127.0.0.1" },
        get: () => "",
        set: vi.fn(),
    } as unknown as RouterContext;
}

function apiContext(token?: string, url = "/api/config"): RouterContext {
    const req = {
        url,
        headers: token ? { authorization: `Bearer ${token}` } : {},
    } as IncomingMessage;
    return {
        path: "/api/config",
        method: "GET",
        ip: "127.0.0.1",
        req,
        request: { body: {}, ip: "127.0.0.1" },
        state: {},
        get: () => "",
        set: vi.fn(),
    } as unknown as RouterContext;
}

describe("management HTTP authentication", () => {
    beforeEach(() => vi.stubEnv("ONEBOTS_ACCESS_TOKEN", ""));
    afterEach(() => {
        vi.useRealTimers();
        vi.unstubAllEnvs();
    });

    it("登录处理器在配置热重载后立即使用新凭据", async () => {
        const { app, login } = setup();
        const oldLogin = loginContext({ username: "old-user", password: "old-password" });
        await login(oldLogin, async () => undefined);
        expect(oldLogin.body).toMatchObject({ success: true });

        app.config.username = "new-user";
        app.config.password = "new-password";
        app.config.access_token = "new-token";

        const rejected = loginContext({ username: "old-user", password: "old-password" });
        await login(rejected, async () => undefined);
        expect(rejected.status).toBe(401);

        const passwordLogin = loginContext({
            username: "new-user",
            password: "new-password",
        });
        await login(passwordLogin, async () => undefined);
        expect(passwordLogin.body).toMatchObject({ success: true });

        const tokenLogin = loginContext({ access_token: "new-token" });
        await login(tokenLogin, async () => undefined);
        expect(tokenLogin.body).toMatchObject({ success: true, token: "new-token" });
    });

    it("只按来源限制失败登录，并返回可重试时间", async () => {
        const { login } = setup();

        for (let attempt = 0; attempt < MANAGEMENT_LOGIN_FAILURE_LIMIT; attempt++) {
            const rejected = loginContext({ access_token: "wrong-token" });
            await login(rejected, async () => undefined);
            expect(rejected.status).toBe(401);
        }

        const limited = loginContext({ access_token: "old-token" });
        await login(limited, async () => undefined);
        expect(limited.status).toBe(429);
        expect(limited.body).toMatchObject({
            error: "RateLimitExceeded",
            message: "登录失败次数过多，请稍后再试",
            retryAfter: expect.any(Number),
        });
        expect(limited.set).toHaveBeenCalledWith("Retry-After", expect.any(String));

        const otherSource = loginContext({ access_token: "old-token" });
        otherSource.ip = "127.0.0.2";
        otherSource.request.ip = "127.0.0.2";
        await login(otherSource, async () => undefined);
        expect(otherSource.status).not.toBe(429);
        expect(otherSource.body).toMatchObject({ success: true });
    });

    it("成功登录和实例切换拒绝不消耗失败凭据预算", async () => {
        const { login } = setup();

        for (let attempt = 0; attempt < MANAGEMENT_LOGIN_FAILURE_LIMIT + 1; attempt++) {
            const stale = loginContext({ access_token: "old-token" });
            stale.get = () => "instance-before-restart";
            await login(stale, async () => undefined);
            expect(stale.status).toBe(409);
        }
        for (let attempt = 0; attempt < MANAGEMENT_LOGIN_FAILURE_LIMIT + 1; attempt++) {
            const accepted = loginContext({ access_token: "old-token" });
            await login(accepted, async () => undefined);
            expect(accepted.status).not.toBe(429);
            expect(accepted.body).toMatchObject({ success: true });
        }
    });

    it("登录和刷新响应发布当前 OneBots 实例身份", async () => {
        const { app, login, refresh } = setup();
        const loginCtx = loginContext({ username: "old-user", password: "old-password" });
        await login(loginCtx, async () => undefined);
        const session = loginCtx.body as { refreshToken: string };
        const refreshCtx = loginContext({ refreshToken: session.refreshToken });

        await refresh(refreshCtx, async () => undefined);

        for (const ctx of [loginCtx, refreshCtx]) {
            expect(ctx.set).toHaveBeenCalledWith("X-OneBots-Application", "onebots");
            expect(ctx.set).toHaveBeenCalledWith("X-OneBots-Version", "1.2.8");
            expect(ctx.set).toHaveBeenCalledWith("X-OneBots-Instance-Id", "instance-current");
            expect(ctx.set).toHaveBeenCalledWith(
                "X-OneBots-Runtime-Contract-Id",
                "sha256:contract-current",
            );
        }
        expect(app.logger.error).not.toHaveBeenCalled();
    });

    it("访问令牌自然过期后仍可在刷新窗口内续期", async () => {
        vi.useFakeTimers();
        vi.setSystemTime(new Date("2026-01-01T00:00:00.000Z"));
        const { app, login, refresh } = setup();
        app.tokenManager = new TokenManager({
            defaultExpiration: 1_000,
            refreshExpiration: 10_000,
        });
        const loginCtx = loginContext({ username: "old-user", password: "old-password" });
        await login(loginCtx, async () => undefined);
        const session = loginCtx.body as { token: string; refreshToken: string };

        vi.advanceTimersByTime(1_001);
        expect(app.tokenManager.validateToken(session.token).expired).toBe(true);
        const refreshCtx = loginContext({ refreshToken: session.refreshToken });
        await refresh(refreshCtx, async () => undefined);

        expect(refreshCtx.status).not.toBe(401);
        expect(refreshCtx.body).toMatchObject({ success: true, token: expect.any(String) });
    });

    it.each([
        ["登录", "login"],
        ["令牌刷新", "refresh"],
    ] as const)("实例切换后在读取凭据前拒绝%s请求", async (operation, route) => {
        const { app, login, refresh } = setup();
        const ctx = {
            ...loginContext(
                route === "login"
                    ? { access_token: "old-token" }
                    : { refreshToken: "refresh-secret" },
            ),
            get: () => "instance-before-restart",
        } as unknown as RouterContext;

        await (route === "login" ? login : refresh)(ctx, async () => undefined);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toEqual({
            success: false,
            application: "onebots",
            instance_id: "instance-current",
            code: "AUTH_INSTANCE_MISMATCH",
            message: `${operation}请求期望实例 instance-before-restart，当前已由实例 instance-current 接管`,
        });
        expect(app.logger.error).toHaveBeenCalledWith(`管理端${operation}实例验证失败`, {
            error: expect.objectContaining({ name: "ManagementInstanceMismatchError" }),
        });
    });

    it("API 中间件同时接受当前配置 token 与有效会话 token", async () => {
        const { app, middleware } = setup();
        const session = app.tokenManager.generateToken({ username: "old-user" });
        const next = vi.fn(async () => undefined);

        await middleware(apiContext("old-token"), next);
        await middleware(apiContext(session.token), next);
        expect(next).toHaveBeenCalledTimes(2);

        const rejected = apiContext("wrong-token");
        await middleware(rejected, next);
        expect(rejected.status).toBe(401);
        expect(rejected.body).toEqual({ error: "Unauthorized", message: "Unauthorized" });
        expect(next).toHaveBeenCalledTimes(2);
    });

    it("普通管理 HTTP 拒绝查询参数令牌", async () => {
        const { middleware } = setup();
        const next = vi.fn(async () => undefined);
        const queryToken = apiContext(undefined, "/api/config?access_token=old-token");

        await middleware(queryToken, next);

        expect(queryToken.status).toBe(401);
        expect(next).not.toHaveBeenCalled();
    });

    it("为凭据签发、鉴权失败和受保护 API 统一禁止缓存", async () => {
        const { login, refresh, middleware } = setup();
        const loginCtx = loginContext({ username: "old-user", password: "old-password" });
        const refreshCtx = loginContext({ refreshToken: "invalid" });
        const protectedCtx = apiContext("old-token");
        const rejectedCtx = apiContext("wrong-token");

        await login(loginCtx, async () => undefined);
        await refresh(refreshCtx, async () => undefined);
        await middleware(protectedCtx, async () => undefined);
        await middleware(rejectedCtx, async () => undefined);

        for (const ctx of [loginCtx, refreshCtx, protectedCtx, rejectedCtx]) {
            expect(ctx.set).toHaveBeenCalledWith("Cache-Control", "no-store");
        }
        expect(refreshCtx.status).toBe(401);
        expect(rejectedCtx.status).toBe(401);
    });
});
