import { RouterContext, logInvalidToken } from "@onebots/core";
import type { App } from "../app.js";
import type { Router } from "@onebots/core";
import {
    extractManagementToken,
    managementAccessTokenMatches,
    managementCredentialsMatch,
    validateManagementToken,
} from "../management-auth.js";

/**
 * Register authentication-related routes.
 *
 * Computes auth state from app.config rather than relying on start() closure variables.
 * The middleware registered here protects all /api/* routes except login and refresh.
 *
 * A note on the access token: ONEBOTS_ACCESS_TOKEN is a deployment-level override,
 * followed by config.access_token. The access token path skips the per-session token
 * manager and is validated by direct comparison.  The username/password path generates
 * managed tokens via app.tokenManager.
 */
export function registerAuthRoutes(app: App, router: Router): void {
    /* ── routes ────────────────────────────────────────────────── */

    router.post("/api/auth/login", (ctx: RouterContext) => {
        disableManagementCaching(ctx);
        const body = ctx.request.body as {
            username?: string;
            password?: string;
            access_token?: string;
        };

        // 鉴权码登录
        if (body.access_token != null && body.access_token !== "") {
            if (managementAccessTokenMatches(app.config, body.access_token)) {
                ctx.body = {
                    success: true,
                    token: body.access_token,
                    expiresAt: null,
                    refreshToken: null,
                    isDefaultCredentials: false,
                };
                return;
            }
            ctx.status = 401;
            ctx.body = { success: false, message: "鉴权码错误" };
            return;
        }

        if (!managementCredentialsMatch(app.config, body.username, body.password)) {
            ctx.status = 401;
            ctx.body = { success: false, message: "用户名或密码错误" };
            return;
        }

        const tokenInfo = app.tokenManager.generateToken({ username: body.username });
        ctx.body = {
            success: true,
            token: tokenInfo.token,
            expiresAt: tokenInfo.expiresAt,
            refreshToken: tokenInfo.refreshToken,
            isDefaultCredentials: app.credentialsWereAutoGenerated,
        };
    });

    router.post("/api/auth/refresh", (ctx: RouterContext) => {
        disableManagementCaching(ctx);
        const { refreshToken } = ctx.request.body as { refreshToken?: string };
        if (!refreshToken) {
            ctx.status = 400;
            ctx.body = { success: false, message: "缺少 refreshToken" };
            return;
        }
        const tokenInfo = app.tokenManager.refreshToken(refreshToken);
        if (!tokenInfo) {
            ctx.status = 401;
            ctx.body = { success: false, message: "refreshToken 无效或已过期" };
            return;
        }
        ctx.body = {
            success: true,
            token: tokenInfo.token,
            expiresAt: tokenInfo.expiresAt,
            refreshToken: tokenInfo.refreshToken,
        };
    });

    /**
     * API auth middleware — protects all /api/* paths EXCEPT login & refresh.
     * Access-token paths (env ONEBOTS_ACCESS_TOKEN / config.access_token) short-circuit
     * the per-session token-manager check.  All other paths go through authValidator
     * which validates the Bearer token issued by the login endpoint.
     */
    router.use("/api", async (ctx: RouterContext, next) => {
        disableManagementCaching(ctx);
        if (ctx.path === "/api/auth/login" || ctx.path === "/api/auth/refresh") return next();

        const token = extractManagementToken(ctx.req);
        const validation = validateManagementToken(app, token);
        if (!validation.valid) {
            logInvalidToken(ctx, token);
            ctx.status = 401;
            ctx.body = { error: "Unauthorized", message: "Unauthorized" };
            return;
        }
        ctx.state.token = token;
        ctx.state.tokenInfo =
            validation.source === "configured"
                ? { metadata: { username: "token" }, expiresAt: null }
                : validation.info;
        return next();
    });

    router.post("/api/auth/logout", (ctx: RouterContext) => {
        const token = ctx.state.token as string | undefined;
        const validation = validateManagementToken(app, token);
        if (token && validation.valid && validation.source === "session") {
            app.tokenManager.revokeToken(token);
        }
        ctx.body = { success: true };
    });

    router.get("/api/auth/me", (ctx: RouterContext) => {
        const tokenInfo = ctx.state.tokenInfo as
            | { expiresAt?: number | null; metadata?: Record<string, unknown> }
            | undefined;
        ctx.body = {
            success: true,
            data: {
                username: tokenInfo?.metadata?.username ?? app.config.username,
                expiresAt: tokenInfo?.expiresAt ?? null,
                isDefaultCredentials: app.credentialsWereAutoGenerated,
            },
        };
    });
}

function disableManagementCaching(ctx: RouterContext): void {
    ctx.set("Cache-Control", "no-store");
}
