import {
    RouterContext,
    ValidationError,
    createRateLimit,
    logAuthFailure,
    logInvalidToken,
} from "@onebots/core";
import type { App } from "../app.js";
import type { Router } from "@onebots/core";
import {
    extractManagementHeaderToken,
    managementAccessTokenMatches,
    managementCredentialsMatch,
    validateManagementToken,
} from "../management-auth.js";
import { setManagementEvidenceIdentity } from "../management-evidence-identity.js";
import {
    assertManagementInstancePrecondition,
    ManagementInstanceMismatchError,
} from "../management-instance-precondition.js";

export const MANAGEMENT_LOGIN_FAILURE_WINDOW_MS = 5 * 60 * 1000;
export const MANAGEMENT_LOGIN_FAILURE_LIMIT = 10;

/**
 * Register authentication-related routes.
 *
 * Computes auth state from app.config rather than relying on start() closure variables.
 * The middleware registered here protects all /api/* routes except login and refresh.
 *
 * A note on the access token: ONEBOTS_ACCESS_TOKEN is a deployment-level override,
 * followed by config.access_token. The access token path skips the per-session token
 * manager and is validated by direct comparison.  The username/password path generates
 * managed tokens via app.tokenManager.
 */
export function registerAuthRoutes(app: App, router: Router): void {
    const loginRateLimit = createRateLimit({
        windowMs: MANAGEMENT_LOGIN_FAILURE_WINDOW_MS,
        max: MANAGEMENT_LOGIN_FAILURE_LIMIT,
        skipSuccessfulRequests: true,
        message: "登录失败次数过多，请稍后再试",
    });
    app.lifecycle.register("managementLoginRateLimit", () => loginRateLimit.close());

    /* ── routes ────────────────────────────────────────────────── */

    router.post("/api/auth/login", async (ctx: RouterContext) => {
        disableManagementCaching(ctx);
        if (!acceptAuthenticationInstance(app, ctx, "登录")) return;
        await loginRateLimit(ctx, async () => {
            const body = ctx.request.body as {
                username?: string;
                password?: string;
                access_token?: string;
            };

            // 鉴权码登录
            if (body.access_token != null && body.access_token !== "") {
                if (managementAccessTokenMatches(app.config, body.access_token)) {
                    ctx.status = 200;
                    ctx.body = {
                        success: true,
                        token: body.access_token,
                        expiresAt: null,
                        refreshToken: null,
                        isDefaultCredentials: false,
                    };
                    return;
                }
                logAuthFailure(ctx, "management_access_token_mismatch");
                ctx.status = 401;
                ctx.body = { success: false, message: "鉴权码错误" };
                return;
            }

            if (!managementCredentialsMatch(app.config, body.username, body.password)) {
                logAuthFailure(ctx, "management_credentials_mismatch");
                ctx.status = 401;
                ctx.body = { success: false, message: "用户名或密码错误" };
                return;
            }

            const tokenInfo = app.tokenManager.generateToken({ username: body.username });
            ctx.status = 200;
            ctx.body = {
                success: true,
                token: tokenInfo.token,
                expiresAt: tokenInfo.expiresAt,
                refreshToken: tokenInfo.refreshToken,
                isDefaultCredentials: app.credentialsWereAutoGenerated,
            };
        });
    });

    router.post("/api/auth/refresh", (ctx: RouterContext) => {
        disableManagementCaching(ctx);
        if (!acceptAuthenticationInstance(app, ctx, "令牌刷新")) return;
        const { refreshToken } = ctx.request.body as { refreshToken?: string };
        if (!refreshToken) {
            ctx.status = 400;
            ctx.body = { success: false, message: "缺少 refreshToken" };
            return;
        }
        const tokenInfo = app.tokenManager.refreshToken(refreshToken);
        if (!tokenInfo) {
            ctx.status = 401;
            ctx.body = { success: false, message: "refreshToken 无效或已过期" };
            return;
        }
        ctx.status = 200;
        ctx.body = {
            success: true,
            token: tokenInfo.token,
            expiresAt: tokenInfo.expiresAt,
            refreshToken: tokenInfo.refreshToken,
        };
    });

    /**
     * API auth middleware — protects all /api/* paths EXCEPT login & refresh.
     * Access-token paths (env ONEBOTS_ACCESS_TOKEN / config.access_token) short-circuit
     * the per-session token-manager check.  All other paths go through authValidator
     * which validates the Bearer token issued by the login endpoint.
     */
    router.use("/api", async (ctx: RouterContext, next) => {
        disableManagementCaching(ctx);
        if (ctx.path === "/api/auth/login" || ctx.path === "/api/auth/refresh") return next();

        const token = extractManagementHeaderToken(ctx.req);
        const validation = validateManagementToken(app, token);
        if (!validation.valid) {
            logInvalidToken(ctx, token);
            ctx.status = 401;
            ctx.body = { error: "Unauthorized", message: "Unauthorized" };
            return;
        }
        ctx.state.token = token;
        ctx.state.tokenInfo =
            validation.source === "configured"
                ? { metadata: { username: "token" }, expiresAt: null }
                : validation.info;
        return next();
    });

    router.post("/api/auth/logout", (ctx: RouterContext) => {
        const token = ctx.state.token as string | undefined;
        const validation = validateManagementToken(app, token);
        if (token && validation.valid && validation.source === "session") {
            app.tokenManager.revokeToken(token);
        }
        ctx.body = { success: true };
    });

    router.get("/api/auth/me", (ctx: RouterContext) => {
        const tokenInfo = ctx.state.tokenInfo as
            | { expiresAt?: number | null; metadata?: Record<string, unknown> }
            | undefined;
        ctx.body = {
            success: true,
            data: {
                username: tokenInfo?.metadata?.username ?? app.config.username,
                expiresAt: tokenInfo?.expiresAt ?? null,
                isDefaultCredentials: app.credentialsWereAutoGenerated,
            },
        };
    });
}

function disableManagementCaching(ctx: RouterContext): void {
    ctx.set("Cache-Control", "no-store");
}

function acceptAuthenticationInstance(app: App, ctx: RouterContext, operation: string): boolean {
    setManagementEvidenceIdentity(app, ctx);
    try {
        assertManagementInstancePrecondition(app, ctx, operation);
        return true;
    } catch (error) {
        ctx.status = error instanceof ManagementInstanceMismatchError ? 409 : 400;
        ctx.body = {
            success: false,
            application: app.info.application_name,
            instance_id: app.info.instance_id,
            code:
                error instanceof ManagementInstanceMismatchError
                    ? "AUTH_INSTANCE_MISMATCH"
                    : "AUTH_REQUEST_INVALID",
            message: error instanceof ValidationError ? error.message : (error as Error).message,
        };
        app.logger.error(`管理端${operation}实例验证失败`, { error });
        return false;
    }
}
