import { RouterContext, createManagedTokenValidator, BaseApp } from "@onebots/core";
import type { App } from "../app.js";
import type { Router } from "@onebots/core";

/**
 * Register authentication-related routes.
 *
 * Computes auth state from app.config rather than relying on start() closure variables.
 * The middleware registered here protects all /api/* routes except login and refresh.
 *
 * A note on the access token: it can come from config.access_token or the environment
 * variable ONEBOTS_ACCESS_TOKEN.  The access token path skips the per-session token
 * manager and is validated by direct comparison.  The username/password path generates
 * managed tokens via app.tokenManager.
 */
export function registerAuthRoutes(app: App, router: Router): void {
    /* ── auth state derived from app.config ───────────────────── */

    const expectedUsername = app.config.username ?? BaseApp.defaultConfig.username!;
    const expectedPassword = app.config.password ?? BaseApp.defaultConfig.password!;
    const expectedAccessToken: string | undefined = (
        (app.config as { access_token?: string }).access_token?.trim()
        || process.env.ONEBOTS_ACCESS_TOKEN?.trim()
        || undefined
    );

    /** Extract a Bearer token or ?access_token from an http.IncomingMessage (used by WebSocket auth). */
    const getTokenFromRequest = (request: import('http').IncomingMessage): string | undefined => {
        const authHeader = request.headers.authorization;
        if (authHeader && typeof authHeader === 'string') {
            const match = authHeader.match(/^Bearer\s+(.+)$/i);
            return match ? match[1] : authHeader;
        }
        try {
            const url = new URL(request.url || '/', 'http://localhost');
            return url.searchParams.get('access_token') || undefined;
        } catch {
            return undefined;
        }
    };

    /** Extract a Bearer token or ?access_token from a Koa / RouterContext. */
    const getTokenFromKoa = (ctx: RouterContext): string | undefined => {
        const authHeader = ctx.request.headers.authorization;
        if (authHeader && typeof authHeader === 'string') {
            const match = authHeader.match(/^Bearer\s+(.+)$/i);
            return match ? match[1] : authHeader;
        }
        return (ctx.request.query?.access_token as string) || undefined;
    };

    const authValidator = createManagedTokenValidator(app.tokenManager, {
        tokenName: 'access_token',
        errorMessage: 'Unauthorized',
    });

    /* ── routes ────────────────────────────────────────────────── */

    router.post("/api/auth/login", (ctx: RouterContext) => {
        const body = ctx.request.body as { username?: string; password?: string; access_token?: string };

        // 鉴权码登录
        if (body.access_token != null && body.access_token !== '') {
            if (expectedAccessToken && body.access_token === expectedAccessToken) {
                ctx.body = {
                    success: true,
                    token: body.access_token,
                    expiresAt: null,
                    refreshToken: null,
                    isDefaultCredentials: false,
                };
                return;
            }
            ctx.status = 401;
            ctx.body = { success: false, message: "鉴权码错误" };
            return;
        }

        if (!body.username || !body.password || body.username !== expectedUsername || body.password !== expectedPassword) {
            ctx.status = 401;
            ctx.body = { success: false, message: "用户名或密码错误" };
            return;
        }

        const tokenInfo = app.tokenManager.generateToken({ username: body.username });
        ctx.body = {
            success: true,
            token: tokenInfo.token,
            expiresAt: tokenInfo.expiresAt,
            refreshToken: tokenInfo.refreshToken,
            isDefaultCredentials: app.credentialsWereAutoGenerated,
        };
    });

    router.post("/api/auth/refresh", (ctx: RouterContext) => {
        const { refreshToken } = ctx.request.body as { refreshToken?: string };
        if (!refreshToken) {
            ctx.status = 400;
            ctx.body = { success: false, message: "缺少 refreshToken" };
            return;
        }
        const tokenInfo = app.tokenManager.refreshToken(refreshToken);
        if (!tokenInfo) {
            ctx.status = 401;
            ctx.body = { success: false, message: "refreshToken 无效或已过期" };
            return;
        }
        ctx.body = {
            success: true,
            token: tokenInfo.token,
            expiresAt: tokenInfo.expiresAt,
            refreshToken: tokenInfo.refreshToken,
        };
    });

    /**
     * API auth middleware — protects all /api/* paths EXCEPT login & refresh.
     * Access-token paths (config.access_token / env ONEBOTS_ACCESS_TOKEN) short-circuit
     * the per-session token-manager check.  All other paths go through authValidator
     * which validates the Bearer token issued by the login endpoint.
     */
    router.use('/api', async (ctx: RouterContext, next) => {
        if (ctx.path === '/api/auth/login' || ctx.path === '/api/auth/refresh') return next();

        const token = getTokenFromKoa(ctx);
        if (expectedAccessToken && token === expectedAccessToken) {
            (ctx as any).state.token = token;
            (ctx as any).state.tokenInfo = { metadata: { username: 'token' }, expiresAt: null };
            return next();
        }
        return authValidator(ctx as any, next as any);
    });

    router.post("/api/auth/logout", (ctx: RouterContext) => {
        const token = ctx.state.token as string | undefined;
        if (token && token !== expectedAccessToken) app.tokenManager.revokeToken(token);
        ctx.body = { success: true };
    });

    router.get("/api/auth/me", (ctx: RouterContext) => {
        const tokenInfo = ctx.state.tokenInfo as { expiresAt?: number | null; metadata?: Record<string, unknown> } | undefined;
        ctx.body = {
            success: true,
            data: {
                username: tokenInfo?.metadata?.username ?? expectedUsername,
                expiresAt: tokenInfo?.expiresAt ?? null,
                isDefaultCredentials: app.credentialsWereAutoGenerated,
            },
        };
    });
}
