import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { BaseApp, HostConfigRestartRequiredError, type RouterContext } from "@onebots/core";
import type { App } from "../app.js";
import { registerConfigRoutes } from "./config.js";

type RouteHandler = (ctx: RouterContext) => void | Promise<void>;

const originalConfigDir = BaseApp.configDir;
const directories: string[] = [];

function setup(reload: App["reload"], isReloading = false) {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), "onebots-config-route-"));
    directories.push(directory);
    BaseApp.configDir = directory;
    fs.writeFileSync(BaseApp.configPath, "access_token: old-token\n", { mode: 0o600 });
    const posts = new Map<string, RouteHandler>();
    const gets = new Map<string, RouteHandler>();
    const router = {
        get: vi.fn((route: string, handler: RouteHandler) => gets.set(route, handler)),
        post: vi.fn((route: string, handler: RouteHandler) => posts.set(route, handler)),
    };
    const app = {
        isReloading,
        reload,
        credentialsWereAutoGenerated: true,
        backupDataToHf: vi.fn(async () => ({ success: true })),
        logger: { warn: vi.fn() },
        info: {},
        pluginInfos: [
            {
                type: "adapter",
                name: "mock",
                packageName: "@onebots/adapter-mock",
                version: "1.0.17",
                entryPath: "/runtime/adapter-mock/lib/index.js",
            },
        ],
    } as unknown as App;
    registerConfigRoutes(app, router as never);
    return {
        app,
        handler: posts.get("/api/config")!,
        systemHandler: gets.get("/api/system")!,
    };
}

afterEach(() => {
    BaseApp.configDir = originalConfigDir;
    for (const directory of directories.splice(0)) {
        fs.rmSync(directory, { recursive: true, force: true });
    }
});

describe("configuration route", () => {
    it("系统信息公开当前进程已验证的插件清单", () => {
        const { systemHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = {} as RouterContext;

        systemHandler(ctx);

        expect(ctx.body).toMatchObject({
            plugins: [
                {
                    type: "adapter",
                    name: "mock",
                    packageName: "@onebots/adapter-mock",
                    version: "1.0.17",
                    entryPath: "/runtime/adapter-mock/lib/index.js",
                },
            ],
        });
    });

    it("返回已保存并生效的机器可读状态", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { app, handler } = setup(reload);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.body).toEqual({
            success: true,
            applied: true,
            restartRequired: false,
            changedHostFields: [],
            message: "配置已保存并生效",
        });
        expect(app.credentialsWereAutoGenerated).toBe(false);
        expect(app.backupDataToHf).toHaveBeenCalledWith("access_token: next-token\n");
    });

    it("宿主配置保留文件并返回重启字段", async () => {
        const reload = vi.fn(async () => {
            throw new HostConfigRestartRequiredError(["port"]);
        }) as App["reload"];
        const { handler } = setup(reload);
        const ctx = { request: { body: "port: 7000\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.body).toMatchObject({
            success: true,
            applied: false,
            restartRequired: true,
            changedHostFields: ["port"],
            message: "配置已保存；port 需要重启后生效",
        });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("port: 7000\n");
    });

    it("重载冲突返回 409 且不覆盖文件", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { handler } = setup(reload, true);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toMatchObject({ success: false });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("access_token: old-token\n");
        expect(reload).not.toHaveBeenCalled();
    });

    it("无效 YAML 返回 400 且不写入文件", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { handler } = setup(reload);
        const ctx = { request: { body: "accounts: [\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(400);
        expect(ctx.body).toMatchObject({ success: false });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("access_token: old-token\n");
        expect(reload).not.toHaveBeenCalled();
    });

    it("可选远端备份异常不会把已生效配置误报为失败", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { app, handler } = setup(reload);
        vi.mocked(app.backupDataToHf).mockRejectedValue(new Error("HF unavailable"));
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBeUndefined();
        expect(ctx.body).toMatchObject({ success: true, applied: true });
        expect(app.logger.warn).toHaveBeenCalledWith("配置已保存并生效，但自动备份失败", {
            error: expect.objectContaining({ message: "HF unavailable" }),
        });
    });
});
