import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
    BaseApp,
    HostConfigRestartRequiredError,
    writeConfigFileAtomic,
    type RouterContext,
} from "@onebots/core";
import type { App } from "../app.js";
import { registerConfigRoutes } from "./config.js";

type RouteHandler = (ctx: RouterContext) => void | Promise<void>;

const originalConfigDir = BaseApp.configDir;
const directories: string[] = [];

function setup(reload: App["reload"], isReloading = false, restartSupported = true) {
    const directory = fs.mkdtempSync(path.join(os.tmpdir(), "onebots-config-route-"));
    directories.push(directory);
    BaseApp.configDir = directory;
    fs.writeFileSync(BaseApp.configPath, "access_token: old-token\n", { mode: 0o600 });
    const posts = new Map<string, RouteHandler>();
    const gets = new Map<string, RouteHandler>();
    const router = {
        get: vi.fn((route: string, handler: RouteHandler) => gets.set(route, handler)),
        post: vi.fn((route: string, handler: RouteHandler) => posts.set(route, handler)),
    };
    const app = {
        isReloading,
        reload,
        credentialsWereAutoGenerated: true,
        backupDataToHf: vi.fn(async () => ({ success: true })),
        preflightRestart: vi.fn(async () => undefined),
        stop: vi.fn(async () => undefined),
        logger: { warn: vi.fn(), error: vi.fn() },
        info: {
            application_name: "onebots",
            application_version: "1.2.8",
            instance_id: "instance-current",
            started_at: "2026-08-31T08:00:00.000Z",
            core_version: "1.2.5",
            sdk_version: "1.2.5",
        },
        pluginInfos: [
            {
                type: "adapter",
                name: "mock",
                packageName: "@onebots/adapter-mock",
                version: "1.0.17",
                entryPath: "/runtime/adapter-mock/lib/index.js",
            },
        ],
        runtimeConfigState: {
            status: "in_sync",
            appliedAt: "2026-08-31T09:00:00.000Z",
            message: "磁盘配置与当前进程最近应用的版本一致",
        },
        runtimeContractId: "sha256:contract-current",
        restartSupported,
    } as unknown as App;
    registerConfigRoutes(app, router as never);
    return {
        app,
        handler: posts.get("/api/config")!,
        systemHandler: gets.get("/api/system")!,
        backupHandler: posts.get("/api/system/backup-to-hf")!,
        restartHandler: posts.get("/api/system/restart")!,
    };
}

afterEach(() => {
    vi.useRealTimers();
    vi.restoreAllMocks();
    BaseApp.configDir = originalConfigDir;
    for (const directory of directories.splice(0)) {
        fs.rmSync(directory, { recursive: true, force: true });
    }
});

describe("configuration route", () => {
    it("以可被守护服务识别的失败码触发重启", async () => {
        vi.useFakeTimers();
        const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
        const { app, restartHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = {
            request: { body: { instance_id: "instance-current" } },
        } as RouterContext;

        await restartHandler(ctx);
        await vi.runAllTimersAsync();

        expect(ctx.body).toMatchObject({
            success: true,
            application: "onebots",
            instance_id: "instance-current",
            scheduled: true,
            restart_supported: true,
        });
        expect(app.preflightRestart).toHaveBeenCalledOnce();
        expect(app.stop).toHaveBeenCalledOnce();
        expect(exit).toHaveBeenCalledWith(75);
        vi.useRealTimers();
    });

    it("前台进程没有监督器时拒绝退出并要求人工重启", async () => {
        vi.useFakeTimers();
        const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
        const { app, restartHandler } = setup(
            vi.fn(async () => undefined) as App["reload"],
            false,
            false,
        );
        const ctx = {
            request: { body: { instance_id: "instance-current" } },
        } as RouterContext;

        await restartHandler(ctx);
        await vi.runAllTimersAsync();

        expect(ctx.status).toBe(409);
        expect(ctx.body).toMatchObject({
            success: false,
            application: "onebots",
            instance_id: "instance-current",
            restart_supported: false,
            message: expect.stringContaining("请手动重启 OneBots"),
        });
        expect(app.preflightRestart).not.toHaveBeenCalled();
        expect(app.stop).not.toHaveBeenCalled();
        expect(exit).not.toHaveBeenCalled();
    });

    it("实例已切换时在预检和调度前拒绝过期的重启请求", async () => {
        vi.useFakeTimers();
        const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
        const { app, restartHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = {
            request: { body: { instance_id: "instance-old" } },
        } as RouterContext;

        await restartHandler(ctx);
        await vi.runAllTimersAsync();

        expect(ctx.status).toBe(409);
        expect(ctx.body).toEqual({
            success: false,
            application: "onebots",
            instance_id: "instance-current",
            message: "重启请求期望实例 instance-old，当前已由实例 instance-current 接管",
        });
        expect(app.preflightRestart).not.toHaveBeenCalled();
        expect(exit).not.toHaveBeenCalled();
    });

    it("拒绝畸形实例身份，同时保留无身份旧客户端兼容", async () => {
        vi.useFakeTimers();
        const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
        const { app, restartHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const malformed = { request: { body: "instance-current" } } as RouterContext;
        await restartHandler(malformed);
        expect(malformed.status).toBe(400);
        expect(malformed.body).toMatchObject({
            success: false,
            message: "重启请求体必须是对象",
        });

        const invalid = { request: { body: { instance_id: " " } } } as RouterContext;

        await restartHandler(invalid);
        expect(invalid.status).toBe(400);
        expect(invalid.body).toMatchObject({
            success: false,
            instance_id: "instance-current",
            message: "重启请求的 instance_id 必须是非空字符串",
        });
        expect(app.preflightRestart).not.toHaveBeenCalled();

        const legacy = { request: { body: undefined } } as RouterContext;
        await restartHandler(legacy);
        await vi.runAllTimersAsync();
        expect(legacy.body).toMatchObject({ success: true, instance_id: "instance-current" });
        expect(exit).toHaveBeenCalledWith(75);
    });

    it("重启预检失败时保持当前服务在线并返回诊断", async () => {
        vi.useFakeTimers();
        const exit = vi.spyOn(process, "exit").mockImplementation((() => undefined) as never);
        const { app, restartHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        vi.mocked(app.preflightRestart).mockRejectedValue(new Error("插件入口损坏"));
        const ctx = {} as RouterContext;

        await restartHandler(ctx);
        await vi.runAllTimersAsync();

        expect(ctx.status).toBe(422);
        expect(ctx.body).toEqual({
            success: false,
            message: "重启预检失败：插件入口损坏",
        });
        expect(exit).not.toHaveBeenCalled();
        expect(app.logger.error).toHaveBeenCalledWith("管理端重启预检失败，当前服务继续运行", {
            error: expect.objectContaining({ message: "插件入口损坏" }),
        });
    });

    it("系统信息公开当前进程已验证的插件清单", () => {
        const { systemHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = { set: vi.fn() } as unknown as RouterContext;

        systemHandler(ctx);

        expect(ctx.body).toMatchObject({
            application_name: "onebots",
            application_version: "1.2.8",
            core_version: "1.2.5",
            runtime_contract_id: "sha256:contract-current",
            configState: {
                status: "in_sync",
                appliedAt: "2026-08-31T09:00:00.000Z",
            },
            restartSupported: true,
            plugins: [
                {
                    type: "adapter",
                    name: "mock",
                    packageName: "@onebots/adapter-mock",
                    version: "1.0.17",
                    entryPath: "/runtime/adapter-mock/lib/index.js",
                },
            ],
        });
        expect(ctx.set).toHaveBeenCalledWith("X-OneBots-Instance-Id", "instance-current");
        expect(ctx.set).toHaveBeenCalledWith(
            "X-OneBots-Runtime-Contract-Id",
            "sha256:contract-current",
        );
        expect(ctx.set).toHaveBeenCalledWith("Cache-Control", "no-store");
    });

    it("实例已切换时拒绝使用旧系统快照触发备份", async () => {
        const { app, backupHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = {
            request: { body: { instance_id: "instance-before-restart" } },
        } as RouterContext;

        await backupHandler(ctx);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toEqual({
            success: false,
            application: "onebots",
            instance_id: "instance-current",
            message: "备份请求期望实例 instance-before-restart，当前已由实例 instance-current 接管",
        });
        expect(app.backupDataToHf).not.toHaveBeenCalled();
    });

    it("备份成功回执证明处理请求的实例", async () => {
        const { app, backupHandler } = setup(vi.fn(async () => undefined) as App["reload"]);
        const ctx = {
            request: { body: { instance_id: "instance-current" } },
        } as RouterContext;

        await backupHandler(ctx);

        expect(ctx.body).toEqual({
            success: true,
            application: "onebots",
            instance_id: "instance-current",
            message: "已备份到仓库",
        });
        expect(app.backupDataToHf).toHaveBeenCalledWith("access_token: old-token\n");
    });

    it("返回已保存并生效的机器可读状态", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { app, handler } = setup(reload);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.body).toEqual({
            success: true,
            applied: true,
            restartRequired: false,
            changedHostFields: [],
            message: "配置已保存并生效",
        });
        expect(app.credentialsWereAutoGenerated).toBe(false);
        expect(app.backupDataToHf).toHaveBeenCalledWith("access_token: next-token\n");
    });

    it("宿主配置保留文件并返回重启字段", async () => {
        const reload = vi.fn(async () => {
            throw new HostConfigRestartRequiredError(["port"]);
        }) as App["reload"];
        const { handler } = setup(reload);
        const ctx = { request: { body: "port: 7000\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.body).toMatchObject({
            success: true,
            applied: false,
            restartRequired: true,
            changedHostFields: ["port"],
            message: "配置已保存；port 需要重启后生效",
        });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("port: 7000\n");
    });

    it("重载冲突返回 409 且不覆盖文件", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { handler } = setup(reload, true);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toMatchObject({ success: false });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("access_token: old-token\n");
        expect(reload).not.toHaveBeenCalled();
    });

    it("外部配置写入导致回滚冲突时返回 409 并保留新文件", async () => {
        const concurrent = "access_token: external-token\nlog_level: debug\n";
        const reload = vi.fn(async () => {
            writeConfigFileAtomic(BaseApp.configPath, concurrent);
            throw new Error("adapter failed");
        }) as App["reload"];
        const { handler } = setup(reload);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toEqual({
            success: false,
            message: "配置应用失败，且磁盘配置已被另一操作更新；已保留最新文件",
        });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe(concurrent);
    });

    it("应用成功后发现外部配置写入时返回 409 而不是误报保存成功", async () => {
        const concurrent = "access_token: external-token\nlog_level: debug\n";
        const reload = vi.fn(async () => {
            writeConfigFileAtomic(BaseApp.configPath, concurrent);
        }) as App["reload"];
        const { app, handler } = setup(reload);
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(409);
        expect(ctx.body).toEqual({
            success: false,
            message: "配置运行态处理完成，但磁盘配置已被另一操作更新；已保留最新文件，请重新加载",
        });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe(concurrent);
        expect(app.backupDataToHf).not.toHaveBeenCalled();
    });

    it("无效 YAML 返回 400 且不写入文件", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { handler } = setup(reload);
        const ctx = { request: { body: "accounts: [\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBe(400);
        expect(ctx.body).toMatchObject({ success: false });
        expect(fs.readFileSync(BaseApp.configPath, "utf8")).toBe("access_token: old-token\n");
        expect(reload).not.toHaveBeenCalled();
    });

    it("可选远端备份异常不会把已生效配置误报为失败", async () => {
        const reload = vi.fn(async () => undefined) as App["reload"];
        const { app, handler } = setup(reload);
        vi.mocked(app.backupDataToHf).mockRejectedValue(new Error("HF unavailable"));
        const ctx = { request: { body: "access_token: next-token\n" } } as RouterContext;

        await handler(ctx);

        expect(ctx.status).toBeUndefined();
        expect(ctx.body).toMatchObject({ success: true, applied: true });
        expect(app.logger.warn).toHaveBeenCalledWith("配置已保存并生效，但自动备份失败", {
            error: expect.objectContaining({ message: "HF unavailable" }),
        });
    });
});
