import { RouterContext, BaseApp, ValidationError } from "@onebots/core";
import type { Router } from "@onebots/core";
import { readFileSync } from "fs";
import type { App } from "../app.js";
import { getAppConfigSchema } from "../config-schema.js";
import { saveManagedRuntimeConfig } from "../managed-runtime-config.js";
import { isRuntimeConfigApplicationConflict } from "../runtime-config-application.js";
import { scheduleProcessRestart } from "../process-restart.js";
import { setManagementEvidenceIdentity } from "../management-evidence-identity.js";

/**
 * Register configuration and system management routes.
 *
 * - GET/POST /api/config — read / write the config YAML file
 * - GET  /api/config/schema — JSON schema for the config
 * - GET  /api/system — app info, runtime plugin inventory and config sync state
 * - POST /api/system/restart — graceful shutdown
 * - POST /api/system/backup-to-hf — push config + data dir to Hugging Face
 */
export function registerConfigRoutes(app: App, router: Router): void {
    router.get("/api/config", (ctx: RouterContext) => {
        ctx.body = readFileSync(BaseApp.configPath, "utf8");
    });

    router.get("/api/config/schema", (ctx: RouterContext) => {
        ctx.body = getAppConfigSchema();
    });

    router.post("/api/config", async (ctx: RouterContext) => {
        const configContent = ctx.request.body as string;
        try {
            ctx.body = await saveManagedRuntimeConfig(app, configContent);
        } catch (error) {
            ctx.status = isRuntimeConfigApplicationConflict(error)
                ? 409
                : error instanceof ValidationError
                  ? 400
                  : 500;
            ctx.body = { success: false, message: (error as Error).message };
        }
    });

    router.get("/api/system", (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        ctx.body = {
            ...app.info,
            runtime_contract_id: app.runtimeContractId,
            isDefaultCredentials: app.credentialsWereAutoGenerated,
            configDir: BaseApp.configDir,
            configPath: BaseApp.configPath,
            dataDir: BaseApp.dataDir,
            plugins: app.pluginInfos,
            configState: app.runtimeConfigState,
            restartSupported: app.restartSupported,
        };
    });

    /** 手动将 data 与配置备份到 HF 仓库（与保存配置时的备份逻辑一致） */
    router.post("/api/system/backup-to-hf", async (ctx: RouterContext) => {
        const application = app.info.application_name;
        const instanceId = app.info.instance_id;
        const expectedInstanceId = readExpectedSystemInstanceId(ctx.request?.body, "备份");
        if (expectedInstanceId instanceof Error) {
            ctx.status = 400;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: expectedInstanceId.message,
            };
            return;
        }
        if (expectedInstanceId && expectedInstanceId !== instanceId) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: `备份请求期望实例 ${expectedInstanceId}，当前已由实例 ${instanceId} 接管`,
            };
            return;
        }
        try {
            const configContent = readFileSync(BaseApp.configPath, "utf8");
            const result = await app.backupDataToHf(configContent);
            if (result.success) {
                ctx.body = {
                    success: true,
                    application,
                    instance_id: instanceId,
                    message: "已备份到仓库",
                };
            } else {
                ctx.status = 400;
                ctx.body = {
                    success: false,
                    application,
                    instance_id: instanceId,
                    message: result.message ?? "备份失败",
                };
            }
        } catch (error) {
            ctx.status = 500;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: error instanceof Error ? error.message : "备份失败",
            };
            app.logger.error("管理端手动备份失败", { error });
        }
    });

    /** 预检通过后以临时失败码退出，让服务管理器或容器策略重新拉起。 */
    router.post("/api/system/restart", async (ctx: RouterContext) => {
        const application = app.info.application_name;
        const instanceId = app.info.instance_id;
        const requestBody: unknown = ctx.request?.body;
        const expectedInstanceId = readExpectedSystemInstanceId(requestBody, "重启");
        if (expectedInstanceId instanceof Error) {
            ctx.status = 400;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: expectedInstanceId.message,
            };
            return;
        }
        if (expectedInstanceId && expectedInstanceId !== instanceId) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: `重启请求期望实例 ${expectedInstanceId}，当前已由实例 ${instanceId} 接管`,
            };
            return;
        }
        if (!app.restartSupported) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                restart_supported: false,
                message:
                    "当前进程没有可验证的重启监督器，未停止服务；请手动重启 OneBots，或以守护服务运行",
            };
            return;
        }
        try {
            await app.preflightRestart();
            const scheduled = scheduleProcessRestart(app, { exitCode: 75 });
            ctx.body = {
                success: true,
                application,
                instance_id: instanceId,
                restart_supported: true,
                scheduled,
                message: scheduled ? "重启预检通过，服务即将重启" : "服务重启已在进行中",
            };
        } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            ctx.status = 422;
            ctx.body = { success: false, message: `重启预检失败：${message}` };
            app.logger.error("管理端重启预检失败，当前服务继续运行", { error });
        }
    });
}

function readExpectedSystemInstanceId(
    value: unknown,
    operation: "重启" | "备份",
): string | null | Error {
    if (value === undefined || value === null) return null;
    if (typeof value !== "object" || Array.isArray(value)) {
        return new Error(`${operation}请求体必须是对象`);
    }
    if (!("instance_id" in value)) return null;
    const instanceId = value.instance_id;
    if (typeof instanceId !== "string" || !instanceId.trim()) {
        return new Error(`${operation}请求的 instance_id 必须是非空字符串`);
    }
    return instanceId.trim();
}
