import { RouterContext, BaseApp } from "@onebots/core";
import type { Router } from "@onebots/core";
import { readFileSync, writeFileSync } from "fs";
import type { App } from "../app.js";
import { getAppConfigSchema } from "../config-schema.js";

/**
 * Register configuration and system management routes.
 *
 * - GET/POST /api/config — read / write the config YAML file
 * - GET  /api/config/schema — JSON schema for the config
 * - GET  /api/system — app info
 * - POST /api/system/restart — graceful shutdown
 * - POST /api/system/backup-to-hf — push config + data dir to Hugging Face
 */
export function registerConfigRoutes(app: App, router: Router): void {
    router.get("/api/config", (ctx: RouterContext) => {
        ctx.body = readFileSync(BaseApp.configPath, "utf8");
    });

    router.get("/api/config/schema", (ctx: RouterContext) => {
        ctx.body = getAppConfigSchema();
    });

    router.post("/api/config", async (ctx: RouterContext) => {
        try {
            const configContent = ctx.request.body as string;
            writeFileSync(BaseApp.configPath, configContent, "utf8");
            app.credentialsWereAutoGenerated = false;
            const backupResult = await app.backupDataToHf(configContent);
            if (!backupResult.success && backupResult.message) {
                app.logger?.warn?.(backupResult.message);
            }
            ctx.body = { success: true, message: "配置已保存" };
        } catch (e) {
            ctx.status = 500;
            ctx.body = { success: false, message: (e as Error).message };
        }
    });

    router.get("/api/system", (ctx: RouterContext) => {
        ctx.body = {
            ...app.info,
            isDefaultCredentials: app.credentialsWereAutoGenerated,
            configDir: BaseApp.configDir,
            configPath: BaseApp.configPath,
            dataDir: BaseApp.dataDir,
        };
    });

    /** 手动将 data 与配置备份到 HF 仓库（与保存配置时的备份逻辑一致） */
    router.post("/api/system/backup-to-hf", async (ctx: RouterContext) => {
        try {
            const configContent = readFileSync(BaseApp.configPath, "utf8");
            const result = await app.backupDataToHf(configContent);
            if (result.success) {
                ctx.body = { success: true, message: "已备份到仓库" };
            } else {
                ctx.status = 400;
                ctx.body = { success: false, message: result.message ?? "备份失败" };
            }
        } catch (e) {
            ctx.status = 500;
            ctx.body = { success: false, message: (e as Error).message };
        }
    });

    /** 重启服务：进程退出后由 Docker 的 restart 策略自动拉起容器；非 Docker 需手动重新启动 */
    router.post("/api/system/restart", (ctx: RouterContext) => {
        ctx.body = { success: true, message: "服务即将重启" };
        setImmediate(() => {
            setTimeout(() => {
                process.exit(0);
            }, 1500);
        });
    });
}
