import { RouterContext, ValidationError } from "@onebots/core";
import type { Router } from "@onebots/core";
import { readFileSync } from "fs";
import type { App } from "../app.js";
import { getAppConfigSchema } from "../config-schema.js";
import { saveManagedRuntimeConfig } from "../managed-runtime-config.js";
import {
    isRuntimeConfigApplicationConflict,
    RuntimeConfigApplicationConflictError,
    RuntimeConfigPostApplyConflictError,
    RuntimeConfigRollbackConflictError,
} from "../runtime-config-application.js";
import { scheduleProcessRestart } from "../process-restart.js";
import { setManagementEvidenceIdentity } from "../management-evidence-identity.js";
import {
    assertManagementInstancePrecondition,
    ManagementInstanceMismatchError,
} from "../management-instance-precondition.js";
import {
    assertManagementConfigRevisionPrecondition,
    ManagementConfigRevisionMismatchError,
    setManagementConfigRevision,
} from "../management-config-revision.js";

/**
 * Register configuration and system management routes.
 *
 * - GET/POST /api/config — read / write the config YAML file
 * - GET  /api/config/schema — JSON schema for the config
 * - GET  /api/system — app info, runtime plugin inventory and config sync state
 * - POST /api/system/restart — graceful shutdown
 * - POST /api/system/backup-to-hf — push config + data dir to Hugging Face
 */
export function registerConfigRoutes(app: App, router: Router): void {
    router.get("/api/config", (ctx: RouterContext) => {
        const content = readFileSync(app.configPath, "utf8");
        setManagementEvidenceIdentity(app, ctx);
        setManagementConfigRevision(ctx, content);
        ctx.body = content;
    });

    router.get("/api/config/schema", (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        ctx.body = getAppConfigSchema();
    });

    router.post("/api/config", async (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        const configContent = ctx.request.body as string;
        try {
            assertManagementInstancePrecondition(app, ctx, "配置保存");
            assertManagementConfigRevisionPrecondition(ctx, "配置保存", app.configPath);
            const result = await saveManagedRuntimeConfig(app, configContent, app.configPath);
            const configRevision = setManagementConfigRevision(ctx, configContent);
            ctx.body = {
                ...result,
                operation: "save",
                application: app.info.application_name,
                instance_id: app.info.instance_id,
                config_revision: configRevision,
            };
        } catch (error) {
            ctx.status =
                error instanceof ManagementInstanceMismatchError ||
                error instanceof ManagementConfigRevisionMismatchError
                    ? 409
                    : isRuntimeConfigApplicationConflict(error)
                      ? 409
                      : error instanceof ValidationError
                        ? 400
                        : 500;
            ctx.body = {
                success: false,
                application: app.info.application_name,
                instance_id: app.info.instance_id,
                code: configurationMutationFailureCode(error),
                message: (error as Error).message,
            };
            app.logger.error("管理端配置保存失败", { error });
        }
    });

    router.get("/api/system", (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        ctx.body = {
            ...app.info,
            runtime_contract_id: app.runtimeContractId,
            isDefaultCredentials: app.credentialsWereAutoGenerated,
            configDir: app.configDir,
            configPath: app.configPath,
            dataDir: app.dataDir,
            plugins: app.pluginInfos,
            configState: app.runtimeConfigState,
            restartSupported: app.restartSupported,
        };
    });

    /** 手动将 data 与配置备份到 HF 仓库（与保存配置时的备份逻辑一致） */
    router.post("/api/system/backup-to-hf", async (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        const application = app.info.application_name;
        const instanceId = app.info.instance_id;
        try {
            assertManagementInstancePrecondition(app, ctx, "备份");
        } catch (error) {
            ctx.status =
                error instanceof ManagementInstanceMismatchError
                    ? 409
                    : error instanceof ValidationError
                      ? 400
                      : 500;
            ctx.body = systemOperationFailure(app, error, "备份请求无效");
            app.logger.error("管理端备份实例校验失败", { error });
            return;
        }
        const expectedInstanceId = readExpectedSystemInstanceId(ctx.request?.body, "备份");
        if (expectedInstanceId instanceof Error) {
            ctx.status = 400;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: expectedInstanceId.message,
            };
            return;
        }
        if (expectedInstanceId && expectedInstanceId !== instanceId) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: `备份请求期望实例 ${expectedInstanceId}，当前已由实例 ${instanceId} 接管`,
            };
            return;
        }
        try {
            const configContent = readFileSync(app.configPath, "utf8");
            const result = await app.backupDataToHf(configContent);
            if (result.success) {
                ctx.body = {
                    success: true,
                    application,
                    instance_id: instanceId,
                    message: result.message ?? "已备份到仓库",
                };
            } else {
                ctx.status = 400;
                ctx.body = {
                    success: false,
                    application,
                    instance_id: instanceId,
                    message: result.message ?? "备份失败",
                };
            }
        } catch (error) {
            ctx.status = 500;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: error instanceof Error ? error.message : "备份失败",
            };
            app.logger.error("管理端手动备份失败", { error });
        }
    });

    /** 预检通过后以临时失败码退出，让服务管理器或容器策略重新拉起。 */
    router.post("/api/system/restart", async (ctx: RouterContext) => {
        setManagementEvidenceIdentity(app, ctx);
        const application = app.info.application_name;
        const instanceId = app.info.instance_id;
        try {
            assertManagementInstancePrecondition(app, ctx, "重启");
        } catch (error) {
            ctx.status =
                error instanceof ManagementInstanceMismatchError
                    ? 409
                    : error instanceof ValidationError
                      ? 400
                      : 500;
            ctx.body = systemOperationFailure(app, error, "重启请求无效");
            app.logger.error("管理端重启实例校验失败", { error });
            return;
        }
        const requestBody: unknown = ctx.request?.body;
        const expectedInstanceId = readExpectedSystemInstanceId(requestBody, "重启");
        if (expectedInstanceId instanceof Error) {
            ctx.status = 400;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: expectedInstanceId.message,
            };
            return;
        }
        if (expectedInstanceId && expectedInstanceId !== instanceId) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                message: `重启请求期望实例 ${expectedInstanceId}，当前已由实例 ${instanceId} 接管`,
            };
            return;
        }
        if (!app.restartSupported) {
            ctx.status = 409;
            ctx.body = {
                success: false,
                application,
                instance_id: instanceId,
                restart_supported: false,
                message:
                    "当前进程没有可验证的重启监督器，未停止服务；请手动重启 OneBots，或以守护服务运行",
            };
            return;
        }
        try {
            await app.preflightRestart();
            const scheduled = scheduleProcessRestart(app, { exitCode: 75 });
            ctx.body = {
                success: true,
                application,
                instance_id: instanceId,
                restart_supported: true,
                scheduled,
                message: scheduled ? "重启预检通过，服务即将重启" : "服务重启已在进行中",
            };
        } catch (error) {
            const message = error instanceof Error ? error.message : String(error);
            ctx.status = 422;
            ctx.body = {
                ...systemOperationFailure(app, error, "重启预检失败"),
                message: `重启预检失败：${message}`,
            };
            app.logger.error("管理端重启预检失败，当前服务继续运行", { error });
        }
    });
}

function configurationMutationFailureCode(error: unknown): string {
    if (error instanceof ManagementInstanceMismatchError) return "CONFIG_INSTANCE_MISMATCH";
    if (error instanceof ManagementConfigRevisionMismatchError) return "CONFIG_REVISION_MISMATCH";
    if (
        error instanceof RuntimeConfigRollbackConflictError ||
        error instanceof RuntimeConfigPostApplyConflictError
    ) {
        return "CONFIG_DRIFT";
    }
    if (error instanceof RuntimeConfigApplicationConflictError) return "CONFIG_BUSY";
    if (error instanceof ValidationError) return "CONFIG_INVALID";
    return "CONFIG_APPLY_FAILED";
}

function systemOperationFailure(app: App, error: unknown, fallback: string) {
    return {
        success: false,
        application: app.info.application_name,
        instance_id: app.info.instance_id,
        message: error instanceof Error ? error.message : fallback,
    };
}

function readExpectedSystemInstanceId(
    value: unknown,
    operation: "重启" | "备份",
): string | null | Error {
    if (value === undefined || value === null) return null;
    if (typeof value !== "object" || Array.isArray(value)) {
        return new Error(`${operation}请求体必须是对象`);
    }
    if (!("instance_id" in value)) return null;
    const instanceId = value.instance_id;
    if (typeof instanceId !== "string" || !instanceId.trim()) {
        return new Error(`${operation}请求的 instance_id 必须是非空字符串`);
    }
    return instanceId.trim();
}
