import {
    defineAdapterCapabilities,
    type AdapterCapabilityManifest,
    type CapabilityDescriptor,
} from "onebots";

const manageGuild: CapabilityDescriptor = {
    support: "native",
    availability: "permission",
    permissions: ["guild.manage"],
};

/** QQ 官方机器人 SDK 通过通用动作和平台扩展动作暴露的能力。 */
export const qqCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "direct", "channel"] },
        delete_message: { support: "native", scenes: ["direct", "channel"] },
        get_message: { support: "native", scenes: ["direct", "channel"] },
        get_login_info: { support: "native" },
        get_group_info: { support: "native", scenes: ["group"] },
        get_guild_info: { support: "native" },
        get_guild_list: { support: "native" },
        get_guild_member_info: { support: "native" },
        get_channel_info: { support: "native" },
        get_channel_list: { support: "native" },
        create_channel: manageGuild,
        update_channel: manageGuild,
        delete_channel: manageGuild,
        get_channel_member_list: { support: "native" },
        kick_channel_member: manageGuild,
        set_channel_member_mute: manageGuild,
        upload_file: { support: "native", scenes: ["group"] },
        create_user_channel: { support: "native", scenes: ["direct"] },
        handle_group_request: { support: "native", availability: "context" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },

        kick_guild_member: manageGuild,
        mute_guild_member: manageGuild,
        unmute_guild_member: manageGuild,
        mute_guild: manageGuild,
        unmute_guild: manageGuild,
        get_guild_roles: { support: "native" },
        create_guild_role: manageGuild,
        update_guild_role: manageGuild,
        delete_guild_role: manageGuild,
        add_guild_member_role: manageGuild,
        remove_guild_member_role: manageGuild,
        set_channel_announce: manageGuild,
        get_channel_pins: { support: "native" },
        pin_channel_message: manageGuild,
        unpin_channel_message: manageGuild,
        add_reaction: { support: "native" },
        remove_reaction: { support: "native" },
        get_reaction_members: { support: "native" },
        get_schedules: { support: "native" },
        get_schedule: { support: "native" },
        create_schedule: manageGuild,
        update_schedule: manageGuild,
        delete_schedule: manageGuild,
        get_channel_threads: { support: "native" },
        get_channel_thread: { support: "native" },
        publish_thread: { support: "native" },
        delete_thread: manageGuild,
        control_channel_audio: manageGuild,
        get_channel_permission_of_role: { support: "native" },
        update_channel_permission_of_role: manageGuild,
        get_channel_member_permission: { support: "native" },
        update_channel_member_permission: manageGuild,
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "direct", "channel"] },
        message_audit: { support: "native" },
        guild_updated: { support: "native" },
        guild_deleted: { support: "native" },
        channel_created: { support: "native" },
        channel_updated: { support: "native" },
        channel_deleted: { support: "native" },
        guild_member_increase: { support: "native" },
        guild_member_update: { support: "native" },
        guild_member_decrease: { support: "native" },
        reaction_updated: { support: "native" },
        interaction: { support: "native" },
        group_action: { support: "native", scenes: ["group"] },
        friend_action: { support: "native", scenes: ["private"] },
        friend_receive: { support: "native", scenes: ["private"] },
        group_receive: { support: "native", scenes: ["group"] },
        group_member_change: { support: "native", scenes: ["group"] },
        group_join_request: { support: "native", scenes: ["group"] },
        forum: { support: "native", scenes: ["channel"] },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "both" },
        face: { support: "native", direction: "both" },
        image: { support: "native", direction: "both" },
        reply: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        markdown: { support: "native", direction: "both" },
        ark: { support: "native", direction: "both" },
        embed: { support: "native", direction: "both" },
        keyboard: { support: "native", direction: "both" },
        link: { support: "native", direction: "both" },
        button: { support: "native", direction: "both" },
    },
    transports: {
        gateway: { support: "native", mode: "websocket" },
        webhook: { support: "native", mode: "webhook" },
    },
});
