import {
    defineAdapterCapabilities,
    type AdapterCapabilityManifest,
    type CapabilityDescriptor,
} from "onebots";

const manageGuild: CapabilityDescriptor = {
    support: "native",
    availability: "permission",
    permissions: ["guild.manage"],
};

const manageBotUi: CapabilityDescriptor = {
    support: "native",
    availability: "permission",
    permissions: ["bot.ui.manage"],
};

/** 腾讯 QQ 官方 SDK 与 OpenAPI 实际可执行能力。 */
export const qqCapabilities: AdapterCapabilityManifest = defineAdapterCapabilities({
    actions: {
        send_message: { support: "native", scenes: ["private", "group", "direct", "channel"] },
        delete_message: { support: "native", scenes: ["private", "group", "direct", "channel"] },
        get_message: { support: "native", scenes: ["direct", "channel"] },
        get_login_info: { support: "native" },
        get_group_info: { support: "native", scenes: ["group"] },
        get_guild_info: { support: "native" },
        get_guild_list: { support: "native" },
        get_guild_member_info: { support: "native" },
        get_guild_member_list: { support: "native" },
        get_channel_info: { support: "native" },
        get_channel_list: { support: "native" },
        create_channel: manageGuild,
        update_channel: manageGuild,
        delete_channel: manageGuild,
        upload_file: { support: "native", scenes: ["private", "group"] },
        create_user_channel: { support: "native", scenes: ["direct"] },
        can_send_image: { support: "native" },
        can_send_record: { support: "native" },
        get_version: { support: "native" },
        get_status: { support: "native" },
        get_supported_actions: { support: "native" },

        qq_call: { support: "native" },
        send_wakeup: { support: "native", scenes: ["private"] },
        send_typing: { support: "native", scenes: ["private"] },
        acknowledge_interaction: { support: "native" },
        approve_group_join_request: manageGuild,
        get_group_join_requests: manageGuild,
        get_group_restrict_chat: manageGuild,
        set_group_restrict_chat: manageGuild,
        get_group_bot_state: { support: "native" },
        get_group_join_approval_strategies: manageGuild,
        create_group_join_approval_strategy: manageGuild,
        update_group_join_approval_strategy: manageGuild,
        delete_group_join_approval_strategy: manageGuild,
        execute_group_join_approval_strategy: manageGuild,
        update_group_join_approval_whitelist: manageGuild,
        kick_guild_member: manageGuild,
        mute_guild_member: manageGuild,
        mute_guild: manageGuild,
        get_guild_roles: { support: "native" },
        create_guild_role: manageGuild,
        update_guild_role: manageGuild,
        delete_guild_role: manageGuild,
        add_guild_member_role: manageGuild,
        remove_guild_member_role: manageGuild,
        set_channel_announce: manageGuild,
        get_channel_pins: { support: "native" },
        pin_channel_message: manageGuild,
        unpin_channel_message: manageGuild,
        add_reaction: { support: "native" },
        remove_reaction: { support: "native" },
        get_reaction_members: { support: "native" },
        get_schedules: { support: "native" },
        get_schedule: { support: "native" },
        create_schedule: manageGuild,
        update_schedule: manageGuild,
        delete_schedule: manageGuild,
        get_channel_threads: { support: "native" },
        get_channel_thread: { support: "native" },
        publish_thread: { support: "native" },
        delete_thread: manageGuild,
        control_channel_audio: manageGuild,
        put_channel_microphone: manageGuild,
        delete_channel_microphone: manageGuild,
        get_channel_permission_of_role: { support: "native" },
        update_channel_permission_of_role: manageGuild,
        get_channel_member_permission: { support: "native" },
        update_channel_member_permission: manageGuild,
        get_guild_api_permissions: { support: "native" },
        demand_guild_api_permission: manageGuild,
        generate_share_link: { support: "native" },
        get_bot_menu: { support: "native" },
        update_bot_menu: manageBotUi,
        list_bot_panels: { support: "native" },
        create_bot_panel: manageBotUi,
        get_bot_panel: { support: "native" },
        update_bot_panel: manageBotUi,
        delete_bot_panel: manageBotUi,
        publish_bot_panel: manageBotUi,
    },
    events: {
        message: { support: "native", scenes: ["private", "group", "direct", "channel"] },
        friend_add: { support: "native", scenes: ["private"] },
        friend_remove: { support: "native", scenes: ["private"] },
        group_increase: { support: "native", scenes: ["group"] },
        group_decrease: { support: "native", scenes: ["group"] },
        member_joined: { support: "native", scenes: ["group", "channel"] },
        user_updated: { support: "native", scenes: ["group", "channel"] },
        member_left: { support: "native", scenes: ["group", "channel"] },
        message_status: {
            support: "native",
            scenes: ["private", "group", "direct", "channel"],
        },
        message_deleted: { support: "native", scenes: ["direct", "channel"] },
        reaction_added: { support: "native", scenes: ["channel"] },
        reaction_removed: { support: "native", scenes: ["channel"] },
        interaction: { support: "native" },
        group_join_request: { support: "native", scenes: ["group"] },
        native_dispatch: {
            support: "native",
            note: "频道、Guild、论坛、音频及未来 Gateway 事件以结构化 custom notice 和 raw_event 无损交付",
        },
    },
    segments: {
        text: { support: "native", direction: "both" },
        at: { support: "native", direction: "both" },
        face: { support: "native", direction: "send" },
        image: { support: "native", direction: "both" },
        reply: { support: "native", direction: "both" },
        video: { support: "native", direction: "both" },
        audio: { support: "native", direction: "both" },
        file: { support: "native", direction: "both" },
        markdown: { support: "native", direction: "send" },
        ark: { support: "native", direction: "send" },
        embed: { support: "native", direction: "send" },
        keyboard: { support: "native", direction: "send" },
        button: { support: "native", direction: "send" },
    },
    transports: {
        gateway: { support: "native", mode: "websocket" },
        webhook: { support: "native", mode: "webhook" },
        manual: {
            support: "native",
            mode: "native",
            note: "通过 Client.ingest() 或 acceptHttp(Request) 接入既有 Host",
        },
    },
});
